name = "edgerelay-account-relay"
main = "src/index.ts"
compatibility_date = "2024-12-30"

[durable_objects]
bindings = [
  { name = "ACCOUNT_RELAY", class_name = "AccountRelay" }
]

[[migrations]]
tag = "v1"
new_classes = ["AccountRelay"]

[[d1_databases]]
binding = "DB"
database_name = "edgerelay-db"
database_id = "8a0eb54a-7072-40fd-8a34-22c6fb3471e0"
