// ── ICC Market Bias Engine Types ──────────────────────────────────
//
// ICC = Indication, Correction, Continuation — a price-action methodology
// that reads pure swing structure on a "boss" timeframe (4H) to determine
// higher-timeframe directional bias. These types are shared between the
// api-gateway worker (producer) and the web frontend (consumer).

export type BiasDirection = 'BULLISH' | 'BEARISH' | 'NEUTRAL';

export type MarketStateKind = 'UPTREND' | 'DOWNTREND' | 'CONSOLIDATION';

export type ICCPhaseKind =
  | 'INDICATION'
  | 'CORRECTION'
  | 'CONTINUATION'
  | 'NO_SETUP';

export type CorrectionZoneKind =
  | 'Above Impulse'
  | 'Shallow (0-38%)'
  | 'Optimal (38-62%)'
  | 'Deep (62-79%)'
  | 'Critical (79%+)'
  | 'N/A';

export type SessionKind =
  | 'Asian'
  | 'London'
  | 'New York'
  | 'London-NY Overlap'
  | 'Off-Hours';

export type MomentumKind = 'Strong' | 'Moderate' | 'Weak' | 'Indecisive';

export interface SwingPoint {
  type: 'high' | 'low';
  price: number;
  /** Index into the candle array passed to the analyzer (0 = oldest). */
  index: number;
}

export interface MarketStateModule {
  score: number;
  state: MarketStateKind;
  swingSequence: string;
  tradeable: boolean;
}

export interface ICCPhaseModule {
  score: number;
  current: ICCPhaseKind;
  detail: string;
  indicationLevel: number | null;
  correctionDepth: number | null;
  entryReady: boolean;
}

export interface SwingStructureModule {
  score: number;
  keyLevels: {
    lastSwingHigh: number | null;
    lastSwingLow: number | null;
    previousSwingHigh: number | null;
    previousSwingLow: number | null;
  };
  recentBreaks: Array<{ level: number; direction: 'above' | 'below'; barsAgo: number }>;
}

export interface CorrectionModule {
  score: number;
  impulseRange: { high: number; low: number } | null;
  currentDepth: number | null;
  inOptimalZone: boolean;
  zone: CorrectionZoneKind;
  retracementLevels: {
    r25: number;
    r38: number;
    r50: number;
    r62: number;
    r79: number;
  } | null;
}

export interface SessionModule {
  score: number;
  active: SessionKind;
  momentum: MomentumKind;
  relevance: 'High' | 'Medium' | 'Low';
  recentCandleProfile: string;
}

export interface ICCBreakdown {
  marketState: MarketStateModule;
  phase: ICCPhaseModule;
  structure: SwingStructureModule;
  correction: CorrectionModule;
  session: SessionModule;
}

/** Suggested reference levels derived from ICC structure. Only present
 *  when phase === 'CONTINUATION' AND tradeable AND the impulse range is
 *  clean. Always framed as planning reference — real entries require a
 *  lower-TF trigger per ICC doctrine. */
export interface TradePlan {
  direction: 'long' | 'short';
  entry: number;
  stopLoss: number;
  takeProfit1: number;
  takeProfit2: number;
  slDistancePct: number;
  tp1DistancePct: number;
  tp2DistancePct: number;
  rationaleSl: string;
}

export interface AssetBias {
  symbol: string;
  label: string;
  category: 'Metal' | 'Index' | 'Forex';
  price: number;
  change24h: number;
  bias: BiasDirection;
  score: number;
  confidence: number;
  tradeable: boolean;
  icc: ICCBreakdown;
  sparkData: number[];

  /** Optional 1H timeframe analysis. When present and both tradeable in the
   *  same direction, `confluence.aligned` is true — the A+ setup signal. */
  icc1H?: ICCBreakdown;
  bias1H?: BiasDirection;
  score1H?: number;
  confluence?: {
    aligned: boolean;
    direction: BiasDirection;
    reason: string;
  };

  /** One-sentence AI narrative generated by the cron. Empty if not yet
   *  generated or if the AI call fell back to the deterministic template. */
  narrative?: string;

  /** 4H-timeframe reference trade plan (entry/SL/TP). Present only when
   *  the 4H is in CONTINUATION + tradeable. */
  tradePlan?: TradePlan;

  /** 1H-timeframe reference trade plan. Present only when 1H is in
   *  CONTINUATION + tradeable. */
  tradePlan1H?: TradePlan;

  /** Present when the asset could not be analyzed this cycle. */
  error?: string;
}

export interface BiasSentiment {
  bullish: number;
  bearish: number;
  neutral: number;
  overall: 'RISK-ON' | 'RISK-OFF' | 'MIXED';
}

export interface BiasResponse {
  timestamp: string;
  timeframe: '4H';
  engine: 'icc-bias-v1';
  method: 'Indication-Correction-Continuation';
  weights: Record<string, number>;
  sentiment: BiasSentiment;
  assets: AssetBias[];
}

export interface AccuracyStats {
  symbol: string;
  interval: string;
  windowDays: number;
  totalCalls: number;
  directionalCalls: number;
  correct: number;
  incorrect: number;
  winRate: number;
  avgMovePct: number;
  lastCalculated: string;
}

export interface AccuracyBreakdown {
  byWindow: {
    '7d':  AccuracyStats;
    '30d': AccuracyStats;
    '90d': AccuracyStats;
    all:   AccuracyStats;
  };
}

export type EntryTrigger = 'continuation' | 'indication' | 'a_plus' | 'any_tradeable';

export interface BacktestParams {
  symbol: string;
  startingBalance: number;
  riskPercent: number;
  stopLossPercent: number;
  takeProfitR: number;
  timeStopHours: number;
  entryTrigger: EntryTrigger;
  maxConcurrentTrades?: number;
}

export interface SimTrade {
  openedAt: string;
  closedAt: string;
  direction: 'long' | 'short';
  entryPrice: number;
  exitPrice: number;
  stopLoss: number;
  takeProfit: number;
  exitReason: 'tp' | 'sl' | 'time';
  rMultiple: number;
  pnl: number;
  balance: number;
  score: number;
}

export interface BacktestResult {
  params: BacktestParams;
  totalTrades: number;
  wins: number;
  losses: number;
  winRate: number;
  avgR: number;
  expectancy: number;
  maxDrawdownPercent: number;
  sharpe: number | null;
  endingBalance: number;
  totalReturnPercent: number;
  equityCurve: Array<{ t: string; balance: number }>;
  trades: SimTrade[];
  meaningful: boolean;
  warning?: string;
}

// ── Alert quality tiers ───────────────────────────────────────
//
// Every phase-transition alert the engine fires is graded against 8
// criteria. The grade tells users at a glance whether a signal had all
// stars aligned (A+) or just partial confirmation (B/C), so they can
// size position / stand aside accordingly. Pure function — same logic
// runs in the cron (on persist) and in the UI (on render).

export type AlertQuality = 'A_PLUS' | 'A' | 'B' | 'C';

export interface AlertCriterion {
  key: string;
  label: string;
  met: boolean;
}

export interface AlertQualityResult {
  quality: AlertQuality;
  metCount: number;
  totalCount: number;
  criteria: AlertCriterion[];
  headlineWarning: string | null;   // short reason set when not A+
}

export function computeAlertQuality(
  asset: Pick<AssetBias, 'bias' | 'score' | 'confidence' | 'tradeable' | 'icc' | 'bias1H' | 'score1H' | 'icc1H' | 'confluence'>,
  interval: '4h' | '1h',
): AlertQualityResult {
  const icc = interval === '4h' ? asset.icc : (asset.icc1H ?? asset.icc);
  const phase = icc.phase.current;
  const otherBias = interval === '4h' ? asset.bias1H : asset.bias;

  const criteria: AlertCriterion[] = [
    {
      key: 'phase_continuation',
      label: 'Phase is Continuation (entry-ready)',
      met: phase === 'CONTINUATION',
    },
    {
      key: 'tradeable',
      label: 'Tradeable (non-NEUTRAL, clean trend)',
      met: asset.tradeable,
    },
    {
      key: 'other_tf_agree',
      label: `${interval === '4h' ? '1H' : '4H'} agrees on direction`,
      met: otherBias !== undefined && otherBias !== 'NEUTRAL' && otherBias === asset.bias,
    },
    {
      key: 'confluence_aligned',
      label: '4H + 1H both in Continuation (A+ confluence)',
      met: !!asset.confluence?.aligned,
    },
    {
      key: 'optimal_zone',
      label: 'Correction in optimal 38–62% zone',
      met: icc.correction.inOptimalZone === true,
    },
    {
      key: 'session_relevance',
      label: 'Active session suits this asset',
      met: icc.session.relevance === 'High' || icc.session.relevance === 'Medium',
    },
    {
      key: 'momentum',
      label: 'Recent candles show real momentum',
      met: icc.session.momentum === 'Strong' || icc.session.momentum === 'Moderate',
    },
    {
      key: 'confidence',
      label: 'Confidence ≥ 60%',
      met: asset.confidence >= 60,
    },
  ];

  const metCount = criteria.filter((c) => c.met).length;
  const totalCount = criteria.length;

  // Tier rules:
  //   A+ requires the three strongest signals: confluence + optimal zone
  //      + either high-relevance session or strong momentum
  //   A  = 6+ criteria met
  //   B  = 4-5 criteria met
  //   C  = <= 3 criteria met
  const hasConfluence = criteria[3]!.met;
  const hasOptimal    = criteria[4]!.met;
  const hasSessionContext = criteria[5]!.met || criteria[6]!.met;

  let quality: AlertQuality;
  if (hasConfluence && hasOptimal && hasSessionContext) quality = 'A_PLUS';
  else if (metCount >= 6) quality = 'A';
  else if (metCount >= 4) quality = 'B';
  else quality = 'C';

  // Headline warning for the UI chip
  let headlineWarning: string | null = null;
  if (quality !== 'A_PLUS') {
    const missed: string[] = [];
    if (!hasConfluence) missed.push('1H not confirming');
    if (!hasOptimal)    missed.push('not in optimal 38–62% zone');
    if (!hasSessionContext) missed.push('off-hours for this asset');
    if (phase !== 'CONTINUATION') missed.push('not yet Continuation');
    if (missed.length > 0) headlineWarning = missed.slice(0, 2).join(' · ');
  }

  return { quality, metCount, totalCount, criteria, headlineWarning };
}

// ── Alert history (inbox) ─────────────────────────────────────

export interface AlertHistoryItem {
  id: string;
  firedAtUnix: number;
  symbol: string;
  interval: '4h' | '1h' | '15min';
  phase: string;      // ICC phase kind OR ORB session+direction label
  previousPhase: string | null;
  bias: BiasDirection;
  quality: AlertQuality;
  metCount: number;
  totalCount: number;
  criteria: AlertCriterion[];
  tradePlan: TradePlan | null;
  narrative: string | null;
  readAtUnix: number | null;
  /** 'ICC' (bias transition) or 'ORB' (opening-range breakout). Drives
   *  the strategy badge and color scheme in the inbox UI. */
  strategy: 'ICC' | 'ORB';
}

export interface InboxResponse {
  unreadCount: number;
  alerts: AlertHistoryItem[];
}

/** OHLC point for the live chart feed. `time` is unix seconds. */
export interface ChartCandle {
  time: number;
  open: number;
  high: number;
  low: number;
  close: number;
}

/** Swing marker drawn on the live chart. */
export interface ChartSwing {
  time: number;
  type: 'high' | 'low';
  price: number;
}

/** Full payload returned by /v1/bias/candles/:symbol/:interval. */
export interface BiasCandlesPayload {
  symbol: string;
  interval: '4h' | '1h';
  candles: ChartCandle[];
  state: {
    bias: BiasDirection;
    score: number;
    phase: ICCPhaseKind;
    marketState: MarketStateKind;
    correctionDepth: number | null;
  };
  swings: ChartSwing[];
  indicationLevel: number | null;
  impulseRange: { high: number; low: number } | null;
  retracementLevels: {
    r25: number;
    r38: number;
    r50: number;
    r62: number;
    r79: number;
  } | null;
  tradePlan: TradePlan | null;
}

/** Historical snapshot served by /v1/bias/snapshot/:symbol/:unix. Used
 *  by the asset page's "alert replay" banner so a user who clicks a
 *  push/Telegram notification sees the exact state that fired the alert,
 *  not just the evolved live state. */
export interface BiasSnapshot {
  capturedAt: string;
  capturedUnix: number;
  interval: string;
  symbol: string;
  phase: ICCPhaseKind;
  bias: BiasDirection;
  price: number;
  score: number;
  asset: AssetBias | null;
}

export interface HighlightsResponse {
  asOf: string;
  aggregate: {
    totalCalls: number;
    directionalCalls: number;
    verified: number;
    correct: number;
    winRate: number;
    meaningful: boolean;
  };
  dailyTrend: Array<{ date: string; verified: number; correct: number; winRate: number }>;
  aPlusHistory: Array<{
    symbol: string;
    captured_at: string;
    bias: string;
    score: number;
    price: number;
  }>;
  perAsset: Array<{
    symbol: string;
    winRate: number;
    verified: number;
    totalCalls: number;
  }>;
}
