import { useState } from 'react';
const steps = [["10:00–11:00 UTC", "Mark the box", "Use the high and low of the four M15 candles opening at 10:00, 10:15, 10:30 and 10:45. Freeze the box at 11:00."], ["After 11:00 UTC", "Wait for a close", "Buy above the high. Sell below the low. A wick outside with a close inside is not confirmation."], ["Next M15 open", "Take the entry", "Measure the completed body. Below 100 pips: next M15 open. At 100+ pips: wait for at least a half-body retracement, then the next M15 open. No alignment, no trade."], ["80 / 160 / 240 pips", "Map the risk", "Keep an 80-pip stop and a chosen 160-pip (2R) or 240-pip (3R) target from the actual entry. Verify your broker’s gold pip convention."]];
export function RangeBreakoutGuide() {
 const [side, setSide] = useState<'buy' | 'sell'>('buy');
 const [delayed, setDelayed] = useState(false);
 return <section aria-label="TMPro Range Breakout visual guide" className="space-y-6">
  <div className="flex flex-wrap gap-3 text-sm text-slate-300"><span>Gold / XAUUSD</span><span>•</span><span>M15 only</span><span>•</span><span>UTC only</span></div>
  <ol className="grid gap-5 sm:grid-cols-2">
   {steps.map(([time, title, text], i) => <li key={title} className="border-l-2 border-neon-amber/50 pl-4"><p className="text-sm text-neon-amber">{i+1}. {time}</p><h3 className="mt-1 text-lg font-semibold text-white">{title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-300">{text}</p></li>)}
  </ol>
  <figure className="rounded-2xl border border-terminal-border p-3 sm:p-5">
   <div className="flex flex-wrap items-center justify-between gap-3 mb-4"><h3 className="text-lg text-white font-semibold">See the sequence</h3><div className="flex gap-2" aria-label="Example direction">{(['buy','sell'] as const).map(value => <button type="button" key={value} aria-pressed={side===value} onClick={() => setSide(value)} className={`min-h-11 rounded-lg border px-5 text-sm focus-visible:outline focus-visible:outline-2 focus-visible:outline-neon-cyan ${side===value ? 'border-neon-amber text-neon-amber bg-neon-amber/10' : 'border-terminal-border text-slate-300'}`}>{value==='buy' ? 'Buy example' : 'Sell example'}</button>)}</div></div>
   <div className="flex flex-wrap gap-2 mb-4">{[false,true].map(value => <button key={String(value)} type="button" aria-pressed={delayed===value} onClick={() => setDelayed(value)} className={`min-h-11 rounded-lg border px-4 text-sm focus-visible:outline focus-visible:outline-2 focus-visible:outline-neon-cyan ${delayed===value ? 'border-neon-amber text-neon-amber' : 'border-terminal-border text-slate-300'}`}>{value ? '100+ pip body: wait' : 'Under 100 pips: standard'}</button>)}</div>
   <div role="region" aria-label="Candlestick chart; scroll horizontally on small screens" tabIndex={0} className="overflow-x-auto rounded-xl focus-visible:outline focus-visible:outline-2 focus-visible:outline-neon-cyan"><img className="w-full min-w-[720px]" src={`/playbook/tmpro-range-${side}${delayed ? '-delayed' : ''}.svg`} alt={delayed ? `Synthetic ${side} example: a 120-pip breakout body, at least 60 pips of retracement to its midpoint, then next-open entry at 11:30 UTC.` : `Synthetic standard ${side} example: four UTC reference candles, a completed breakout with body under 100 pips, then next-open entry at 11:15 UTC.`}/></div><p className="mt-2 text-xs text-terminal-muted">Scroll the chart sideways on small screens. Green candles close up; red candles close down.</p>
   <figcaption className="mt-4 space-y-2 text-sm leading-relaxed text-slate-300">{delayed ? <><p><strong className="text-white">120-pip breakout body:</strong> no immediate entry. <strong className="text-white">60-pip retracement:</strong> midpoint reached during a later candle. <strong className="text-white">Next candle:</strong> entry at its open, only if the rules still align.</p><p>The midpoint touch qualifies the retracement; do not enter intrabar. Let that candle finish. No qualifying retracement means let the trade go.</p></> : <><p><strong className="text-white">Four candles in the shaded box:</strong> freeze the range. <strong className="text-white">Breakout candle:</strong> closes outside, with a 60-pip body. <strong className="text-white">Hollow marker:</strong> entry at its open.</p><p>This chart uses the close-outside interpretation of the initial breakout. The source leaves whole-body versus close-only unclear; declare your interpretation before testing.</p></>}<p>Constructed OHLC, not historical market data. The price scale uses 1 example pip = 0.10 price units, not a broker default. Adjacent opens match previous closes. The final marker shows only the entry open, with no future outcome. Times illustrate the earliest sequence, not a daily signal.</p></figcaption>
  </figure>
  <div className="rounded-xl border border-neon-amber/30 p-4 text-sm leading-relaxed text-slate-300"><h3 className="font-semibold text-white mb-2">100+ pip body: wait for half back</h3><p className="mb-3">Measure open to close, excluding wicks. The threshold includes exactly 100 pips. Midpoint = (open + close) / 2. Buy: price retraces down to the midpoint or lower. Sell: price retraces up to the midpoint or higher. Only a later candle can qualify; keep the original breakout midpoint fixed.</p><p className="mb-3">Example: 120-pip body → at least 60 pips back. If the breakout closes at 11:15 UTC and the 11:15–11:30 candle retraces enough, consider the 11:30 open. A second candle without the retracement is not an entry. Keep the 80/160/240-pip distances from the actual entry. If it does not fit, let it go.</p><h3 className="font-semibold text-white mb-2">Before testing</h3><p>Declare close-only versus whole-body initial breakout, verify the gold pip size and choose 2R or 3R before the batch. The course reads retracement as a midpoint touch, followed by entry at the next open after that candle completes. Break-even, partial exits, re-entry and daily cutoffs still need a declared test protocol.</p></div>
  <p className="text-xs leading-relaxed text-terminal-muted">Source: supplied MZITOH FX transcript, MFG 2.2. It ends at 30 minutes during the buy explanation. The 100+ pip / half-body retracement rule is supplied by the user. Diagrams and UTC teaching adaptation by TradeMetrics Pro. No source video is supplied for this course. Educational demo testing; no demonstrated edge or live orders.</p>
  <a href="/playbook/tmpro-range-breakout.pdf" download className="inline-flex min-h-11 items-center rounded-lg border border-terminal-border px-4 text-sm text-neon-cyan underline mr-3">Download two-page PDF</a>
  <a href="/playbook/tmpro-range-breakout.html" target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center rounded-lg border border-terminal-border px-4 text-sm text-neon-cyan underline">Open printable visual guide</a>
 </section>;
}
