//+------------------------------------------------------------------+
//| {{STRATEGY_NAME}} EA                                              |
//| Generated by TradeMetrics Pro Strategy Hub                        |
//+------------------------------------------------------------------+
#property copyright "TradeMetrics Pro"
#property version   "1.00"
#property strict

// -- Includes ────────────────────────────────────────────────────
#include <EdgeRelay_Common.mqh>
#include <EdgeRelay_Crypto.mqh>
#include <EdgeRelay_Http.mqh>
#include <EdgeRelay_Queue.mqh>
#include <EdgeRelay_JournalSync.mqh>
#include <EdgeRelay_JournalQueue.mqh>
#include <Trade\Trade.mqh>

// -- Strategy Parameters ─────────────────────────────────────────
input int              AsianStartHour  = {{ASIAN_START}};      // Asian Session Start (UTC)
input int              AsianEndHour    = {{ASIAN_END}};         // Asian Session End (UTC)
input int              BreakoutBuffer  = {{BREAKOUT_BUFFER}};   // Breakout Buffer (pips)
input ENUM_TIMEFRAMES  Timeframe       = {{TIMEFRAME}};         // Timeframe

// -- Trade Management ────────────────────────────────────────────
input double LotSize            = {{LOT_SIZE}};              // Lot Size
input int    StopLossPips        = {{SL_PIPS}};               // Stop Loss (pips)
input int    TakeProfitPips      = {{TP_PIPS}};               // Take Profit (pips)
input int    MaxSpreadPoints     = {{MAX_SPREAD}};            // Max Spread (points)
input int    MagicNumber         = {{MAGIC_NUMBER}};          // Magic Number

// -- Risk Management ─────────────────────────────────────────────
input double MaxDailyLossPercent   = {{MAX_DAILY_LOSS}};      // Max Daily Loss %
input int    ConsecutiveLossLimit  = {{CONSEC_LOSS_LIMIT}};   // Consecutive Loss Limit
input double BreakevenTriggerRR    = {{BE_TRIGGER_RR}};       // Breakeven at R:R
input double TrailingStopPips      = {{TRAILING_STOP}};       // Trailing Stop (pips)
input bool   UseSessionFilter      = {{USE_SESSION_FILTER}};  // Session Filter
input int    SessionStartHour      = {{SESSION_START}};       // Session Start (UTC)
input int    SessionEndHour        = {{SESSION_END}};         // Session End (UTC)

// -- TradeMetrics Integration ────────────────────────────────────
input string AccountID        = "{{ACCOUNT_ID}}";
input string API_Key          = "{{API_KEY}}";
input string API_Secret       = "";                           // API Secret (enter manually)
input string API_Endpoint     = "https://edgerelay-signal-ingestion.ghwmelite.workers.dev";
input string JournalEndpoint  = "https://edgerelay-journal-sync.ghwmelite.workers.dev";
input bool   EnableJournal    = true;                         // Enable Journal Sync

// -- Shared Integration Block ────────────────────────────────────
{{TRADEMETRICS_BLOCK}}

// -- Strategy Variables ──────────────────────────────────────────
double   g_rangeHigh       = 0.0;
double   g_rangeLow        = DBL_MAX;
bool     g_rangeReady      = false;
bool     g_tradedBuyToday  = false;
bool     g_tradedSellToday = false;
datetime g_lastRangeDate   = 0;
CTrade   g_trade;

//+------------------------------------------------------------------+
//| Expert initialization function                                    |
//+------------------------------------------------------------------+
int OnInit()
  {
   //--- Configure trade object
   g_trade.SetExpertMagicNumber(MagicNumber);
   g_trade.SetDeviationInPoints(10);
   g_trade.SetTypeFilling(ORDER_FILLING_IOC);

   //--- Initialize TradeMetrics integration
   return TM_OnInit();
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                  |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   TM_OnDeinit(reason);
  }

//+------------------------------------------------------------------+
//| Timer event handler                                               |
//+------------------------------------------------------------------+
void OnTimer()
  {
   TM_OnTimer();
  }

//+------------------------------------------------------------------+
//| Expert tick function                                              |
//+------------------------------------------------------------------+
void OnTick()
  {
   if(!TM_IsNewBar()) return;
   if(!TM_CanTrade()) return;

   //--- Get current UTC hour
   MqlDateTime dt;
   TimeToStruct(TimeGMT(), dt);
   int hour = dt.hour;

   //--- Daily reset: detect new day
   datetime today = StringToTime(TimeToString(TimeCurrent(), TIME_DATE));
   if(today != g_lastRangeDate)
     {
      g_lastRangeDate   = today;
      g_rangeHigh       = 0.0;
      g_rangeLow        = DBL_MAX;
      g_rangeReady      = false;
      g_tradedBuyToday  = false;
      g_tradedSellToday = false;
     }

   //--- During Asian session: track high/low
   bool inAsianSession = false;
   if(AsianStartHour < AsianEndHour)
      inAsianSession = (hour >= AsianStartHour && hour < AsianEndHour);
   else
      inAsianSession = (hour >= AsianStartHour || hour < AsianEndHour);

   if(inAsianSession)
     {
      double high = iHigh(_Symbol, Timeframe, 1);
      double low  = iLow(_Symbol, Timeframe, 1);
      if(high > g_rangeHigh) g_rangeHigh = high;
      if(low  < g_rangeLow)  g_rangeLow  = low;
      g_rangeReady = false;
      return;
     }

   //--- Mark range as ready once Asian session ends
   if(g_rangeHigh > 0.0 && g_rangeLow < DBL_MAX)
      g_rangeReady = true;

   if(!g_rangeReady) return;

   //--- Calculate pip value and buffer
   double pip    = _Point * ((_Digits == 3 || _Digits == 5) ? 10 : 1);
   double buffer = BreakoutBuffer * pip;
   double ask    = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid    = SymbolInfoDouble(_Symbol, SYMBOL_BID);

   //--- Use bar 1 (last closed) for breakout detection
   double close1 = iClose(_Symbol, Timeframe, 1);

   //--- BUY breakout: close above range high + buffer
   if(close1 > g_rangeHigh + buffer && !g_tradedBuyToday)
     {
      ClosePositionsByDirection(POSITION_TYPE_SELL);

      if(!HasPositionByDirection(POSITION_TYPE_BUY))
        {
         //--- SL at opposite range boundary (range low)
         double slDist = ask - g_rangeLow;
         double sl = NormalizeDouble(g_rangeLow, _Digits);
         double tp = (TakeProfitPips > 0) ? NormalizeDouble(ask + TakeProfitPips * pip, _Digits) : 0.0;

         //--- Override SL if user-defined SL is tighter
         if(StopLossPips > 0)
           {
            double userSl = NormalizeDouble(ask - StopLossPips * pip, _Digits);
            if(userSl > sl) sl = userSl;
           }

         if(g_trade.Buy(LotSize, _Symbol, ask, sl, tp, "AsianBreakout"))
           {
            ulong ticket = g_trade.ResultOrder();
            if(ticket > 0)
              {
               TM_OnTradeOpened(ticket, _Symbol, "buy", LotSize, ask, sl, tp);
               g_tradedBuyToday = true;
              }
           }
        }
     }

   //--- SELL breakout: close below range low - buffer
   if(close1 < g_rangeLow - buffer && !g_tradedSellToday)
     {
      ClosePositionsByDirection(POSITION_TYPE_BUY);

      if(!HasPositionByDirection(POSITION_TYPE_SELL))
        {
         //--- SL at opposite range boundary (range high)
         double sl = NormalizeDouble(g_rangeHigh, _Digits);
         double tp = (TakeProfitPips > 0) ? NormalizeDouble(bid - TakeProfitPips * pip, _Digits) : 0.0;

         //--- Override SL if user-defined SL is tighter
         if(StopLossPips > 0)
           {
            double userSl = NormalizeDouble(bid + StopLossPips * pip, _Digits);
            if(userSl < sl) sl = userSl;
           }

         if(g_trade.Sell(LotSize, _Symbol, bid, sl, tp, "AsianBreakout"))
           {
            ulong ticket = g_trade.ResultOrder();
            if(ticket > 0)
              {
               TM_OnTradeOpened(ticket, _Symbol, "sell", LotSize, bid, sl, tp);
               g_tradedSellToday = true;
              }
           }
        }
     }

   TM_ManageOpenTrades();
  }

//+------------------------------------------------------------------+
//| Check if a position exists in the given direction                 |
//+------------------------------------------------------------------+
bool HasPositionByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) == direction)
         return true;
     }
   return false;
  }

//+------------------------------------------------------------------+
//| Close all positions in the given direction                        |
//+------------------------------------------------------------------+
void ClosePositionsByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) != direction) continue;

      double profit = PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);

      if(g_trade.PositionClose(ticket))
         TM_OnTradeClosed(ticket, profit);
     }
  }
//+------------------------------------------------------------------+
