//+------------------------------------------------------------------+
//| {{STRATEGY_NAME}} EA                                              |
//| Generated by TradeMetrics Pro Strategy Hub                        |
//+------------------------------------------------------------------+
#property copyright "TradeMetrics Pro"
#property version   "1.00"
#property strict

// -- Includes ────────────────────────────────────────────────────
#include <EdgeRelay_Common.mqh>
#include <EdgeRelay_Crypto.mqh>
#include <EdgeRelay_Http.mqh>
#include <EdgeRelay_Queue.mqh>
#include <EdgeRelay_JournalSync.mqh>
#include <EdgeRelay_JournalQueue.mqh>
#include <Trade\Trade.mqh>

// -- Strategy Parameters ─────────────────────────────────────────
input int              BBPeriod         = {{BB_PERIOD}};         // Bollinger Period
input double           BBDeviation      = {{BB_DEVIATION}};      // Bollinger Deviation
input double           SqueezeThreshold = {{SQUEEZE_THRESHOLD}}; // Bandwidth Squeeze %
input int              RSIConfirmPeriod = {{RSI_CONFIRM}};       // RSI Confirmation Period
input ENUM_TIMEFRAMES  Timeframe        = {{TIMEFRAME}};         // Timeframe

// -- Trade Management ────────────────────────────────────────────
input double LotSize            = {{LOT_SIZE}};              // Lot Size
input int    StopLossPips        = {{SL_PIPS}};               // Stop Loss (pips)
input int    TakeProfitPips      = {{TP_PIPS}};               // Take Profit (pips)
input int    MaxSpreadPoints     = {{MAX_SPREAD}};            // Max Spread (points)
input int    MagicNumber         = {{MAGIC_NUMBER}};          // Magic Number

// -- Risk Management ─────────────────────────────────────────────
input double MaxDailyLossPercent   = {{MAX_DAILY_LOSS}};      // Max Daily Loss %
input int    ConsecutiveLossLimit  = {{CONSEC_LOSS_LIMIT}};   // Consecutive Loss Limit
input double BreakevenTriggerRR    = {{BE_TRIGGER_RR}};       // Breakeven at R:R
input double TrailingStopPips      = {{TRAILING_STOP}};       // Trailing Stop (pips)
input bool   UseSessionFilter      = {{USE_SESSION_FILTER}};  // Session Filter
input int    SessionStartHour      = {{SESSION_START}};       // Session Start (UTC)
input int    SessionEndHour        = {{SESSION_END}};         // Session End (UTC)

// -- TradeMetrics Integration ────────────────────────────────────
input string AccountID        = "{{ACCOUNT_ID}}";
input string API_Key          = "{{API_KEY}}";
input string API_Secret       = "";                           // API Secret (enter manually)
input string API_Endpoint     = "https://edgerelay-signal-ingestion.ghwmelite.workers.dev";
input string JournalEndpoint  = "https://edgerelay-journal-sync.ghwmelite.workers.dev";
input bool   EnableJournal    = true;                         // Enable Journal Sync

// -- Shared Integration Block ────────────────────────────────────
{{TRADEMETRICS_BLOCK}}

// -- Strategy Variables ──────────────────────────────────────────
int      g_bbHandle  = INVALID_HANDLE;
int      g_rsiHandle = INVALID_HANDLE;
bool     g_squeezeActive = false;
CTrade   g_trade;

//+------------------------------------------------------------------+
//| Expert initialization function                                    |
//+------------------------------------------------------------------+
int OnInit()
  {
   //--- Create indicator handles
   g_bbHandle  = iBands(_Symbol, Timeframe, BBPeriod, 0, BBDeviation, PRICE_CLOSE);
   g_rsiHandle = iRSI(_Symbol, Timeframe, RSIConfirmPeriod, PRICE_CLOSE);

   if(g_bbHandle == INVALID_HANDLE || g_rsiHandle == INVALID_HANDLE)
     {
      PrintFormat("[BollingerSqueeze] Failed to create indicator handles. Error: %d", GetLastError());
      return INIT_FAILED;
     }

   //--- Configure trade object
   g_trade.SetExpertMagicNumber(MagicNumber);
   g_trade.SetDeviationInPoints(10);
   g_trade.SetTypeFilling(ORDER_FILLING_IOC);

   //--- Initialize TradeMetrics integration
   return TM_OnInit();
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                  |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   //--- Release indicator handles
   if(g_bbHandle != INVALID_HANDLE)
      IndicatorRelease(g_bbHandle);
   if(g_rsiHandle != INVALID_HANDLE)
      IndicatorRelease(g_rsiHandle);

   TM_OnDeinit(reason);
  }

//+------------------------------------------------------------------+
//| Timer event handler                                               |
//+------------------------------------------------------------------+
void OnTimer()
  {
   TM_OnTimer();
  }

//+------------------------------------------------------------------+
//| Expert tick function                                              |
//+------------------------------------------------------------------+
void OnTick()
  {
   if(!TM_IsNewBar()) return;
   if(!TM_CanTrade()) return;

   //--- Read Bollinger Band values: middle(0), upper(1), lower(2)
   double bbMiddle[];
   double bbUpper[];
   double bbLower[];
   double rsi[];
   ArraySetAsSeries(bbMiddle, true);
   ArraySetAsSeries(bbUpper, true);
   ArraySetAsSeries(bbLower, true);
   ArraySetAsSeries(rsi, true);

   if(CopyBuffer(g_bbHandle, 0, 0, 3, bbMiddle) < 3) return;
   if(CopyBuffer(g_bbHandle, 1, 0, 3, bbUpper)  < 3) return;
   if(CopyBuffer(g_bbHandle, 2, 0, 3, bbLower)  < 3) return;
   if(CopyBuffer(g_rsiHandle, 0, 0, 3, rsi)     < 3) return;

   //--- Calculate bandwidth on bar 1 and bar 2
   double bw1 = 0.0;
   double bw2 = 0.0;
   if(bbMiddle[1] > 0.0) bw1 = (bbUpper[1] - bbLower[1]) / bbMiddle[1] * 100.0;
   if(bbMiddle[2] > 0.0) bw2 = (bbUpper[2] - bbLower[2]) / bbMiddle[2] * 100.0;

   //--- Detect squeeze: bandwidth below threshold
   if(bw1 < SqueezeThreshold)
      g_squeezeActive = true;

   //--- Check for expansion after squeeze
   if(!g_squeezeActive) { TM_ManageOpenTrades(); return; }
   if(bw1 <= bw2) { TM_ManageOpenTrades(); return; }  // Still contracting

   //--- Squeeze is expanding — check for entry signals
   double close1 = iClose(_Symbol, Timeframe, 1);
   double pip    = _Point * ((_Digits == 3 || _Digits == 5) ? 10 : 1);
   double ask    = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid    = SymbolInfoDouble(_Symbol, SYMBOL_BID);

   bool buySignal  = (close1 > bbUpper[1] && rsi[1] > 50.0);
   bool sellSignal = (close1 < bbLower[1] && rsi[1] < 50.0);

   //--- BUY signal
   if(buySignal)
     {
      ClosePositionsByDirection(POSITION_TYPE_SELL);

      if(!HasPositionByDirection(POSITION_TYPE_BUY))
        {
         double sl = (StopLossPips > 0)  ? NormalizeDouble(ask - StopLossPips * pip, _Digits)  : 0.0;
         double tp = (TakeProfitPips > 0) ? NormalizeDouble(ask + TakeProfitPips * pip, _Digits) : 0.0;

         if(g_trade.Buy(LotSize, _Symbol, ask, sl, tp, "BBSqueeze"))
           {
            ulong ticket = g_trade.ResultOrder();
            if(ticket > 0)
              {
               TM_OnTradeOpened(ticket, _Symbol, "buy", LotSize, ask, sl, tp);
               g_squeezeActive = false;
              }
           }
        }
     }

   //--- SELL signal
   if(sellSignal)
     {
      ClosePositionsByDirection(POSITION_TYPE_BUY);

      if(!HasPositionByDirection(POSITION_TYPE_SELL))
        {
         double sl = (StopLossPips > 0)  ? NormalizeDouble(bid + StopLossPips * pip, _Digits)  : 0.0;
         double tp = (TakeProfitPips > 0) ? NormalizeDouble(bid - TakeProfitPips * pip, _Digits) : 0.0;

         if(g_trade.Sell(LotSize, _Symbol, bid, sl, tp, "BBSqueeze"))
           {
            ulong ticket = g_trade.ResultOrder();
            if(ticket > 0)
              {
               TM_OnTradeOpened(ticket, _Symbol, "sell", LotSize, bid, sl, tp);
               g_squeezeActive = false;
              }
           }
        }
     }

   TM_ManageOpenTrades();
  }

//+------------------------------------------------------------------+
//| Check if a position exists in the given direction                 |
//+------------------------------------------------------------------+
bool HasPositionByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) == direction)
         return true;
     }
   return false;
  }

//+------------------------------------------------------------------+
//| Close all positions in the given direction                        |
//+------------------------------------------------------------------+
void ClosePositionsByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) != direction) continue;

      double profit = PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);

      if(g_trade.PositionClose(ticket))
         TM_OnTradeClosed(ticket, profit);
     }
  }
//+------------------------------------------------------------------+
