//+------------------------------------------------------------------+
//| {{STRATEGY_NAME}} EA                                              |
//| Generated by TradeMetrics Pro Strategy Hub                        |
//+------------------------------------------------------------------+
#property copyright "TradeMetrics Pro"
#property version   "1.00"
#property strict

// ── Includes ────────────────────────────────────────────────────
#include <EdgeRelay_Common.mqh>
#include <EdgeRelay_Crypto.mqh>
#include <EdgeRelay_Http.mqh>
#include <EdgeRelay_Queue.mqh>
#include <EdgeRelay_JournalSync.mqh>
#include <EdgeRelay_JournalQueue.mqh>
#include <Trade\Trade.mqh>

// ── Strategy Parameters ─────────────────────────────────────────
input int              LookbackBars        = {{LOOKBACK_BARS}};         // Range Lookback Bars
input int              BreakoutBufferPips   = {{BREAKOUT_BUFFER_PIPS}};  // Breakout Buffer (pips)
input int              ConfirmationCandles  = {{CONFIRMATION_CANDLES}};  // Confirmation Candles
input ENUM_TIMEFRAMES  Timeframe            = {{TIMEFRAME}};             // Timeframe

// ── ATR Range Validation ──────────────────────────────────────
input int              ATRRangePeriod      = {{ATR_RANGE_PERIOD}};      // ATR Period for Range Validation
input double           MinRangeATRMult     = {{MIN_RANGE_ATR_MULT}};    // Min Range as ATR Multiple (e.g. 0.5)
input double           MaxRangeATRMult     = {{MAX_RANGE_ATR_MULT}};    // Max Range as ATR Multiple (e.g. 3.0)

// ── Strategy Filters ──────────────────────────────────────────
input int    ADXPeriod        = {{ADX_PERIOD}};              // ADX Period (0=disabled)
input double ADXMinStrength   = {{ADX_MIN_STRENGTH}};        // Min ADX for Entry

// ── ATR Dynamic Stops ─────────────────────────────────────────
input bool   UseATRStops      = {{USE_ATR_STOPS}};           // Use ATR for SL/TP
input int    ATRStopPeriod    = {{ATR_STOP_PERIOD}};         // ATR Period for Stops
input double ATRSLMultiplier  = {{ATR_SL_MULT}};             // ATR SL Multiplier
input double ATRTPMultiplier  = {{ATR_TP_MULT}};             // ATR TP Multiplier

// ── Risk-Based Sizing ─────────────────────────────────────────
input double RiskPercent      = {{RISK_PERCENT}};            // Risk % of Balance (0=use fixed lot)

// ── Trade Management ────────────────────────────────────────────
input double LotSize            = {{LOT_SIZE}};              // Lot Size
input int    StopLossPips        = {{SL_PIPS}};               // Stop Loss (pips)
input int    TakeProfitPips      = {{TP_PIPS}};               // Take Profit (pips)
input int    MaxSpreadPoints     = {{MAX_SPREAD}};            // Max Spread (points)
input int    MagicNumber         = {{MAGIC_NUMBER}};          // Magic Number
input string MultiSymbols        = "{{MULTI_SYMBOLS}}";       // Multi-Asset Symbols (comma-separated, empty=chart symbol only)
input int    GMTOffset           = {{GMT_OFFSET}};            // Broker GMT Offset (99=auto-detect)

// ── Adaptive Mode ───────────────────────────────────────────────
input bool   UseAdaptiveMode       = {{USE_ADAPTIVE}};        // Adaptive Mode (auto-adjust to market)
input double TrendADXThreshold     = {{TREND_ADX_THRESH}};    // ADX Threshold for Trending
input double RangeADXThreshold     = {{RANGE_ADX_THRESH}};    // ADX Threshold for Ranging
input double VolatileATRMult       = {{VOLATILE_ATR_MULT}};   // ATR Spike Multiplier for Volatile

// ── Risk Management ─────────────────────────────────────────────
input double MaxDailyLossPercent   = {{MAX_DAILY_LOSS}};      // Max Daily Loss %
input int    ConsecutiveLossLimit  = {{CONSEC_LOSS_LIMIT}};   // Consecutive Loss Limit
input double BreakevenTriggerRR    = {{BE_TRIGGER_RR}};       // Breakeven at R:R
input double TrailingStopPips      = {{TRAILING_STOP}};       // Trailing Stop (pips)
input bool   UseSessionFilter      = {{USE_SESSION_FILTER}};  // Session Filter
input int    SessionStartHour      = {{SESSION_START}};       // Session Start (UTC)
input int    SessionEndHour        = {{SESSION_END}};         // Session End (UTC)

// ── Friday Close ────────────────────────────────────────────────
input bool   CloseFriday           = {{CLOSE_FRIDAY}};        // Close All Trades on Friday
input int    FridayCloseHour       = {{FRIDAY_CLOSE_HOUR}};    // Friday Close Hour (UTC)

// ── Prop Firm Limits ────────────────────────────────────────────
input double PropFirmDailyLimit   = {{PROP_DAILY_LIMIT}};     // Prop Firm Daily Loss Limit % (0=off)
input double PropFirmMaxDD        = {{PROP_MAX_DD}};           // Prop Firm Max Drawdown % (0=off)

// ── TradeMetrics Integration ────────────────────────────────────
input string AccountID        = "{{ACCOUNT_ID}}";
input string API_Key          = "{{API_KEY}}";
input string API_Secret       = "";                           // API Secret (enter manually)
input string API_Endpoint     = "https://edgerelay-signal-ingestion.ghwmelite.workers.dev";
input string JournalEndpoint  = "https://edgerelay-journal-sync.ghwmelite.workers.dev";
input bool   EnableJournal    = true;                         // Enable Journal Sync

// ── Shared Integration Block ────────────────────────────────────
{{TRADEMETRICS_BLOCK}}

// ── Multi-Asset Support ─────────────────────────────────────────
string g_symbols[];
int    g_symbolCount;
datetime g_lastBarTime[];

void InitSymbols()
{
   if(StringLen(MultiSymbols) == 0)
   {
      g_symbolCount = 1;
      ArrayResize(g_symbols, 1);
      g_symbols[0] = _Symbol;
   }
   else
   {
      string parts[];
      g_symbolCount = StringSplit(MultiSymbols, ',', parts);
      ArrayResize(g_symbols, g_symbolCount);
      for(int i = 0; i < g_symbolCount; i++)
      {
         StringTrimLeft(parts[i]);
         StringTrimRight(parts[i]);
         g_symbols[i] = parts[i];
         SymbolSelect(g_symbols[i], true);
      }
   }
   ArrayResize(g_lastBarTime, g_symbolCount);
   for(int i = 0; i < g_symbolCount; i++)
      g_lastBarTime[i] = 0;
}

int GetSymbolMagic(string symbol)
{
   int hash = MagicNumber;
   for(int i = 0; i < StringLen(symbol); i++)
      hash = ((hash << 5) - hash + StringGetCharacter(symbol, i)) & 0x7FFFFFFF;
   return hash;
}

double GetSymbolPip(string symbol)
{
   int digits = (int)SymbolInfoInteger(symbol, SYMBOL_DIGITS);
   double point = SymbolInfoDouble(symbol, SYMBOL_POINT);
   return point * ((digits == 3 || digits == 5) ? 10 : 1);
}

bool HasPositionFor(string symbol, ENUM_POSITION_TYPE direction, int magic)
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != magic) continue;
      if(PositionGetString(POSITION_SYMBOL) != symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) == direction)
         return true;
   }
   return false;
}

void ClosePositionsFor(string symbol, ENUM_POSITION_TYPE direction, int magic)
{
   CTrade closeTrade;
   closeTrade.SetExpertMagicNumber(magic);
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != magic) continue;
      if(PositionGetString(POSITION_SYMBOL) != symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) != direction) continue;
      double profit = PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);
      if(closeTrade.PositionClose(ticket))
         TM_OnTradeClosed(ticket, profit);
   }
}

bool IsNewBarForSymbol(int symIdx, string symbol)
{
   datetime currentBar = iTime(symbol, Timeframe, 0);
   if(currentBar == g_lastBarTime[symIdx]) return false;
   g_lastBarTime[symIdx] = currentBar;
   return true;
}

// ── Adaptive Mode ───────────────────────────────────────────────
enum ENUM_MARKET_REGIME { REGIME_TRENDING, REGIME_RANGING, REGIME_VOLATILE, REGIME_NORMAL };
ENUM_MARKET_REGIME g_regimes[];

// ── Strategy Variables ──────────────────────────────────────────
int      g_adxHandles[];
int      g_atrRangeHandles[];
int      g_atrStopHandles[];
CTrade   g_trade;

//+------------------------------------------------------------------+
//| Calculate lot size based on risk percentage                       |
//+------------------------------------------------------------------+
double CalculateLotSize(double slPips, string symbol, double symPip)
  {
   if(RiskPercent <= 0 || slPips <= 0) return LotSize;
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskAmount = balance * RiskPercent / 100.0;
   double tickValue = SymbolInfoDouble(symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize = SymbolInfoDouble(symbol, SYMBOL_TRADE_TICK_SIZE);
   if(tickValue <= 0 || tickSize <= 0) return LotSize;
   double lotSize = riskAmount / (slPips * symPip / tickSize * tickValue);
   double minLot = SymbolInfoDouble(symbol, SYMBOL_VOLUME_MIN);
   double maxLot = SymbolInfoDouble(symbol, SYMBOL_VOLUME_MAX);
   double lotStep = SymbolInfoDouble(symbol, SYMBOL_VOLUME_STEP);
   lotSize = MathMax(minLot, MathMin(maxLot, MathFloor(lotSize / lotStep) * lotStep));
   return lotSize;
  }

//+------------------------------------------------------------------+
//| Expert initialization function                                    |
//+------------------------------------------------------------------+
int OnInit()
  {
   InitSymbols();

   ArrayResize(g_adxHandles, g_symbolCount);
   ArrayResize(g_atrRangeHandles, g_symbolCount);
   ArrayResize(g_atrStopHandles, g_symbolCount);
   ArrayResize(g_regimes, g_symbolCount);

   for(int i = 0; i < g_symbolCount; i++)
     {
      g_adxHandles[i] = INVALID_HANDLE;
      g_atrRangeHandles[i] = INVALID_HANDLE;
      g_atrStopHandles[i] = INVALID_HANDLE;
      g_regimes[i] = REGIME_NORMAL;

      if(ADXPeriod > 0 || UseAdaptiveMode)
        {
         g_adxHandles[i] = iADX(g_symbols[i], Timeframe, (ADXPeriod > 0 ? ADXPeriod : 14));
         if(g_adxHandles[i] == INVALID_HANDLE)
           {
            PrintFormat("[BreakoutRetest] Failed to create ADX handle for %s. Error: %d", g_symbols[i], GetLastError());
            return INIT_FAILED;
           }
        }

      if(ATRRangePeriod > 0 || UseAdaptiveMode)
        {
         g_atrRangeHandles[i] = iATR(g_symbols[i], Timeframe, ATRRangePeriod);
         if(g_atrRangeHandles[i] == INVALID_HANDLE)
           {
            PrintFormat("[BreakoutRetest] Failed to create ATR range handle for %s. Error: %d", g_symbols[i], GetLastError());
            return INIT_FAILED;
           }
        }

      if(UseATRStops || UseAdaptiveMode)
        {
         if(ATRStopPeriod == ATRRangePeriod && g_atrRangeHandles[i] != INVALID_HANDLE)
            g_atrStopHandles[i] = g_atrRangeHandles[i];
         else
           {
            g_atrStopHandles[i] = iATR(g_symbols[i], Timeframe, ATRStopPeriod);
            if(g_atrStopHandles[i] == INVALID_HANDLE)
              {
               PrintFormat("[BreakoutRetest] Failed to create ATR stop handle for %s. Error: %d", g_symbols[i], GetLastError());
               return INIT_FAILED;
              }
           }
        }
     }

   g_trade.SetExpertMagicNumber(MagicNumber);
   g_trade.SetDeviationInPoints(10);
   g_trade.SetTypeFilling(ORDER_FILLING_IOC);

   return TM_OnInit();
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                  |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   for(int i = 0; i < g_symbolCount; i++)
     {
      if(g_adxHandles[i] != INVALID_HANDLE) IndicatorRelease(g_adxHandles[i]);
      if(g_atrRangeHandles[i] != INVALID_HANDLE) IndicatorRelease(g_atrRangeHandles[i]);
      if(g_atrStopHandles[i] != INVALID_HANDLE && g_atrStopHandles[i] != g_atrRangeHandles[i])
         IndicatorRelease(g_atrStopHandles[i]);
     }

   TM_OnDeinit(reason);
  }

//+------------------------------------------------------------------+
//| Timer event handler                                               |
//+------------------------------------------------------------------+
void OnTimer()
  {
   TM_OnTimer();
  }

//+------------------------------------------------------------------+
//| Expert tick function                                              |
//+------------------------------------------------------------------+
void OnTick()
  {
   if(!TM_CanTrade()) return;

   for(int si = 0; si < g_symbolCount; si++)
     {
      string sym = g_symbols[si];
      if(!IsNewBarForSymbol(si, sym)) continue;

      int magic = GetSymbolMagic(sym);
      double symPip = GetSymbolPip(sym);
      double symAsk = SymbolInfoDouble(sym, SYMBOL_ASK);
      double symBid = SymbolInfoDouble(sym, SYMBOL_BID);
      int symDigits = (int)SymbolInfoInteger(sym, SYMBOL_DIGITS);

      //--- Calculate range
      double highArr[];
      double lowArr[];
      ArraySetAsSeries(highArr, true);
      ArraySetAsSeries(lowArr, true);

      if(CopyHigh(sym, Timeframe, 1, LookbackBars, highArr) < LookbackBars) continue;
      if(CopyLow(sym, Timeframe, 1, LookbackBars, lowArr) < LookbackBars)   continue;

      double rangeHigh = highArr[0];
      double rangeLow  = lowArr[0];
      for(int i = 1; i < LookbackBars; i++)
        {
         if(highArr[i] > rangeHigh) rangeHigh = highArr[i];
         if(lowArr[i]  < rangeLow)  rangeLow  = lowArr[i];
        }

      double rangeSize = rangeHigh - rangeLow;

      //--- ATR range validation
      if(g_atrRangeHandles[si] != INVALID_HANDLE)
        {
         double atrRangeArr[];
         ArraySetAsSeries(atrRangeArr, true);
         if(CopyBuffer(g_atrRangeHandles[si], 0, 0, 2, atrRangeArr) >= 2)
           {
            double atrVal = atrRangeArr[1];
            if(atrVal > 0)
              {
               if(rangeSize < MinRangeATRMult * atrVal) continue;
               if(rangeSize > MaxRangeATRMult * atrVal) continue;
              }
           }
        }

      //--- Get close prices for confirmation
      double closeArr[];
      ArraySetAsSeries(closeArr, true);
      int needBars = ConfirmationCandles + 1;
      if(CopyClose(sym, Timeframe, 1, needBars, closeArr) < needBars) continue;

      double buffer = BreakoutBufferPips * symPip;

      int confirmBuyCount = 0;
      for(int i = 0; i < ConfirmationCandles; i++)
        { if(closeArr[i] > rangeHigh + buffer) confirmBuyCount++; else break; }

      int confirmSellCount = 0;
      for(int i = 0; i < ConfirmationCandles; i++)
        { if(closeArr[i] < rangeLow - buffer) confirmSellCount++; else break; }

      bool buySignal  = (confirmBuyCount >= ConfirmationCandles);
      bool sellSignal = (confirmSellCount >= ConfirmationCandles);

      //--- ADX confirmation
      if((buySignal || sellSignal) && ADXPeriod > 0 && g_adxHandles[si] != INVALID_HANDLE)
        {
         double adxVal[];
         ArraySetAsSeries(adxVal, true);
         if(CopyBuffer(g_adxHandles[si], 0, 0, 3, adxVal) >= 3)
           {
            if(adxVal[1] < ADXMinStrength || adxVal[1] < adxVal[2])
              { buySignal = false; sellSignal = false; }
           }
         else
           { buySignal = false; sellSignal = false; }
        }

      //--- Read ATR for dynamic stops
      double atrStopValue = 0.0;
      if(UseATRStops && g_atrStopHandles[si] != INVALID_HANDLE)
        {
         double atrStopArr[];
         ArraySetAsSeries(atrStopArr, true);
         if(CopyBuffer(g_atrStopHandles[si], 0, 0, 2, atrStopArr) >= 2)
            atrStopValue = atrStopArr[1];
        }


      //--- Detect market regime for adaptive mode
      double adaptiveSLMult  = 1.0;
      double adaptiveTPMult  = 1.0;
      double adaptiveLotMult = 1.0;

      if(UseAdaptiveMode)
        {
         double adxAdapt = 0.0;
         if(g_adxHandles[si] != INVALID_HANDLE)
           {
            double adxAdaptArr[];
            ArraySetAsSeries(adxAdaptArr, true);
            if(CopyBuffer(g_adxHandles[si], 0, 0, 2, adxAdaptArr) >= 2)
               adxAdapt = adxAdaptArr[1];
           }

         int adaptATRH = g_atrRangeHandles[si];
         if(adaptATRH != INVALID_HANDLE)
           {
            double adaptATR[];
            ArraySetAsSeries(adaptATR, true);
            if(CopyBuffer(adaptATRH, 0, 1, 20, adaptATR) >= 20)
              {
               double currentATR = adaptATR[0];
               double avgATR = 0;
               for(int ai = 1; ai < 20; ai++) avgATR += adaptATR[ai];
               avgATR /= 19.0;

               if(currentATR > avgATR * VolatileATRMult)
                  g_regimes[si] = REGIME_VOLATILE;
               else if(adxAdapt > TrendADXThreshold)
                  g_regimes[si] = REGIME_TRENDING;
               else if(adxAdapt < RangeADXThreshold)
                  g_regimes[si] = REGIME_RANGING;
               else
                  g_regimes[si] = REGIME_NORMAL;
              }
           }

         switch(g_regimes[si])
           {
            case REGIME_TRENDING:  adaptiveSLMult = 0.8; adaptiveTPMult = 1.5; adaptiveLotMult = 1.0; break;
            case REGIME_RANGING:   adaptiveSLMult = 1.2; adaptiveTPMult = 0.7; adaptiveLotMult = 0.8; break;
            case REGIME_VOLATILE:  adaptiveSLMult = 1.5; adaptiveTPMult = 1.3; adaptiveLotMult = 0.5; break;
            default: break;
           }
        }
      //--- BUY signal
      if(buySignal)
        {
         ClosePositionsFor(sym, POSITION_TYPE_SELL, magic);

         if(!HasPositionFor(sym, POSITION_TYPE_BUY, magic))
           {
            double slDist = 0.0;
            double tpDist = 0.0;

            if(UseATRStops && atrStopValue > 0)
              { slDist = atrStopValue * ATRSLMultiplier; tpDist = atrStopValue * ATRTPMultiplier; }
            else
              {
               double rangeSLDist = symAsk - rangeLow;
               double fixedSLDist = StopLossPips * symPip;
               if(StopLossPips > 0 && fixedSLDist < rangeSLDist)
                  slDist = fixedSLDist;
               else
                  slDist = rangeSLDist;
               tpDist = TakeProfitPips * symPip;
              }

            slDist *= adaptiveSLMult;
            tpDist *= adaptiveTPMult;

            double sl = (slDist > 0) ? NormalizeDouble(symAsk - slDist, symDigits) : 0.0;
            double tp = (tpDist > 0) ? NormalizeDouble(symAsk + tpDist, symDigits) : 0.0;

            double slPips = (slDist > 0) ? slDist / symPip : 0.0;
            double lot = CalculateLotSize(slPips, sym, symPip) * adaptiveLotMult;

            string comment = StringFormat("TM:%s|SIG:%s", "Breakout", "BUY_BREAK");

            g_trade.SetExpertMagicNumber(magic);
            if(g_trade.Buy(lot, sym, symAsk, sl, tp, comment))
              {
               ulong ticket = g_trade.ResultOrder();
               if(ticket > 0)
                  TM_OnTradeOpened(ticket, sym, "buy", lot, symAsk, sl, tp);
              }
           }
        }

      //--- SELL signal
      if(sellSignal)
        {
         ClosePositionsFor(sym, POSITION_TYPE_BUY, magic);

         if(!HasPositionFor(sym, POSITION_TYPE_SELL, magic))
           {
            double slDist = 0.0;
            double tpDist = 0.0;

            if(UseATRStops && atrStopValue > 0)
              { slDist = atrStopValue * ATRSLMultiplier; tpDist = atrStopValue * ATRTPMultiplier; }
            else
              {
               double rangeSLDist = rangeHigh - symBid;
               double fixedSLDist = StopLossPips * symPip;
               if(StopLossPips > 0 && fixedSLDist < rangeSLDist)
                  slDist = fixedSLDist;
               else
                  slDist = rangeSLDist;
               tpDist = TakeProfitPips * symPip;
              }

            slDist *= adaptiveSLMult;
            tpDist *= adaptiveTPMult;

            double sl = (slDist > 0) ? NormalizeDouble(symBid + slDist, symDigits) : 0.0;
            double tp = (tpDist > 0) ? NormalizeDouble(symBid - tpDist, symDigits) : 0.0;

            double slPips = (slDist > 0) ? slDist / symPip : 0.0;
            double lot = CalculateLotSize(slPips, sym, symPip) * adaptiveLotMult;

            string comment = StringFormat("TM:%s|SIG:%s", "Breakout", "SELL_BREAK");

            g_trade.SetExpertMagicNumber(magic);
            if(g_trade.Sell(lot, sym, symBid, sl, tp, comment))
              {
               ulong ticket = g_trade.ResultOrder();
               if(ticket > 0)
                  TM_OnTradeOpened(ticket, sym, "sell", lot, symBid, sl, tp);
              }
           }
        }
     }

   TM_ManageOpenTrades();
  }

//+------------------------------------------------------------------+
//| Check if a position exists in the given direction                 |
//+------------------------------------------------------------------+
bool HasPositionByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) == direction)
         return true;
     }
   return false;
  }

//+------------------------------------------------------------------+
//| Close all positions in the given direction                        |
//+------------------------------------------------------------------+
void ClosePositionsByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) != direction) continue;

      double profit = PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);

      if(g_trade.PositionClose(ticket))
         TM_OnTradeClosed(ticket, profit);
     }
  }
//+------------------------------------------------------------------+
