//+------------------------------------------------------------------+
//| {{STRATEGY_NAME}} EA                                              |
//| Generated by TradeMetrics Pro Strategy Hub                        |
//+------------------------------------------------------------------+
#property copyright "TradeMetrics Pro"
#property version   "1.00"
#property strict

// ── Includes ────────────────────────────────────────────────────
#include <EdgeRelay_Common.mqh>
#include <EdgeRelay_Crypto.mqh>
#include <EdgeRelay_Http.mqh>
#include <EdgeRelay_Queue.mqh>
#include <EdgeRelay_JournalSync.mqh>
#include <EdgeRelay_JournalQueue.mqh>
#include <Trade\Trade.mqh>

// ── Strategy Parameters ─────────────────────────────────────────
input int              LookbackBars        = {{LOOKBACK_BARS}};         // Range Lookback Bars
input int              BreakoutBufferPips   = {{BREAKOUT_BUFFER_PIPS}};  // Breakout Buffer (pips)
input int              ConfirmationCandles  = {{CONFIRMATION_CANDLES}};  // Confirmation Candles
input ENUM_TIMEFRAMES  Timeframe            = {{TIMEFRAME}};             // Timeframe

// ── Trade Management ────────────────────────────────────────────
input double LotSize            = {{LOT_SIZE}};              // Lot Size
input int    StopLossPips        = {{SL_PIPS}};               // Stop Loss (pips)
input int    TakeProfitPips      = {{TP_PIPS}};               // Take Profit (pips)
input int    MaxSpreadPoints     = {{MAX_SPREAD}};            // Max Spread (points)
input int    MagicNumber         = {{MAGIC_NUMBER}};          // Magic Number

// ── Risk Management ─────────────────────────────────────────────
input double MaxDailyLossPercent   = {{MAX_DAILY_LOSS}};      // Max Daily Loss %
input int    ConsecutiveLossLimit  = {{CONSEC_LOSS_LIMIT}};   // Consecutive Loss Limit
input double BreakevenTriggerRR    = {{BE_TRIGGER_RR}};       // Breakeven at R:R
input double TrailingStopPips      = {{TRAILING_STOP}};       // Trailing Stop (pips)
input bool   UseSessionFilter      = {{USE_SESSION_FILTER}};  // Session Filter
input int    SessionStartHour      = {{SESSION_START}};       // Session Start (UTC)
input int    SessionEndHour        = {{SESSION_END}};         // Session End (UTC)

// ── TradeMetrics Integration ────────────────────────────────────
input string AccountID        = "{{ACCOUNT_ID}}";
input string API_Key          = "{{API_KEY}}";
input string API_Secret       = "";                           // API Secret (enter manually)
input string API_Endpoint     = "https://edgerelay-signal-ingestion.ghwmelite.workers.dev";
input string JournalEndpoint  = "https://edgerelay-journal-sync.ghwmelite.workers.dev";
input bool   EnableJournal    = true;                         // Enable Journal Sync

// ── Shared Integration Block ────────────────────────────────────
{{TRADEMETRICS_BLOCK}}

// ── Strategy Variables ──────────────────────────────────────────
CTrade   g_trade;
double   g_rangeHigh = 0.0;
double   g_rangeLow  = 0.0;
int      g_confirmBuyCount  = 0;
int      g_confirmSellCount = 0;

//+------------------------------------------------------------------+
//| Expert initialization function                                    |
//+------------------------------------------------------------------+
int OnInit()
  {
   //--- Configure trade object
   g_trade.SetExpertMagicNumber(MagicNumber);
   g_trade.SetDeviationInPoints(10);
   g_trade.SetTypeFilling(ORDER_FILLING_IOC);

   //--- Initialize TradeMetrics integration
   return TM_OnInit();
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                  |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   TM_OnDeinit(reason);
  }

//+------------------------------------------------------------------+
//| Timer event handler                                               |
//+------------------------------------------------------------------+
void OnTimer()
  {
   TM_OnTimer();
  }

//+------------------------------------------------------------------+
//| Expert tick function                                              |
//+------------------------------------------------------------------+
void OnTick()
  {
   if(!TM_IsNewBar()) return;
   if(!TM_CanTrade()) return;

   //--- Calculate range: highest high and lowest low over LookbackBars
   double highArr[];
   double lowArr[];
   ArraySetAsSeries(highArr, true);
   ArraySetAsSeries(lowArr, true);

   if(CopyHigh(_Symbol, Timeframe, 1, LookbackBars, highArr) < LookbackBars) return;
   if(CopyLow(_Symbol, Timeframe, 1, LookbackBars, lowArr) < LookbackBars)   return;

   g_rangeHigh = highArr[0];
   g_rangeLow  = lowArr[0];
   for(int i = 1; i < LookbackBars; i++)
     {
      if(highArr[i] > g_rangeHigh) g_rangeHigh = highArr[i];
      if(lowArr[i]  < g_rangeLow)  g_rangeLow  = lowArr[i];
     }

   //--- Get last closed bar close price
   double closeArr[];
   ArraySetAsSeries(closeArr, true);
   int needBars = ConfirmationCandles + 1;
   if(CopyClose(_Symbol, Timeframe, 1, needBars, closeArr) < needBars) return;

   //--- Calculate pip value for SL/TP and buffer
   double pip = _Point * ((_Digits == 3 || _Digits == 5) ? 10 : 1);
   double buffer = BreakoutBufferPips * pip;

   //--- Count confirmation candles closing above range high (for BUY)
   g_confirmBuyCount = 0;
   for(int i = 0; i < ConfirmationCandles; i++)
     {
      if(closeArr[i] > g_rangeHigh + buffer)
         g_confirmBuyCount++;
      else
         break;
     }

   //--- Count confirmation candles closing below range low (for SELL)
   g_confirmSellCount = 0;
   for(int i = 0; i < ConfirmationCandles; i++)
     {
      if(closeArr[i] < g_rangeLow - buffer)
         g_confirmSellCount++;
      else
         break;
     }

   //--- Detect signals
   bool buySignal  = (g_confirmBuyCount >= ConfirmationCandles);
   bool sellSignal = (g_confirmSellCount >= ConfirmationCandles);

   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

   //--- BUY signal: breakout above range high confirmed
   if(buySignal)
     {
      //--- Close any existing SELL positions with our magic number
      ClosePositionsByDirection(POSITION_TYPE_SELL);

      //--- Only open if no existing BUY position
      if(!HasPositionByDirection(POSITION_TYPE_BUY))
        {
         //--- SL below range low, or use fixed SL if smaller
         double rangeSL = NormalizeDouble(ask - (ask - g_rangeLow), _Digits);
         double fixedSL = (StopLossPips > 0) ? NormalizeDouble(ask - StopLossPips * pip, _Digits) : 0.0;
         double sl = 0.0;
         if(StopLossPips > 0 && fixedSL > rangeSL)
            sl = fixedSL;
         else
            sl = rangeSL;

         double tp = (TakeProfitPips > 0) ? NormalizeDouble(ask + TakeProfitPips * pip, _Digits) : 0.0;

         if(g_trade.Buy(LotSize, _Symbol, ask, sl, tp, "BreakoutRetest"))
           {
            ulong ticket = g_trade.ResultOrder();
            if(ticket > 0)
               TM_OnTradeOpened(ticket, _Symbol, "buy", LotSize, ask, sl, tp);
           }
        }
     }

   //--- SELL signal: breakout below range low confirmed
   if(sellSignal)
     {
      //--- Close any existing BUY positions with our magic number
      ClosePositionsByDirection(POSITION_TYPE_BUY);

      //--- Only open if no existing SELL position
      if(!HasPositionByDirection(POSITION_TYPE_SELL))
        {
         //--- SL above range high, or use fixed SL if smaller
         double rangeSL = NormalizeDouble(bid + (g_rangeHigh - bid), _Digits);
         double fixedSL = (StopLossPips > 0) ? NormalizeDouble(bid + StopLossPips * pip, _Digits) : 0.0;
         double sl = 0.0;
         if(StopLossPips > 0 && fixedSL < rangeSL)
            sl = fixedSL;
         else
            sl = rangeSL;

         double tp = (TakeProfitPips > 0) ? NormalizeDouble(bid - TakeProfitPips * pip, _Digits) : 0.0;

         if(g_trade.Sell(LotSize, _Symbol, bid, sl, tp, "BreakoutRetest"))
           {
            ulong ticket = g_trade.ResultOrder();
            if(ticket > 0)
               TM_OnTradeOpened(ticket, _Symbol, "sell", LotSize, bid, sl, tp);
           }
        }
     }

   TM_ManageOpenTrades();
  }

//+------------------------------------------------------------------+
//| Check if a position exists in the given direction                 |
//+------------------------------------------------------------------+
bool HasPositionByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) == direction)
         return true;
     }
   return false;
  }

//+------------------------------------------------------------------+
//| Close all positions in the given direction                        |
//+------------------------------------------------------------------+
void ClosePositionsByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) != direction) continue;

      double profit = PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);

      if(g_trade.PositionClose(ticket))
         TM_OnTradeClosed(ticket, profit);
     }
  }
//+------------------------------------------------------------------+
