//+------------------------------------------------------------------+
//| {{STRATEGY_NAME}} EA                                              |
//| Generated by TradeMetrics Pro Strategy Hub                        |
//+------------------------------------------------------------------+
#property copyright "TradeMetrics Pro"
#property version   "1.00"
#property strict

// ── Includes ────────────────────────────────────────────────────
#include <EdgeRelay_Common.mqh>
#include <EdgeRelay_Crypto.mqh>
#include <EdgeRelay_Http.mqh>
#include <EdgeRelay_Queue.mqh>
#include <EdgeRelay_JournalSync.mqh>
#include <EdgeRelay_JournalQueue.mqh>
#include <Trade\Trade.mqh>

// ── Strategy Parameters ─────────────────────────────────────────
input int              GridSpacingPips  = {{GRID_SPACING}};     // Grid Spacing (pips)
input int              MaxGridLevels    = {{MAX_GRID_LEVELS}};  // Max Grid Levels
input double           LotMultiplier    = {{LOT_MULTIPLIER}};   // Lot Multiplier per Level
input double           TakeProfitGrid   = {{TP_GRID}};          // Grid TP (pips from avg)
input ENUM_TIMEFRAMES  Timeframe        = {{TIMEFRAME}};        // Timeframe

// ── Strategy Filters ──────────────────────────────────────────
input int    ADXPeriod        = {{ADX_PERIOD}};                 // ADX Period (0=disabled)
input double ADXMinStrength   = {{ADX_MIN_STRENGTH}};           // Max ADX for New Grid (skip if trend too strong)

// ── ATR Dynamic Stops ─────────────────────────────────────────
input bool   UseATRStops      = {{USE_ATR_STOPS}};              // Use ATR for per-level SL
input int    ATRStopPeriod    = {{ATR_STOP_PERIOD}};            // ATR Period for Stops
input double ATRSLMultiplier  = {{ATR_SL_MULT}};                // ATR SL Multiplier
input double ATRTPMultiplier  = {{ATR_TP_MULT}};                // ATR TP Multiplier (unused — grid manages TP)

// ── Risk-Based Sizing ─────────────────────────────────────────
input double RiskPercent      = {{RISK_PERCENT}};               // Risk % of Balance (0=use fixed lot)
input double MaxAccountRisk   = {{MAX_ACCOUNT_RISK}};           // Max Total Grid Risk % (close all if exceeded)

// ── Trade Management ────────────────────────────────────────────
input double LotSize            = {{LOT_SIZE}};              // Lot Size
input int    StopLossPips        = {{SL_PIPS}};               // Stop Loss (pips)
input int    TakeProfitPips      = {{TP_PIPS}};               // Take Profit (pips)
input int    MaxSpreadPoints     = {{MAX_SPREAD}};            // Max Spread (points)
input int    MagicNumber         = {{MAGIC_NUMBER}};          // Magic Number
input string MultiSymbols        = "{{MULTI_SYMBOLS}}";       // Multi-Asset Symbols (comma-separated, empty=chart symbol only)

// ── Risk Management ─────────────────────────────────────────────
input double MaxDailyLossPercent   = {{MAX_DAILY_LOSS}};      // Max Daily Loss %
input int    ConsecutiveLossLimit  = {{CONSEC_LOSS_LIMIT}};   // Consecutive Loss Limit
input double BreakevenTriggerRR    = {{BE_TRIGGER_RR}};       // Breakeven at R:R
input double TrailingStopPips      = {{TRAILING_STOP}};       // Trailing Stop (pips)
input bool   UseSessionFilter      = {{USE_SESSION_FILTER}};  // Session Filter
input int    SessionStartHour      = {{SESSION_START}};       // Session Start (UTC)
input int    SessionEndHour        = {{SESSION_END}};         // Session End (UTC)

// ── TradeMetrics Integration ────────────────────────────────────
input string AccountID        = "{{ACCOUNT_ID}}";
input string API_Key          = "{{API_KEY}}";
input string API_Secret       = "";                           // API Secret (enter manually)
input string API_Endpoint     = "https://edgerelay-signal-ingestion.ghwmelite.workers.dev";
input string JournalEndpoint  = "https://edgerelay-journal-sync.ghwmelite.workers.dev";
input bool   EnableJournal    = true;                         // Enable Journal Sync

// ── Shared Integration Block ────────────────────────────────────
{{TRADEMETRICS_BLOCK}}

// ── Multi-Asset Support ─────────────────────────────────────────
string g_symbols[];
int    g_symbolCount;
datetime g_lastBarTime[];

void InitSymbols()
{
   if(StringLen(MultiSymbols) == 0)
   { g_symbolCount = 1; ArrayResize(g_symbols, 1); g_symbols[0] = _Symbol; }
   else
   {
      string parts[];
      g_symbolCount = StringSplit(MultiSymbols, ',', parts);
      ArrayResize(g_symbols, g_symbolCount);
      for(int i = 0; i < g_symbolCount; i++)
      { StringTrimLeft(parts[i]); StringTrimRight(parts[i]); g_symbols[i] = parts[i]; SymbolSelect(g_symbols[i], true); }
   }
   ArrayResize(g_lastBarTime, g_symbolCount);
   for(int i = 0; i < g_symbolCount; i++) g_lastBarTime[i] = 0;
}

int GetSymbolMagic(string symbol)
{ int hash = MagicNumber; for(int i = 0; i < StringLen(symbol); i++) hash = ((hash << 5) - hash + StringGetCharacter(symbol, i)) & 0x7FFFFFFF; return hash; }

double GetSymbolPip(string symbol)
{ int digits = (int)SymbolInfoInteger(symbol, SYMBOL_DIGITS); double point = SymbolInfoDouble(symbol, SYMBOL_POINT); return point * ((digits == 3 || digits == 5) ? 10 : 1); }

bool HasPositionFor(string symbol, ENUM_POSITION_TYPE direction, int magic)
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   { ulong ticket = PositionGetTicket(i); if(ticket == 0) continue; if(PositionGetInteger(POSITION_MAGIC) != magic) continue;
     if(PositionGetString(POSITION_SYMBOL) != symbol) continue; if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) == direction) return true; }
   return false;
}

void ClosePositionsFor(string symbol, ENUM_POSITION_TYPE direction, int magic)
{
   CTrade closeTrade; closeTrade.SetExpertMagicNumber(magic);
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   { ulong ticket = PositionGetTicket(i); if(ticket == 0) continue; if(PositionGetInteger(POSITION_MAGIC) != magic) continue;
     if(PositionGetString(POSITION_SYMBOL) != symbol) continue; if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) != direction) continue;
     double profit = PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);
     if(closeTrade.PositionClose(ticket)) TM_OnTradeClosed(ticket, profit); }
}

bool IsNewBarForSymbol(int symIdx, string symbol)
{ datetime currentBar = iTime(symbol, Timeframe, 0); if(currentBar == g_lastBarTime[symIdx]) return false; g_lastBarTime[symIdx] = currentBar; return true; }

// ── Strategy Variables ──────────────────────────────────────────
int      g_emaHandles[];
int      g_adxHandles[];
int      g_atrHandles[];
int      g_gridDir[];
double   g_lastGridPrice[];
CTrade   g_trade;

//+------------------------------------------------------------------+
//| Calculate lot size based on risk percentage                       |
//+------------------------------------------------------------------+
double CalculateLotSize(double slPips, string symbol, double symPip)
  {
   if(RiskPercent <= 0 || slPips <= 0) return LotSize;
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskAmount = balance * RiskPercent / 100.0;
   double tickValue = SymbolInfoDouble(symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize = SymbolInfoDouble(symbol, SYMBOL_TRADE_TICK_SIZE);
   if(tickValue <= 0 || tickSize <= 0) return LotSize;
   double lotSize = riskAmount / (slPips * symPip / tickSize * tickValue);
   double minLot = SymbolInfoDouble(symbol, SYMBOL_VOLUME_MIN);
   double maxLot = SymbolInfoDouble(symbol, SYMBOL_VOLUME_MAX);
   double lotStep = SymbolInfoDouble(symbol, SYMBOL_VOLUME_STEP);
   lotSize = MathMax(minLot, MathMin(maxLot, MathFloor(lotSize / lotStep) * lotStep));
   return lotSize;
  }

int OnInit()
  {
   InitSymbols();
   ArrayResize(g_emaHandles, g_symbolCount); ArrayResize(g_adxHandles, g_symbolCount);
   ArrayResize(g_atrHandles, g_symbolCount); ArrayResize(g_gridDir, g_symbolCount);
   ArrayResize(g_lastGridPrice, g_symbolCount);

   for(int i = 0; i < g_symbolCount; i++)
     {
      g_adxHandles[i] = INVALID_HANDLE; g_atrHandles[i] = INVALID_HANDLE;
      g_gridDir[i] = 0; g_lastGridPrice[i] = 0.0;

      g_emaHandles[i] = iMA(g_symbols[i], Timeframe, 50, 0, MODE_EMA, PRICE_CLOSE);
      if(g_emaHandles[i] == INVALID_HANDLE)
        { PrintFormat("[GridRecovery] Failed EMA for %s. Error: %d", g_symbols[i], GetLastError()); return INIT_FAILED; }
      if(ADXPeriod > 0)
        { g_adxHandles[i] = iADX(g_symbols[i], Timeframe, ADXPeriod); if(g_adxHandles[i] == INVALID_HANDLE) { PrintFormat("[GridRecovery] Failed ADX for %s", g_symbols[i]); return INIT_FAILED; } }
      if(UseATRStops)
        { g_atrHandles[i] = iATR(g_symbols[i], Timeframe, ATRStopPeriod); if(g_atrHandles[i] == INVALID_HANDLE) { PrintFormat("[GridRecovery] Failed ATR for %s", g_symbols[i]); return INIT_FAILED; } }
     }

   g_trade.SetExpertMagicNumber(MagicNumber); g_trade.SetDeviationInPoints(10); g_trade.SetTypeFilling(ORDER_FILLING_IOC);
   return TM_OnInit();
  }

void OnDeinit(const int reason)
  {
   for(int i = 0; i < g_symbolCount; i++)
     {
      if(g_emaHandles[i] != INVALID_HANDLE) IndicatorRelease(g_emaHandles[i]);
      if(g_adxHandles[i] != INVALID_HANDLE) IndicatorRelease(g_adxHandles[i]);
      if(g_atrHandles[i] != INVALID_HANDLE) IndicatorRelease(g_atrHandles[i]);
     }
   TM_OnDeinit(reason);
  }

//+------------------------------------------------------------------+
//| Timer event handler                                               |
//+------------------------------------------------------------------+
void OnTimer()
  {
   TM_OnTimer();
  }

//+------------------------------------------------------------------+
//| Expert tick function                                              |
//+------------------------------------------------------------------+
void CloseAllGridPositionsFor(string symbol, int magic)
  {
   CTrade closeTrade; closeTrade.SetExpertMagicNumber(magic);
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i); if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != magic) continue;
      if(PositionGetString(POSITION_SYMBOL) != symbol) continue;
      double profit = PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);
      if(closeTrade.PositionClose(ticket)) TM_OnTradeClosed(ticket, profit);
     }
  }

void OnTick()
  {
   if(!TM_CanTrade()) return;

   for(int si = 0; si < g_symbolCount; si++)
     {
      string sym = g_symbols[si];
      if(!IsNewBarForSymbol(si, sym)) continue;

      int magic = GetSymbolMagic(sym);
      double symPip = GetSymbolPip(sym);
      double symAsk = SymbolInfoDouble(sym, SYMBOL_ASK);
      double symBid = SymbolInfoDouble(sym, SYMBOL_BID);
      int symDigits = (int)SymbolInfoInteger(sym, SYMBOL_DIGITS);

      //--- Count grid positions for this symbol+magic
      int gridCount = 0; double totalVolume = 0.0; double weightedPrice = 0.0; double totalFloatingPL = 0.0;
      ENUM_POSITION_TYPE gridType = POSITION_TYPE_BUY;

      for(int i = PositionsTotal() - 1; i >= 0; i--)
        {
         ulong ticket = PositionGetTicket(i); if(ticket == 0) continue;
         if(PositionGetInteger(POSITION_MAGIC) != magic) continue;
         if(PositionGetString(POSITION_SYMBOL) != sym) continue;
         double vol = PositionGetDouble(POSITION_VOLUME); double entry = PositionGetDouble(POSITION_PRICE_OPEN);
         gridType = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);
         weightedPrice += entry * vol; totalVolume += vol;
         totalFloatingPL += PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);
         gridCount++;
        }

      double avgEntry = (totalVolume > 0.0) ? weightedPrice / totalVolume : 0.0;

      //--- Max account risk stop
      if(gridCount > 0 && MaxAccountRisk > 0)
        {
         double balance = AccountInfoDouble(ACCOUNT_BALANCE);
         double riskPct = MathAbs(totalFloatingPL) / balance * 100.0;
         if(totalFloatingPL < 0 && riskPct >= MaxAccountRisk)
           { CloseAllGridPositionsFor(sym, magic); g_gridDir[si] = 0; g_lastGridPrice[si] = 0.0; continue; }
        }

      //--- Grid TP check
      if(gridCount > 0 && avgEntry > 0.0)
        {
         double tpDist = TakeProfitGrid * symPip;
         bool hitTP = false;
         if(gridType == POSITION_TYPE_BUY && symBid >= avgEntry + tpDist) hitTP = true;
         else if(gridType == POSITION_TYPE_SELL && symAsk <= avgEntry - tpDist) hitTP = true;
         if(hitTP) { CloseAllGridPositionsFor(sym, magic); g_gridDir[si] = 0; g_lastGridPrice[si] = 0.0; continue; }
        }

      double atrValue = 0.0;
      if(UseATRStops && g_atrHandles[si] != INVALID_HANDLE)
        { double atrArr[]; ArraySetAsSeries(atrArr, true); if(CopyBuffer(g_atrHandles[si], 0, 0, 2, atrArr) >= 2) atrValue = atrArr[1]; }

      g_trade.SetExpertMagicNumber(magic);

      //--- No positions: initial entry
      if(gridCount == 0)
        {
         double ema[]; ArraySetAsSeries(ema, true);
         if(CopyBuffer(g_emaHandles[si], 0, 0, 3, ema) < 3) continue;
         double close1 = iClose(sym, Timeframe, 1);

         if(ADXPeriod > 0 && g_adxHandles[si] != INVALID_HANDLE)
           {
            double adxVal[]; ArraySetAsSeries(adxVal, true);
            if(CopyBuffer(g_adxHandles[si], 0, 0, 2, adxVal) >= 2) { if(adxVal[1] > ADXMinStrength) continue; }
            else continue;
           }

         double slDist = 0.0;
         if(UseATRStops && atrValue > 0) slDist = atrValue * ATRSLMultiplier;
         else if(StopLossPips > 0) slDist = StopLossPips * symPip;
         double slPips = (slDist > 0) ? slDist / symPip : 0.0;
         double lot = CalculateLotSize(slPips, sym, symPip);

         if(close1 > ema[1])
           {
            double sl = (slDist > 0) ? NormalizeDouble(symAsk - slDist, symDigits) : 0.0;
            if(g_trade.Buy(lot, sym, symAsk, sl, 0.0, StringFormat("TM:%s|SIG:%s|LVL:%d", "Grid", "BUY_INIT", 1)))
              { ulong ticket = g_trade.ResultOrder(); if(ticket > 0) { TM_OnTradeOpened(ticket, sym, "buy", lot, symAsk, sl, 0.0); g_gridDir[si] = 1; g_lastGridPrice[si] = symAsk; } }
           }
         else
           {
            double sl = (slDist > 0) ? NormalizeDouble(symBid + slDist, symDigits) : 0.0;
            if(g_trade.Sell(lot, sym, symBid, sl, 0.0, StringFormat("TM:%s|SIG:%s|LVL:%d", "Grid", "SELL_INIT", 1)))
              { ulong ticket = g_trade.ResultOrder(); if(ticket > 0) { TM_OnTradeOpened(ticket, sym, "sell", lot, symBid, sl, 0.0); g_gridDir[si] = -1; g_lastGridPrice[si] = symBid; } }
           }
         continue;
        }

      if(gridCount >= MaxGridLevels) continue;

      //--- ADX trend filter for grid expansion
      if(ADXPeriod > 0 && g_adxHandles[si] != INVALID_HANDLE)
        {
         double adxVal[], plusDI[], minusDI[];
         ArraySetAsSeries(adxVal, true); ArraySetAsSeries(plusDI, true); ArraySetAsSeries(minusDI, true);
         if(CopyBuffer(g_adxHandles[si], 0, 0, 2, adxVal) >= 2 && CopyBuffer(g_adxHandles[si], 1, 0, 2, plusDI) >= 2 && CopyBuffer(g_adxHandles[si], 2, 0, 2, minusDI) >= 2)
           {
            bool strongAgainst = false;
            if(g_gridDir[si] == 1 && adxVal[1] > ADXMinStrength && minusDI[1] > plusDI[1]) strongAgainst = true;
            if(g_gridDir[si] == -1 && adxVal[1] > ADXMinStrength && plusDI[1] > minusDI[1]) strongAgainst = true;
            if(strongAgainst) continue;
           }
        }

      double gridDist = GridSpacingPips * symPip;
      double nextLot = LotSize;
      for(int lvl = 1; lvl < gridCount; lvl++) nextLot *= LotMultiplier;

      double slDist = 0.0;
      if(UseATRStops && atrValue > 0) slDist = atrValue * ATRSLMultiplier;
      else if(StopLossPips > 0) slDist = StopLossPips * symPip;
      double slPips = (slDist > 0) ? slDist / symPip : 0.0;
      double lot = CalculateLotSize(slPips, sym, symPip);
      if(lot <= 0) lot = nextLot;

      double minLot = SymbolInfoDouble(sym, SYMBOL_VOLUME_MIN);
      double maxLot = SymbolInfoDouble(sym, SYMBOL_VOLUME_MAX);
      double lotStep = SymbolInfoDouble(sym, SYMBOL_VOLUME_STEP);
      double recoveryLot = nextLot;
      if(RiskPercent > 0 && slPips > 0)
        { recoveryLot = lot; for(int lvl = 1; lvl < gridCount; lvl++) recoveryLot *= LotMultiplier;
          recoveryLot = MathMax(minLot, MathMin(maxLot, MathFloor(recoveryLot / lotStep) * lotStep)); }
      else
        recoveryLot = MathMax(minLot, MathMin(maxLot, MathFloor(nextLot / lotStep) * lotStep));

      if(g_gridDir[si] == 1 && g_lastGridPrice[si] > 0.0 && symAsk <= g_lastGridPrice[si] - gridDist)
        {
         double sl = (slDist > 0) ? NormalizeDouble(symAsk - slDist, symDigits) : 0.0;
         if(g_trade.Buy(recoveryLot, sym, symAsk, sl, 0.0, StringFormat("TM:%s|SIG:%s|LVL:%d", "Grid", "BUY_RECOV", gridCount + 1)))
           { ulong ticket = g_trade.ResultOrder(); if(ticket > 0) { TM_OnTradeOpened(ticket, sym, "buy", recoveryLot, symAsk, sl, 0.0); g_lastGridPrice[si] = symAsk; } }
        }

      if(g_gridDir[si] == -1 && g_lastGridPrice[si] > 0.0 && symBid >= g_lastGridPrice[si] + gridDist)
        {
         double sl = (slDist > 0) ? NormalizeDouble(symBid + slDist, symDigits) : 0.0;
         if(g_trade.Sell(recoveryLot, sym, symBid, sl, 0.0, StringFormat("TM:%s|SIG:%s|LVL:%d", "Grid", "SELL_RECOV", gridCount + 1)))
           { ulong ticket = g_trade.ResultOrder(); if(ticket > 0) { TM_OnTradeOpened(ticket, sym, "sell", recoveryLot, symBid, sl, 0.0); g_lastGridPrice[si] = symBid; } }
        }
     }

   TM_ManageOpenTrades();
  }

//+------------------------------------------------------------------+
//| Close all grid positions with our magic number (backward compat)  |
//+------------------------------------------------------------------+
void CloseAllGridPositions()
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i); if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      double profit = PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);
      if(g_trade.PositionClose(ticket)) TM_OnTradeClosed(ticket, profit);
     }
  }

//+------------------------------------------------------------------+
//| Check if a position exists in the given direction                 |
//+------------------------------------------------------------------+
bool HasPositionByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) == direction)
         return true;
     }
   return false;
  }

//+------------------------------------------------------------------+
//| Close all positions in the given direction                        |
//+------------------------------------------------------------------+
void ClosePositionsByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) != direction) continue;

      double profit = PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);

      if(g_trade.PositionClose(ticket))
         TM_OnTradeClosed(ticket, profit);
     }
  }
//+------------------------------------------------------------------+
