//+------------------------------------------------------------------+
//| {{STRATEGY_NAME}} EA                                              |
//| Generated by TradeMetrics Pro Strategy Hub                        |
//+------------------------------------------------------------------+
#property copyright "TradeMetrics Pro"
#property version   "1.00"
#property strict

// ── Includes ────────────────────────────────────────────────────
#include <EdgeRelay_Common.mqh>
#include <EdgeRelay_Crypto.mqh>
#include <EdgeRelay_Http.mqh>
#include <EdgeRelay_Queue.mqh>
#include <EdgeRelay_JournalSync.mqh>
#include <EdgeRelay_JournalQueue.mqh>
#include <Trade\Trade.mqh>

// ── Strategy Parameters ─────────────────────────────────────────
input int              GridSpacingPips  = {{GRID_SPACING}};     // Grid Spacing (pips)
input int              MaxGridLevels    = {{MAX_GRID_LEVELS}};  // Max Grid Levels
input double           LotMultiplier    = {{LOT_MULTIPLIER}};   // Lot Multiplier per Level
input double           TakeProfitGrid   = {{TP_GRID}};          // Grid TP (pips from avg)
input ENUM_TIMEFRAMES  Timeframe        = {{TIMEFRAME}};        // Timeframe

// ── Strategy Filters ──────────────────────────────────────────
input int    ADXPeriod        = {{ADX_PERIOD}};                 // ADX Period (0=disabled)
input double ADXMinStrength   = {{ADX_MIN_STRENGTH}};           // Max ADX for New Grid (skip if trend too strong)

// ── ATR Dynamic Stops ─────────────────────────────────────────
input bool   UseATRStops      = {{USE_ATR_STOPS}};              // Use ATR for per-level SL
input int    ATRStopPeriod    = {{ATR_STOP_PERIOD}};            // ATR Period for Stops
input double ATRSLMultiplier  = {{ATR_SL_MULT}};                // ATR SL Multiplier
input double ATRTPMultiplier  = {{ATR_TP_MULT}};                // ATR TP Multiplier (unused — grid manages TP)

// ── Risk-Based Sizing ─────────────────────────────────────────
input double RiskPercent      = {{RISK_PERCENT}};               // Risk % of Balance (0=use fixed lot)
input double MaxAccountRisk   = {{MAX_ACCOUNT_RISK}};           // Max Total Grid Risk % (close all if exceeded)

// ── Trade Management ────────────────────────────────────────────
input double LotSize            = {{LOT_SIZE}};              // Lot Size
input int    StopLossPips        = {{SL_PIPS}};               // Stop Loss (pips)
input int    TakeProfitPips      = {{TP_PIPS}};               // Take Profit (pips)
input int    MaxSpreadPoints     = {{MAX_SPREAD}};            // Max Spread (points)
input int    MagicNumber         = {{MAGIC_NUMBER}};          // Magic Number

// ── Risk Management ─────────────────────────────────────────────
input double MaxDailyLossPercent   = {{MAX_DAILY_LOSS}};      // Max Daily Loss %
input int    ConsecutiveLossLimit  = {{CONSEC_LOSS_LIMIT}};   // Consecutive Loss Limit
input double BreakevenTriggerRR    = {{BE_TRIGGER_RR}};       // Breakeven at R:R
input double TrailingStopPips      = {{TRAILING_STOP}};       // Trailing Stop (pips)
input bool   UseSessionFilter      = {{USE_SESSION_FILTER}};  // Session Filter
input int    SessionStartHour      = {{SESSION_START}};       // Session Start (UTC)
input int    SessionEndHour        = {{SESSION_END}};         // Session End (UTC)

// ── TradeMetrics Integration ────────────────────────────────────
input string AccountID        = "{{ACCOUNT_ID}}";
input string API_Key          = "{{API_KEY}}";
input string API_Secret       = "";                           // API Secret (enter manually)
input string API_Endpoint     = "https://edgerelay-signal-ingestion.ghwmelite.workers.dev";
input string JournalEndpoint  = "https://edgerelay-journal-sync.ghwmelite.workers.dev";
input bool   EnableJournal    = true;                         // Enable Journal Sync

// ── Shared Integration Block ────────────────────────────────────
{{TRADEMETRICS_BLOCK}}

// ── Strategy Variables ──────────────────────────────────────────
int      g_emaHandle    = INVALID_HANDLE;
int      g_adxHandle    = INVALID_HANDLE;
int      g_atrHandle    = INVALID_HANDLE;
int      g_gridDir      = 0;    // 1 = BUY grid, -1 = SELL grid, 0 = none
double   g_lastGridPrice = 0.0;
CTrade   g_trade;

//+------------------------------------------------------------------+
//| Calculate lot size based on risk percentage                       |
//+------------------------------------------------------------------+
double CalculateLotSize(double slPips)
  {
   if(RiskPercent <= 0 || slPips <= 0) return LotSize;
   double pip = _Point * ((_Digits == 3 || _Digits == 5) ? 10 : 1);
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskAmount = balance * RiskPercent / 100.0;
   double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   if(tickValue <= 0 || tickSize <= 0) return LotSize;
   double lotSize = riskAmount / (slPips * pip / tickSize * tickValue);
   double minLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   lotSize = MathMax(minLot, MathMin(maxLot, MathFloor(lotSize / lotStep) * lotStep));
   return lotSize;
  }

//+------------------------------------------------------------------+
//| Expert initialization function                                    |
//+------------------------------------------------------------------+
int OnInit()
  {
   //--- Create EMA handle for initial direction
   g_emaHandle = iMA(_Symbol, Timeframe, 50, 0, MODE_EMA, PRICE_CLOSE);

   if(g_emaHandle == INVALID_HANDLE)
     {
      PrintFormat("[GridRecovery] Failed to create EMA handle. Error: %d", GetLastError());
      return INIT_FAILED;
     }

   //--- ADX filter handle (high ADX = strong trend = don't start new grid against it)
   if(ADXPeriod > 0)
     {
      g_adxHandle = iADX(_Symbol, Timeframe, ADXPeriod);
      if(g_adxHandle == INVALID_HANDLE)
        {
         PrintFormat("[GridRecovery] Failed to create ADX handle. Error: %d", GetLastError());
         return INIT_FAILED;
        }
     }

   //--- ATR handle for dynamic per-level SL
   if(UseATRStops)
     {
      g_atrHandle = iATR(_Symbol, Timeframe, ATRStopPeriod);
      if(g_atrHandle == INVALID_HANDLE)
        {
         PrintFormat("[GridRecovery] Failed to create ATR handle. Error: %d", GetLastError());
         return INIT_FAILED;
        }
     }

   //--- Configure trade object
   g_trade.SetExpertMagicNumber(MagicNumber);
   g_trade.SetDeviationInPoints(10);
   g_trade.SetTypeFilling(ORDER_FILLING_IOC);

   //--- Initialize TradeMetrics integration
   return TM_OnInit();
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                  |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   //--- Release indicator handles
   if(g_emaHandle != INVALID_HANDLE)
      IndicatorRelease(g_emaHandle);
   if(g_adxHandle != INVALID_HANDLE)
      IndicatorRelease(g_adxHandle);
   if(g_atrHandle != INVALID_HANDLE)
      IndicatorRelease(g_atrHandle);

   TM_OnDeinit(reason);
  }

//+------------------------------------------------------------------+
//| Timer event handler                                               |
//+------------------------------------------------------------------+
void OnTimer()
  {
   TM_OnTimer();
  }

//+------------------------------------------------------------------+
//| Expert tick function                                              |
//+------------------------------------------------------------------+
void OnTick()
  {
   if(!TM_IsNewBar()) return;
   if(!TM_CanTrade()) return;

   double pip = _Point * ((_Digits == 3 || _Digits == 5) ? 10 : 1);
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

   //--- Count existing grid positions and calculate average entry + total floating P/L
   int    gridCount = 0;
   double totalVolume = 0.0;
   double weightedPrice = 0.0;
   double totalFloatingPL = 0.0;
   ENUM_POSITION_TYPE gridType = POSITION_TYPE_BUY;

   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;

      double vol   = PositionGetDouble(POSITION_VOLUME);
      double entry = PositionGetDouble(POSITION_PRICE_OPEN);
      gridType = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);

      weightedPrice += entry * vol;
      totalVolume   += vol;
      totalFloatingPL += PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);
      gridCount++;
     }

   double avgEntry = 0.0;
   if(totalVolume > 0.0)
      avgEntry = weightedPrice / totalVolume;

   //--- Max account risk % stop: close all grid if floating loss exceeds threshold
   if(gridCount > 0 && MaxAccountRisk > 0)
     {
      double balance = AccountInfoDouble(ACCOUNT_BALANCE);
      double riskPct = MathAbs(totalFloatingPL) / balance * 100.0;
      if(totalFloatingPL < 0 && riskPct >= MaxAccountRisk)
        {
         PrintFormat("[GridRecovery] Max account risk %.1f%% reached (%.1f%%). Closing all grid positions.", MaxAccountRisk, riskPct);
         CloseAllGridPositions();
         g_gridDir = 0;
         g_lastGridPrice = 0.0;
         TM_ManageOpenTrades();
         return;
        }
     }

   //--- Check if grid TP is reached: close all positions
   if(gridCount > 0 && avgEntry > 0.0)
     {
      double tpDist = TakeProfitGrid * pip;
      bool hitTP = false;

      if(gridType == POSITION_TYPE_BUY && bid >= avgEntry + tpDist)
         hitTP = true;
      else if(gridType == POSITION_TYPE_SELL && ask <= avgEntry - tpDist)
         hitTP = true;

      if(hitTP)
        {
         CloseAllGridPositions();
         g_gridDir = 0;
         g_lastGridPrice = 0.0;
         TM_ManageOpenTrades();
         return;
        }
     }

   //--- Read ATR for dynamic stops if enabled
   double atrValue = 0.0;
   if(UseATRStops && g_atrHandle != INVALID_HANDLE)
     {
      double atrArr[];
      ArraySetAsSeries(atrArr, true);
      if(CopyBuffer(g_atrHandle, 0, 0, 2, atrArr) >= 2)
         atrValue = atrArr[1];
     }

   //--- No positions: determine initial direction from EMA
   if(gridCount == 0)
     {
      double ema[];
      ArraySetAsSeries(ema, true);
      if(CopyBuffer(g_emaHandle, 0, 0, 3, ema) < 3) return;

      double close1 = iClose(_Symbol, Timeframe, 1);

      //--- ADX filter: don't start a new grid if trend is too strong (likely to continue against grid)
      if(ADXPeriod > 0)
        {
         double adxVal[];
         ArraySetAsSeries(adxVal, true);
         if(CopyBuffer(g_adxHandle, 0, 0, 2, adxVal) >= 2)
           {
            if(adxVal[1] > ADXMinStrength)
              {
               TM_ManageOpenTrades();
               return;  // Strong trend — skip new grid
              }
           }
         else
           {
            TM_ManageOpenTrades();
            return;
           }
        }

      //--- Calculate SL distance
      double slDist = 0.0;
      if(UseATRStops && atrValue > 0)
         slDist = atrValue * ATRSLMultiplier;
      else if(StopLossPips > 0)
         slDist = StopLossPips * pip;

      double slPips = (slDist > 0) ? slDist / pip : 0.0;
      double lot = CalculateLotSize(slPips);

      if(close1 > ema[1])
        {
         //--- BUY initial entry
         double sl = (slDist > 0) ? NormalizeDouble(ask - slDist, _Digits) : 0.0;
         double tp = 0.0;  // Grid manages TP

         string comment = StringFormat("TM:%s|SIG:%s|LVL:%d", "Grid", "BUY_INIT", 1);

         if(g_trade.Buy(lot, _Symbol, ask, sl, tp, comment))
           {
            ulong ticket = g_trade.ResultOrder();
            if(ticket > 0)
              {
               TM_OnTradeOpened(ticket, _Symbol, "buy", lot, ask, sl, tp);
               g_gridDir = 1;
               g_lastGridPrice = ask;
              }
           }
        }
      else
        {
         //--- SELL initial entry
         double sl = (slDist > 0) ? NormalizeDouble(bid + slDist, _Digits) : 0.0;
         double tp = 0.0;

         string comment = StringFormat("TM:%s|SIG:%s|LVL:%d", "Grid", "SELL_INIT", 1);

         if(g_trade.Sell(lot, _Symbol, bid, sl, tp, comment))
           {
            ulong ticket = g_trade.ResultOrder();
            if(ticket > 0)
              {
               TM_OnTradeOpened(ticket, _Symbol, "sell", lot, bid, sl, tp);
               g_gridDir = -1;
               g_lastGridPrice = bid;
              }
           }
        }

      TM_ManageOpenTrades();
      return;
     }

   //--- Grid is active: check if we need to add a new level
   if(gridCount >= MaxGridLevels)
     {
      TM_ManageOpenTrades();
      return;
     }

   //--- ADX trend filter for grid expansion: don't add levels against a strong trend
   if(ADXPeriod > 0)
     {
      double adxVal[];
      double plusDI[];
      double minusDI[];
      ArraySetAsSeries(adxVal, true);
      ArraySetAsSeries(plusDI, true);
      ArraySetAsSeries(minusDI, true);

      if(CopyBuffer(g_adxHandle, 0, 0, 2, adxVal)  >= 2 &&
         CopyBuffer(g_adxHandle, 1, 0, 2, plusDI)   >= 2 &&
         CopyBuffer(g_adxHandle, 2, 0, 2, minusDI)  >= 2)
        {
         //--- Strong trend against our grid direction? Stop adding levels
         bool strongTrendAgainst = false;
         if(g_gridDir == 1 && adxVal[1] > ADXMinStrength && minusDI[1] > plusDI[1])
            strongTrendAgainst = true;  // Strong bearish trend, but we have BUY grid
         if(g_gridDir == -1 && adxVal[1] > ADXMinStrength && plusDI[1] > minusDI[1])
            strongTrendAgainst = true;  // Strong bullish trend, but we have SELL grid

         if(strongTrendAgainst)
           {
            TM_ManageOpenTrades();
            return;
           }
        }
     }

   double gridDist = GridSpacingPips * pip;
   double nextLot  = LotSize;
   for(int lvl = 1; lvl < gridCount; lvl++)
      nextLot *= LotMultiplier;

   //--- Calculate SL for new grid level
   double slDist = 0.0;
   if(UseATRStops && atrValue > 0)
      slDist = atrValue * ATRSLMultiplier;
   else if(StopLossPips > 0)
      slDist = StopLossPips * pip;

   double slPips = (slDist > 0) ? slDist / pip : 0.0;
   double lot = CalculateLotSize(slPips);
   if(lot <= 0) lot = nextLot;

   //--- Apply multiplier for recovery levels
   double minLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   double recoveryLot = nextLot;
   if(RiskPercent > 0 && slPips > 0)
     {
      //--- Scale the risk-based lot by the multiplier ratio
      recoveryLot = lot;
      for(int lvl = 1; lvl < gridCount; lvl++)
         recoveryLot *= LotMultiplier;
      recoveryLot = MathMax(minLot, MathMin(maxLot, MathFloor(recoveryLot / lotStep) * lotStep));
     }
   else
      recoveryLot = MathMax(minLot, MathMin(maxLot, MathFloor(nextLot / lotStep) * lotStep));

   //--- BUY grid: add level if price dropped by GridSpacingPips from last grid entry
   if(g_gridDir == 1 && g_lastGridPrice > 0.0)
     {
      if(ask <= g_lastGridPrice - gridDist)
        {
         double sl = (slDist > 0) ? NormalizeDouble(ask - slDist, _Digits) : 0.0;

         string comment = StringFormat("TM:%s|SIG:%s|LVL:%d", "Grid", "BUY_RECOV", gridCount + 1);

         if(g_trade.Buy(recoveryLot, _Symbol, ask, sl, 0.0, comment))
           {
            ulong ticket = g_trade.ResultOrder();
            if(ticket > 0)
              {
               TM_OnTradeOpened(ticket, _Symbol, "buy", recoveryLot, ask, sl, 0.0);
               g_lastGridPrice = ask;
              }
           }
        }
     }

   //--- SELL grid: add level if price rose by GridSpacingPips from last grid entry
   if(g_gridDir == -1 && g_lastGridPrice > 0.0)
     {
      if(bid >= g_lastGridPrice + gridDist)
        {
         double sl = (slDist > 0) ? NormalizeDouble(bid + slDist, _Digits) : 0.0;

         string comment = StringFormat("TM:%s|SIG:%s|LVL:%d", "Grid", "SELL_RECOV", gridCount + 1);

         if(g_trade.Sell(recoveryLot, _Symbol, bid, sl, 0.0, comment))
           {
            ulong ticket = g_trade.ResultOrder();
            if(ticket > 0)
              {
               TM_OnTradeOpened(ticket, _Symbol, "sell", recoveryLot, bid, sl, 0.0);
               g_lastGridPrice = bid;
              }
           }
        }
     }

   TM_ManageOpenTrades();
  }

//+------------------------------------------------------------------+
//| Close all grid positions with our magic number                    |
//+------------------------------------------------------------------+
void CloseAllGridPositions()
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;

      double profit = PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);

      if(g_trade.PositionClose(ticket))
         TM_OnTradeClosed(ticket, profit);
     }
  }

//+------------------------------------------------------------------+
//| Check if a position exists in the given direction                 |
//+------------------------------------------------------------------+
bool HasPositionByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) == direction)
         return true;
     }
   return false;
  }

//+------------------------------------------------------------------+
//| Close all positions in the given direction                        |
//+------------------------------------------------------------------+
void ClosePositionsByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) != direction) continue;

      double profit = PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);

      if(g_trade.PositionClose(ticket))
         TM_OnTradeClosed(ticket, profit);
     }
  }
//+------------------------------------------------------------------+
