//+------------------------------------------------------------------+
//| {{STRATEGY_NAME}} EA                                              |
//| Generated by TradeMetrics Pro Strategy Hub                        |
//+------------------------------------------------------------------+
#property copyright "TradeMetrics Pro"
#property version   "1.00"
#property strict

// -- Includes ────────────────────────────────────────────────────
#include <EdgeRelay_Common.mqh>
#include <EdgeRelay_Crypto.mqh>
#include <EdgeRelay_Http.mqh>
#include <EdgeRelay_Queue.mqh>
#include <EdgeRelay_JournalSync.mqh>
#include <EdgeRelay_JournalQueue.mqh>
#include <Trade\Trade.mqh>

// -- Strategy Parameters ─────────────────────────────────────────
input int              GridSpacingPips  = {{GRID_SPACING}};     // Grid Spacing (pips)
input int              MaxGridLevels    = {{MAX_GRID_LEVELS}};  // Max Grid Levels
input double           LotMultiplier    = {{LOT_MULTIPLIER}};   // Lot Multiplier per Level
input double           TakeProfitGrid   = {{TP_GRID}};          // Grid TP (pips from avg)
input ENUM_TIMEFRAMES  Timeframe        = {{TIMEFRAME}};        // Timeframe

// -- Trade Management ────────────────────────────────────────────
input double LotSize            = {{LOT_SIZE}};              // Lot Size
input int    StopLossPips        = {{SL_PIPS}};               // Stop Loss (pips)
input int    TakeProfitPips      = {{TP_PIPS}};               // Take Profit (pips)
input int    MaxSpreadPoints     = {{MAX_SPREAD}};            // Max Spread (points)
input int    MagicNumber         = {{MAGIC_NUMBER}};          // Magic Number

// -- Risk Management ─────────────────────────────────────────────
input double MaxDailyLossPercent   = {{MAX_DAILY_LOSS}};      // Max Daily Loss %
input int    ConsecutiveLossLimit  = {{CONSEC_LOSS_LIMIT}};   // Consecutive Loss Limit
input double BreakevenTriggerRR    = {{BE_TRIGGER_RR}};       // Breakeven at R:R
input double TrailingStopPips      = {{TRAILING_STOP}};       // Trailing Stop (pips)
input bool   UseSessionFilter      = {{USE_SESSION_FILTER}};  // Session Filter
input int    SessionStartHour      = {{SESSION_START}};       // Session Start (UTC)
input int    SessionEndHour        = {{SESSION_END}};         // Session End (UTC)

// -- TradeMetrics Integration ────────────────────────────────────
input string AccountID        = "{{ACCOUNT_ID}}";
input string API_Key          = "{{API_KEY}}";
input string API_Secret       = "";                           // API Secret (enter manually)
input string API_Endpoint     = "https://edgerelay-signal-ingestion.ghwmelite.workers.dev";
input string JournalEndpoint  = "https://edgerelay-journal-sync.ghwmelite.workers.dev";
input bool   EnableJournal    = true;                         // Enable Journal Sync

// -- Shared Integration Block ────────────────────────────────────
{{TRADEMETRICS_BLOCK}}

// -- Strategy Variables ──────────────────────────────────────────
int      g_emaHandle  = INVALID_HANDLE;
int      g_gridDir    = 0;    // 1 = BUY grid, -1 = SELL grid, 0 = none
double   g_lastGridPrice = 0.0;
CTrade   g_trade;

//+------------------------------------------------------------------+
//| Expert initialization function                                    |
//+------------------------------------------------------------------+
int OnInit()
  {
   //--- Create EMA handle for initial direction
   g_emaHandle = iMA(_Symbol, Timeframe, 50, 0, MODE_EMA, PRICE_CLOSE);

   if(g_emaHandle == INVALID_HANDLE)
     {
      PrintFormat("[GridRecovery] Failed to create EMA handle. Error: %d", GetLastError());
      return INIT_FAILED;
     }

   //--- Configure trade object
   g_trade.SetExpertMagicNumber(MagicNumber);
   g_trade.SetDeviationInPoints(10);
   g_trade.SetTypeFilling(ORDER_FILLING_IOC);

   //--- Initialize TradeMetrics integration
   return TM_OnInit();
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                  |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   //--- Release indicator handles
   if(g_emaHandle != INVALID_HANDLE)
      IndicatorRelease(g_emaHandle);

   TM_OnDeinit(reason);
  }

//+------------------------------------------------------------------+
//| Timer event handler                                               |
//+------------------------------------------------------------------+
void OnTimer()
  {
   TM_OnTimer();
  }

//+------------------------------------------------------------------+
//| Expert tick function                                              |
//+------------------------------------------------------------------+
void OnTick()
  {
   if(!TM_IsNewBar()) return;
   if(!TM_CanTrade()) return;

   double pip = _Point * ((_Digits == 3 || _Digits == 5) ? 10 : 1);
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

   //--- Count existing grid positions and calculate average entry
   int    gridCount = 0;
   double totalVolume = 0.0;
   double weightedPrice = 0.0;
   ENUM_POSITION_TYPE gridType = POSITION_TYPE_BUY;

   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;

      double vol   = PositionGetDouble(POSITION_VOLUME);
      double entry = PositionGetDouble(POSITION_PRICE_OPEN);
      gridType = (ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE);

      weightedPrice += entry * vol;
      totalVolume   += vol;
      gridCount++;
     }

   double avgEntry = 0.0;
   if(totalVolume > 0.0)
      avgEntry = weightedPrice / totalVolume;

   //--- Check if grid TP is reached: close all positions
   if(gridCount > 0 && avgEntry > 0.0)
     {
      double tpDist = TakeProfitGrid * pip;
      bool hitTP = false;

      if(gridType == POSITION_TYPE_BUY && bid >= avgEntry + tpDist)
         hitTP = true;
      else if(gridType == POSITION_TYPE_SELL && ask <= avgEntry - tpDist)
         hitTP = true;

      if(hitTP)
        {
         CloseAllGridPositions();
         g_gridDir = 0;
         g_lastGridPrice = 0.0;
         TM_ManageOpenTrades();
         return;
        }
     }

   //--- No positions: determine initial direction from EMA
   if(gridCount == 0)
     {
      double ema[];
      ArraySetAsSeries(ema, true);
      if(CopyBuffer(g_emaHandle, 0, 0, 3, ema) < 3) return;

      double close1 = iClose(_Symbol, Timeframe, 1);

      if(close1 > ema[1])
        {
         //--- BUY initial entry
         double sl = (StopLossPips > 0) ? NormalizeDouble(ask - StopLossPips * pip, _Digits) : 0.0;
         double tp = 0.0;  // Grid manages TP

         if(g_trade.Buy(LotSize, _Symbol, ask, sl, tp, "Grid"))
           {
            ulong ticket = g_trade.ResultOrder();
            if(ticket > 0)
              {
               TM_OnTradeOpened(ticket, _Symbol, "buy", LotSize, ask, sl, tp);
               g_gridDir = 1;
               g_lastGridPrice = ask;
              }
           }
        }
      else
        {
         //--- SELL initial entry
         double sl = (StopLossPips > 0) ? NormalizeDouble(bid + StopLossPips * pip, _Digits) : 0.0;
         double tp = 0.0;

         if(g_trade.Sell(LotSize, _Symbol, bid, sl, tp, "Grid"))
           {
            ulong ticket = g_trade.ResultOrder();
            if(ticket > 0)
              {
               TM_OnTradeOpened(ticket, _Symbol, "sell", LotSize, bid, sl, tp);
               g_gridDir = -1;
               g_lastGridPrice = bid;
              }
           }
        }

      TM_ManageOpenTrades();
      return;
     }

   //--- Grid is active: check if we need to add a new level
   if(gridCount >= MaxGridLevels)
     {
      TM_ManageOpenTrades();
      return;
     }

   double gridDist = GridSpacingPips * pip;
   double nextLot  = LotSize;
   for(int lvl = 1; lvl < gridCount; lvl++)
      nextLot *= LotMultiplier;

   //--- BUY grid: add level if price dropped by GridSpacingPips from last grid entry
   if(g_gridDir == 1 && g_lastGridPrice > 0.0)
     {
      if(ask <= g_lastGridPrice - gridDist)
        {
         double sl = (StopLossPips > 0) ? NormalizeDouble(ask - StopLossPips * pip, _Digits) : 0.0;

         if(g_trade.Buy(nextLot, _Symbol, ask, sl, 0.0, "Grid"))
           {
            ulong ticket = g_trade.ResultOrder();
            if(ticket > 0)
              {
               TM_OnTradeOpened(ticket, _Symbol, "buy", nextLot, ask, sl, 0.0);
               g_lastGridPrice = ask;
              }
           }
        }
     }

   //--- SELL grid: add level if price rose by GridSpacingPips from last grid entry
   if(g_gridDir == -1 && g_lastGridPrice > 0.0)
     {
      if(bid >= g_lastGridPrice + gridDist)
        {
         double sl = (StopLossPips > 0) ? NormalizeDouble(bid + StopLossPips * pip, _Digits) : 0.0;

         if(g_trade.Sell(nextLot, _Symbol, bid, sl, 0.0, "Grid"))
           {
            ulong ticket = g_trade.ResultOrder();
            if(ticket > 0)
              {
               TM_OnTradeOpened(ticket, _Symbol, "sell", nextLot, bid, sl, 0.0);
               g_lastGridPrice = bid;
              }
           }
        }
     }

   TM_ManageOpenTrades();
  }

//+------------------------------------------------------------------+
//| Close all grid positions with our magic number                    |
//+------------------------------------------------------------------+
void CloseAllGridPositions()
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;

      double profit = PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);

      if(g_trade.PositionClose(ticket))
         TM_OnTradeClosed(ticket, profit);
     }
  }

//+------------------------------------------------------------------+
//| Check if a position exists in the given direction                 |
//+------------------------------------------------------------------+
bool HasPositionByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) == direction)
         return true;
     }
   return false;
  }

//+------------------------------------------------------------------+
//| Close all positions in the given direction                        |
//+------------------------------------------------------------------+
void ClosePositionsByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) != direction) continue;

      double profit = PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);

      if(g_trade.PositionClose(ticket))
         TM_OnTradeClosed(ticket, profit);
     }
  }
//+------------------------------------------------------------------+
