//+------------------------------------------------------------------+
//| {{STRATEGY_NAME}} EA                                              |
//| Generated by TradeMetrics Pro Strategy Hub                        |
//+------------------------------------------------------------------+
#property copyright "TradeMetrics Pro"
#property version   "1.00"
#property strict

// ── Includes ────────────────────────────────────────────────────
#include <EdgeRelay_Common.mqh>
#include <EdgeRelay_Crypto.mqh>
#include <EdgeRelay_Http.mqh>
#include <EdgeRelay_Queue.mqh>
#include <EdgeRelay_JournalSync.mqh>
#include <EdgeRelay_JournalQueue.mqh>
#include <Trade\Trade.mqh>

// ── Strategy Parameters ─────────────────────────────────────────
input int              ScalpSessionStart  = {{SCALP_SESSION_START}};  // Session Start Hour (UTC)
input int              ScalpSessionEnd    = {{SCALP_SESSION_END}};    // Session End Hour (UTC)
input int              EMAPeriod          = {{EMA_PERIOD}};           // EMA Period
input int              RSIFilterPeriod    = {{RSI_FILTER_PERIOD}};    // RSI Filter Period
input ENUM_TIMEFRAMES  Timeframe          = {{TIMEFRAME}};            // Timeframe

// ── Trade Management ────────────────────────────────────────────
input double LotSize            = {{LOT_SIZE}};              // Lot Size
input int    StopLossPips        = {{SL_PIPS}};               // Stop Loss (pips)
input int    TakeProfitPips      = {{TP_PIPS}};               // Take Profit (pips)
input int    MaxSpreadPoints     = {{MAX_SPREAD}};            // Max Spread (points)
input int    MagicNumber         = {{MAGIC_NUMBER}};          // Magic Number

// ── Risk Management ─────────────────────────────────────────────
input double MaxDailyLossPercent   = {{MAX_DAILY_LOSS}};      // Max Daily Loss %
input int    ConsecutiveLossLimit  = {{CONSEC_LOSS_LIMIT}};   // Consecutive Loss Limit
input double BreakevenTriggerRR    = {{BE_TRIGGER_RR}};       // Breakeven at R:R
input int    TrailingStopPips      = {{TRAILING_STOP}};       // Trailing Stop (pips)
input bool   UseSessionFilter      = {{USE_SESSION_FILTER}};  // Session Filter
input int    SessionStartHour      = {{SESSION_START}};       // Session Start (UTC)
input int    SessionEndHour        = {{SESSION_END}};         // Session End (UTC)

// ── TradeMetrics Integration ────────────────────────────────────
input string AccountID        = "{{ACCOUNT_ID}}";
input string API_Key          = "{{API_KEY}}";
input string API_Secret       = "";                           // API Secret (enter manually)
input string API_Endpoint     = "https://edgerelay-signal-ingestion.ghwmelite.workers.dev";
input string JournalEndpoint  = "https://edgerelay-journal-sync.ghwmelite.workers.dev";
input bool   EnableJournal    = true;                         // Enable Journal Sync

// ── Shared Integration Block ────────────────────────────────────
{{TRADEMETRICS_BLOCK}}

// ── Strategy Variables ──────────────────────────────────────────
int      g_emaHandle = INVALID_HANDLE;
int      g_rsiHandle = INVALID_HANDLE;
CTrade   g_trade;

//+------------------------------------------------------------------+
//| Expert initialization function                                    |
//+------------------------------------------------------------------+
int OnInit()
  {
   //--- Create indicator handles
   g_emaHandle = iMA(_Symbol, Timeframe, EMAPeriod, 0, MODE_EMA, PRICE_CLOSE);
   g_rsiHandle = iRSI(_Symbol, Timeframe, RSIFilterPeriod, PRICE_CLOSE);

   if(g_emaHandle == INVALID_HANDLE || g_rsiHandle == INVALID_HANDLE)
     {
      PrintFormat("[LondonScalper] Failed to create indicator handles. Error: %d", GetLastError());
      return INIT_FAILED;
     }

   //--- Configure trade object
   g_trade.SetExpertMagicNumber(MagicNumber);
   g_trade.SetDeviationInPoints(10);
   g_trade.SetTypeFilling(ORDER_FILLING_IOC);

   //--- Initialize TradeMetrics integration
   return TM_OnInit();
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                  |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   //--- Release indicator handles
   if(g_emaHandle != INVALID_HANDLE)
      IndicatorRelease(g_emaHandle);
   if(g_rsiHandle != INVALID_HANDLE)
      IndicatorRelease(g_rsiHandle);

   TM_OnDeinit(reason);
  }

//+------------------------------------------------------------------+
//| Expert tick function                                              |
//+------------------------------------------------------------------+
void OnTick()
  {
   TM_OnTick();

   if(!TM_IsNewBar()) return;

   //--- Get current GMT hour
   MqlDateTime dt;
   TimeGMT(dt);
   int gmtHour = dt.hour;

   //--- At session end: close ALL open positions with our MagicNumber
   if(gmtHour >= ScalpSessionEnd)
     {
      CloseAllPositions();
      return;
     }

   //--- Only trade within session window
   if(gmtHour < ScalpSessionStart || gmtHour >= ScalpSessionEnd)
      return;

   if(!TM_CanTrade()) return;

   //--- Read EMA values: [0] = bar 0 (current), [1] = bar 1 (last closed)
   double ema[];
   ArraySetAsSeries(ema, true);
   if(CopyBuffer(g_emaHandle, 0, 0, 2, ema) < 2) return;

   //--- Read RSI values
   double rsi[];
   ArraySetAsSeries(rsi, true);
   if(CopyBuffer(g_rsiHandle, 0, 0, 2, rsi) < 2) return;

   //--- Use bar 1 (last closed) for signal detection
   double emaValue = ema[1];
   double rsiValue = rsi[1];

   //--- Get close of last completed bar
   double closeArr[];
   ArraySetAsSeries(closeArr, true);
   if(CopyClose(_Symbol, Timeframe, 1, 1, closeArr) < 1) return;
   double lastClose = closeArr[0];

   //--- Detect signals
   bool buySignal  = (lastClose > emaValue && rsiValue > 50.0);
   bool sellSignal = (lastClose < emaValue && rsiValue < 50.0);

   //--- Calculate pip value for SL/TP
   double pip = _Point * ((_Digits == 3 || _Digits == 5) ? 10 : 1);
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

   //--- BUY signal: price above EMA and RSI > 50
   if(buySignal)
     {
      //--- Close any existing SELL positions with our magic number
      ClosePositionsByDirection(POSITION_TYPE_SELL);

      //--- Only open if no existing BUY position
      if(!HasPositionByDirection(POSITION_TYPE_BUY))
        {
         double sl = (StopLossPips > 0)   ? NormalizeDouble(ask - StopLossPips * pip, _Digits)   : 0.0;
         double tp = (TakeProfitPips > 0)  ? NormalizeDouble(ask + TakeProfitPips * pip, _Digits) : 0.0;

         if(g_trade.Buy(LotSize, _Symbol, ask, sl, tp, "LondonScalper"))
           {
            ulong ticket = g_trade.ResultOrder();
            if(ticket > 0)
               TM_OnTradeOpened(ticket, _Symbol, "buy", LotSize, ask, sl, tp);
           }
        }
     }

   //--- SELL signal: price below EMA and RSI < 50
   if(sellSignal)
     {
      //--- Close any existing BUY positions with our magic number
      ClosePositionsByDirection(POSITION_TYPE_BUY);

      //--- Only open if no existing SELL position
      if(!HasPositionByDirection(POSITION_TYPE_SELL))
        {
         double sl = (StopLossPips > 0)   ? NormalizeDouble(bid + StopLossPips * pip, _Digits)   : 0.0;
         double tp = (TakeProfitPips > 0)  ? NormalizeDouble(bid - TakeProfitPips * pip, _Digits) : 0.0;

         if(g_trade.Sell(LotSize, _Symbol, bid, sl, tp, "LondonScalper"))
           {
            ulong ticket = g_trade.ResultOrder();
            if(ticket > 0)
               TM_OnTradeOpened(ticket, _Symbol, "sell", LotSize, bid, sl, tp);
           }
        }
     }

   TM_ManageOpenTrades();
  }

//+------------------------------------------------------------------+
//| Check if a position exists in the given direction                 |
//+------------------------------------------------------------------+
bool HasPositionByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) == direction)
         return true;
     }
   return false;
  }

//+------------------------------------------------------------------+
//| Close all positions in the given direction                        |
//+------------------------------------------------------------------+
void ClosePositionsByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) != direction) continue;

      double profit = PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);

      if(g_trade.PositionClose(ticket))
         TM_OnTradeClosed(ticket, profit);
     }
  }

//+------------------------------------------------------------------+
//| Close ALL open positions with our MagicNumber (session end)       |
//+------------------------------------------------------------------+
void CloseAllPositions()
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;

      double profit = PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);

      if(g_trade.PositionClose(ticket))
         TM_OnTradeClosed(ticket, profit);
     }
  }
//+------------------------------------------------------------------+
