//+------------------------------------------------------------------+
//| {{STRATEGY_NAME}} EA                                              |
//| Generated by TradeMetrics Pro Strategy Hub                        |
//+------------------------------------------------------------------+
#property copyright "TradeMetrics Pro"
#property version   "1.00"
#property strict

// ── Includes ────────────────────────────────────────────────────
#include <EdgeRelay_Common.mqh>
#include <EdgeRelay_Crypto.mqh>
#include <EdgeRelay_Http.mqh>
#include <EdgeRelay_Queue.mqh>
#include <EdgeRelay_JournalSync.mqh>
#include <EdgeRelay_JournalQueue.mqh>
#include <Trade\Trade.mqh>

// ── Strategy Parameters ─────────────────────────────────────────
input int              ScalpSessionStart  = {{SCALP_SESSION_START}};  // Session Start Hour (UTC)
input int              ScalpSessionEnd    = {{SCALP_SESSION_END}};    // Session End Hour (UTC)
input int              EMAPeriod          = {{EMA_PERIOD}};           // EMA Period
input int              RSIFilterPeriod    = {{RSI_FILTER_PERIOD}};    // RSI Filter Period
input ENUM_TIMEFRAMES  Timeframe          = {{TIMEFRAME}};            // Timeframe

// ── Asian Range Reference ─────────────────────────────────────
input int              AsianStartHour     = {{ASIAN_START_HOUR}};    // Asian Session Start (UTC, e.g. 0)
input int              AsianEndHour       = {{ASIAN_END_HOUR}};      // Asian Session End (UTC, e.g. 8)
input bool             UseAsianTP         = {{USE_ASIAN_TP}};        // Use Asian Range for TP targets

// ── Spread Spike Protection ───────────────────────────────────
input int              AvgSpreadBars      = {{AVG_SPREAD_BARS}};     // Bars for Average Spread Calc
input double           SpreadSpikeMultiplier = {{SPREAD_SPIKE_MULT}}; // Max Spread vs Avg (e.g. 2.0)

// ── Strategy Filters ──────────────────────────────────────────
input int    ADXPeriod        = {{ADX_PERIOD}};              // ADX Period (0=disabled)
input double ADXMinStrength   = {{ADX_MIN_STRENGTH}};        // Min ADX for Entry

// ── ATR Dynamic Stops ─────────────────────────────────────────
input bool   UseATRStops      = {{USE_ATR_STOPS}};           // Use ATR for SL/TP
input int    ATRStopPeriod    = {{ATR_STOP_PERIOD}};         // ATR Period for Stops
input double ATRSLMultiplier  = {{ATR_SL_MULT}};             // ATR SL Multiplier
input double ATRTPMultiplier  = {{ATR_TP_MULT}};             // ATR TP Multiplier

// ── Risk-Based Sizing ─────────────────────────────────────────
input double RiskPercent      = {{RISK_PERCENT}};            // Risk % of Balance (0=use fixed lot)

// ── Trade Management ────────────────────────────────────────────
input double LotSize            = {{LOT_SIZE}};              // Lot Size
input int    StopLossPips        = {{SL_PIPS}};               // Stop Loss (pips)
input int    TakeProfitPips      = {{TP_PIPS}};               // Take Profit (pips)
input int    MaxSpreadPoints     = {{MAX_SPREAD}};            // Max Spread (points)
input int    MagicNumber         = {{MAGIC_NUMBER}};          // Magic Number

// ── Risk Management ─────────────────────────────────────────────
input double MaxDailyLossPercent   = {{MAX_DAILY_LOSS}};      // Max Daily Loss %
input int    ConsecutiveLossLimit  = {{CONSEC_LOSS_LIMIT}};   // Consecutive Loss Limit
input double BreakevenTriggerRR    = {{BE_TRIGGER_RR}};       // Breakeven at R:R
input double TrailingStopPips      = {{TRAILING_STOP}};       // Trailing Stop (pips)
input bool   UseSessionFilter      = {{USE_SESSION_FILTER}};  // Session Filter
input int    SessionStartHour      = {{SESSION_START}};       // Session Start (UTC)
input int    SessionEndHour        = {{SESSION_END}};         // Session End (UTC)

// ── TradeMetrics Integration ────────────────────────────────────
input string AccountID        = "{{ACCOUNT_ID}}";
input string API_Key          = "{{API_KEY}}";
input string API_Secret       = "";                           // API Secret (enter manually)
input string API_Endpoint     = "https://edgerelay-signal-ingestion.ghwmelite.workers.dev";
input string JournalEndpoint  = "https://edgerelay-journal-sync.ghwmelite.workers.dev";
input bool   EnableJournal    = true;                         // Enable Journal Sync

// ── Shared Integration Block ────────────────────────────────────
{{TRADEMETRICS_BLOCK}}

// ── Strategy Variables ──────────────────────────────────────────
int      g_emaHandle = INVALID_HANDLE;
int      g_rsiHandle = INVALID_HANDLE;
int      g_adxHandle = INVALID_HANDLE;
int      g_atrHandle = INVALID_HANDLE;
CTrade   g_trade;
double   g_asianHigh      = 0.0;
double   g_asianLow       = 0.0;
datetime g_asianCalcDay    = 0;
double   g_avgSpread       = 0.0;
int      g_spreadSamples   = 0;

//+------------------------------------------------------------------+
//| Calculate lot size based on risk percentage                       |
//+------------------------------------------------------------------+
double CalculateLotSize(double slPips)
  {
   if(RiskPercent <= 0 || slPips <= 0) return LotSize;
   double pip = _Point * ((_Digits == 3 || _Digits == 5) ? 10 : 1);
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskAmount = balance * RiskPercent / 100.0;
   double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   if(tickValue <= 0 || tickSize <= 0) return LotSize;
   double lotSize = riskAmount / (slPips * pip / tickSize * tickValue);
   double minLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   lotSize = MathMax(minLot, MathMin(maxLot, MathFloor(lotSize / lotStep) * lotStep));
   return lotSize;
  }

//+------------------------------------------------------------------+
//| Calculate Asian session high/low for current day                  |
//+------------------------------------------------------------------+
void CalculateAsianRange()
  {
   datetime today = StringToTime(TimeToString(TimeCurrent(), TIME_DATE));
   if(today == g_asianCalcDay && g_asianHigh > 0) return;  // Already calculated today

   g_asianCalcDay = today;
   g_asianHigh = 0.0;
   g_asianLow  = 99999.0;

   //--- Scan bars within Asian session hours for today
   int totalBars = iBars(_Symbol, Timeframe);
   for(int i = 1; i < totalBars && i < 500; i++)
     {
      datetime barTime = iTime(_Symbol, Timeframe, i);
      if(barTime < today) break;  // Past today's start

      MqlDateTime dt;
      TimeToStruct(barTime, dt);

      bool inAsian = false;
      if(AsianStartHour < AsianEndHour)
        {
         inAsian = (dt.hour >= AsianStartHour && dt.hour < AsianEndHour);
        }
      else
        {
         inAsian = (dt.hour >= AsianStartHour || dt.hour < AsianEndHour);
        }

      if(inAsian)
        {
         double h = iHigh(_Symbol, Timeframe, i);
         double l = iLow(_Symbol, Timeframe, i);
         if(h > g_asianHigh) g_asianHigh = h;
         if(l < g_asianLow)  g_asianLow  = l;
        }
     }

   if(g_asianLow >= 99999.0)
     {
      g_asianHigh = 0.0;
      g_asianLow  = 0.0;
     }
  }

//+------------------------------------------------------------------+
//| Expert initialization function                                    |
//+------------------------------------------------------------------+
int OnInit()
  {
   //--- Create indicator handles
   g_emaHandle = iMA(_Symbol, Timeframe, EMAPeriod, 0, MODE_EMA, PRICE_CLOSE);
   g_rsiHandle = iRSI(_Symbol, Timeframe, RSIFilterPeriod, PRICE_CLOSE);

   if(g_emaHandle == INVALID_HANDLE || g_rsiHandle == INVALID_HANDLE)
     {
      PrintFormat("[LondonScalper] Failed to create indicator handles. Error: %d", GetLastError());
      return INIT_FAILED;
     }

   //--- ADX filter handle
   if(ADXPeriod > 0)
     {
      g_adxHandle = iADX(_Symbol, Timeframe, ADXPeriod);
      if(g_adxHandle == INVALID_HANDLE)
        {
         PrintFormat("[LondonScalper] Failed to create ADX handle. Error: %d", GetLastError());
         return INIT_FAILED;
        }
     }

   //--- ATR handle for dynamic stops
   if(UseATRStops)
     {
      g_atrHandle = iATR(_Symbol, Timeframe, ATRStopPeriod);
      if(g_atrHandle == INVALID_HANDLE)
        {
         PrintFormat("[LondonScalper] Failed to create ATR handle. Error: %d", GetLastError());
         return INIT_FAILED;
        }
     }

   //--- Configure trade object
   g_trade.SetExpertMagicNumber(MagicNumber);
   g_trade.SetDeviationInPoints(10);
   g_trade.SetTypeFilling(ORDER_FILLING_IOC);

   //--- Initialize spread tracking
   g_avgSpread = 0.0;
   g_spreadSamples = 0;

   //--- Initialize TradeMetrics integration
   return TM_OnInit();
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                  |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   //--- Release indicator handles
   if(g_emaHandle != INVALID_HANDLE)
      IndicatorRelease(g_emaHandle);
   if(g_rsiHandle != INVALID_HANDLE)
      IndicatorRelease(g_rsiHandle);
   if(g_adxHandle != INVALID_HANDLE)
      IndicatorRelease(g_adxHandle);
   if(g_atrHandle != INVALID_HANDLE)
      IndicatorRelease(g_atrHandle);

   TM_OnDeinit(reason);
  }

//+------------------------------------------------------------------+
//| Timer event handler                                               |
//+------------------------------------------------------------------+
void OnTimer()
  {
   TM_OnTimer();
  }

//+------------------------------------------------------------------+
//| Expert tick function                                              |
//+------------------------------------------------------------------+
void OnTick()
  {
   if(!TM_IsNewBar()) return;

   //--- Update rolling average spread
   double currentSpread = (double)SymbolInfoInteger(_Symbol, SYMBOL_SPREAD);
   if(g_spreadSamples < AvgSpreadBars)
     {
      g_avgSpread = (g_avgSpread * g_spreadSamples + currentSpread) / (g_spreadSamples + 1);
      g_spreadSamples++;
     }
   else
     {
      //--- Exponential moving average of spread
      double alpha = 2.0 / (AvgSpreadBars + 1);
      g_avgSpread = alpha * currentSpread + (1.0 - alpha) * g_avgSpread;
     }

   //--- Calculate Asian range for TP reference
   if(UseAsianTP)
      CalculateAsianRange();

   //--- Get current GMT hour
   MqlDateTime dt;
   TimeToStruct(TimeGMT(), dt);
   int gmtHour = dt.hour;

   //--- At session end: close ALL open positions with our MagicNumber
   if(gmtHour >= ScalpSessionEnd)
     {
      CloseAllPositions();
      return;
     }

   //--- Only trade within session window
   if(gmtHour < ScalpSessionStart || gmtHour >= ScalpSessionEnd)
      return;

   if(!TM_CanTrade()) return;

   //--- Spread spike protection: if current spread > SpreadSpikeMultiplier × average, skip
   if(g_avgSpread > 0 && SpreadSpikeMultiplier > 0)
     {
      if(currentSpread > SpreadSpikeMultiplier * g_avgSpread)
        {
         PrintFormat("[LondonScalper] Spread spike blocked: %.0f > %.1f × %.1f",
                     currentSpread, SpreadSpikeMultiplier, g_avgSpread);
         return;
        }
     }

   //--- Read EMA values: [0] = bar 0 (current), [1] = bar 1 (last closed)
   double ema[];
   ArraySetAsSeries(ema, true);
   if(CopyBuffer(g_emaHandle, 0, 0, 2, ema) < 2) return;

   //--- Read RSI values
   double rsi[];
   ArraySetAsSeries(rsi, true);
   if(CopyBuffer(g_rsiHandle, 0, 0, 2, rsi) < 2) return;

   //--- Use bar 1 (last closed) for signal detection
   double emaValue = ema[1];
   double rsiValue = rsi[1];

   //--- Get close of last completed bar
   double closeArr[];
   ArraySetAsSeries(closeArr, true);
   if(CopyClose(_Symbol, Timeframe, 1, 1, closeArr) < 1) return;
   double lastClose = closeArr[0];

   //--- Detect signals
   bool buySignal  = (lastClose > emaValue && rsiValue > 50.0);
   bool sellSignal = (lastClose < emaValue && rsiValue < 50.0);

   //--- ADX momentum filter
   if((buySignal || sellSignal) && ADXPeriod > 0 && g_adxHandle != INVALID_HANDLE)
     {
      double adxVal[];
      ArraySetAsSeries(adxVal, true);
      if(CopyBuffer(g_adxHandle, 0, 0, 2, adxVal) >= 2)
        {
         if(adxVal[1] < ADXMinStrength)
           {
            buySignal  = false;
            sellSignal = false;
           }
        }
      else
        {
         buySignal  = false;
         sellSignal = false;
        }
     }

   //--- Calculate pip value for SL/TP
   double pip = _Point * ((_Digits == 3 || _Digits == 5) ? 10 : 1);
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

   //--- Read ATR for dynamic stops
   double atrValue = 0.0;
   if(UseATRStops && g_atrHandle != INVALID_HANDLE)
     {
      double atrArr[];
      ArraySetAsSeries(atrArr, true);
      if(CopyBuffer(g_atrHandle, 0, 0, 2, atrArr) >= 2)
         atrValue = atrArr[1];
     }

   //--- BUY signal: price above EMA and RSI > 50
   if(buySignal)
     {
      //--- Close any existing SELL positions with our magic number
      ClosePositionsByDirection(POSITION_TYPE_SELL);

      //--- Only open if no existing BUY position
      if(!HasPositionByDirection(POSITION_TYPE_BUY))
        {
         double slDist = 0.0;
         double tpDist = 0.0;

         if(UseATRStops && atrValue > 0)
           {
            slDist = atrValue * ATRSLMultiplier;
            tpDist = atrValue * ATRTPMultiplier;
           }
         else
           {
            slDist = StopLossPips * pip;
            tpDist = TakeProfitPips * pip;
           }

         //--- Asian range TP override: target Asian high if available and larger
         if(UseAsianTP && g_asianHigh > 0 && g_asianHigh > ask)
           {
            double asianTPDist = g_asianHigh - ask;
            if(asianTPDist > tpDist)
               tpDist = asianTPDist;
           }

         double sl = (slDist > 0) ? NormalizeDouble(ask - slDist, _Digits) : 0.0;
         double tp = (tpDist > 0) ? NormalizeDouble(ask + tpDist, _Digits) : 0.0;

         double slPips = (slDist > 0) ? slDist / pip : 0.0;
         double lot = CalculateLotSize(slPips);

         string comment = StringFormat("TM:%s|SIG:%s", "London_Scalp", "BUY_MOMENTUM");

         if(g_trade.Buy(lot, _Symbol, ask, sl, tp, comment))
           {
            ulong ticket = g_trade.ResultOrder();
            if(ticket > 0)
               TM_OnTradeOpened(ticket, _Symbol, "buy", lot, ask, sl, tp);
           }
        }
     }

   //--- SELL signal: price below EMA and RSI < 50
   if(sellSignal)
     {
      //--- Close any existing BUY positions with our magic number
      ClosePositionsByDirection(POSITION_TYPE_BUY);

      //--- Only open if no existing SELL position
      if(!HasPositionByDirection(POSITION_TYPE_SELL))
        {
         double slDist = 0.0;
         double tpDist = 0.0;

         if(UseATRStops && atrValue > 0)
           {
            slDist = atrValue * ATRSLMultiplier;
            tpDist = atrValue * ATRTPMultiplier;
           }
         else
           {
            slDist = StopLossPips * pip;
            tpDist = TakeProfitPips * pip;
           }

         //--- Asian range TP override: target Asian low if available and larger
         if(UseAsianTP && g_asianLow > 0 && g_asianLow < bid)
           {
            double asianTPDist = bid - g_asianLow;
            if(asianTPDist > tpDist)
               tpDist = asianTPDist;
           }

         double sl = (slDist > 0) ? NormalizeDouble(bid + slDist, _Digits) : 0.0;
         double tp = (tpDist > 0) ? NormalizeDouble(bid - tpDist, _Digits) : 0.0;

         double slPips = (slDist > 0) ? slDist / pip : 0.0;
         double lot = CalculateLotSize(slPips);

         string comment = StringFormat("TM:%s|SIG:%s", "London_Scalp", "SELL_MOMENTUM");

         if(g_trade.Sell(lot, _Symbol, bid, sl, tp, comment))
           {
            ulong ticket = g_trade.ResultOrder();
            if(ticket > 0)
               TM_OnTradeOpened(ticket, _Symbol, "sell", lot, bid, sl, tp);
           }
        }
     }

   TM_ManageOpenTrades();
  }

//+------------------------------------------------------------------+
//| Check if a position exists in the given direction                 |
//+------------------------------------------------------------------+
bool HasPositionByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) == direction)
         return true;
     }
   return false;
  }

//+------------------------------------------------------------------+
//| Close all positions in the given direction                        |
//+------------------------------------------------------------------+
void ClosePositionsByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) != direction) continue;

      double profit = PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);

      if(g_trade.PositionClose(ticket))
         TM_OnTradeClosed(ticket, profit);
     }
  }

//+------------------------------------------------------------------+
//| Close ALL open positions with our MagicNumber (session end)       |
//+------------------------------------------------------------------+
void CloseAllPositions()
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;

      double profit = PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);

      if(g_trade.PositionClose(ticket))
         TM_OnTradeClosed(ticket, profit);
     }
  }
//+------------------------------------------------------------------+
