//+------------------------------------------------------------------+
//| {{STRATEGY_NAME}} EA                                              |
//| Generated by TradeMetrics Pro Strategy Hub                        |
//+------------------------------------------------------------------+
#property copyright "TradeMetrics Pro"
#property version   "1.00"
#property strict

// ── Includes ────────────────────────────────────────────────────
#include <EdgeRelay_Common.mqh>
#include <EdgeRelay_Crypto.mqh>
#include <EdgeRelay_Http.mqh>
#include <EdgeRelay_Queue.mqh>
#include <EdgeRelay_JournalSync.mqh>
#include <EdgeRelay_JournalQueue.mqh>
#include <Trade\Trade.mqh>

// ── Strategy Parameters ─────────────────────────────────────────
input ENUM_TIMEFRAMES  HigherTF        = {{HIGHER_TF}};        // Higher Timeframe (trend)
input ENUM_TIMEFRAMES  LowerTF         = {{LOWER_TF}};         // Lower Timeframe (entry)
input int              TrendEMAPeriod  = {{TREND_EMA_PERIOD}};  // Trend EMA Period
input int              StochK          = {{STOCH_K}};           // Stochastic %K
input int              StochD          = {{STOCH_D}};           // Stochastic %D
input int              StochSlowing    = {{STOCH_SLOWING}};     // Stochastic Slowing

// ── EMA Slope Strength ────────────────────────────────────────
input double           EMASlopeThreshold = {{EMA_SLOPE_THRESHOLD}}; // Min EMA Slope (price units, e.g. 0.0005)
input int              EMASlopeBars      = {{EMA_SLOPE_BARS}};      // EMA Slope Lookback Bars (e.g. 3)

// ── Strategy Filters ──────────────────────────────────────────
input int    ADXPeriod        = {{ADX_PERIOD}};              // ADX Period on Higher TF (0=disabled)
input double ADXMinStrength   = {{ADX_MIN_STRENGTH}};        // Min ADX for Entry

// ── ATR Dynamic Stops ─────────────────────────────────────────
input bool   UseATRStops      = {{USE_ATR_STOPS}};           // Use ATR for SL/TP
input int    ATRStopPeriod    = {{ATR_STOP_PERIOD}};         // ATR Period for Stops
input double ATRSLMultiplier  = {{ATR_SL_MULT}};             // ATR SL Multiplier
input double ATRTPMultiplier  = {{ATR_TP_MULT}};             // ATR TP Multiplier

// ── Risk-Based Sizing ─────────────────────────────────────────
input double RiskPercent      = {{RISK_PERCENT}};            // Risk % of Balance (0=use fixed lot)

// ── Trade Management ────────────────────────────────────────────
input double LotSize            = {{LOT_SIZE}};              // Lot Size
input int    StopLossPips        = {{SL_PIPS}};               // Stop Loss (pips)
input int    TakeProfitPips      = {{TP_PIPS}};               // Take Profit (pips)
input int    MaxSpreadPoints     = {{MAX_SPREAD}};            // Max Spread (points)
input int    MagicNumber         = {{MAGIC_NUMBER}};          // Magic Number

// ── Risk Management ─────────────────────────────────────────────
input double MaxDailyLossPercent   = {{MAX_DAILY_LOSS}};      // Max Daily Loss %
input int    ConsecutiveLossLimit  = {{CONSEC_LOSS_LIMIT}};   // Consecutive Loss Limit
input double BreakevenTriggerRR    = {{BE_TRIGGER_RR}};       // Breakeven at R:R
input double TrailingStopPips      = {{TRAILING_STOP}};       // Trailing Stop (pips)
input bool   UseSessionFilter      = {{USE_SESSION_FILTER}};  // Session Filter
input int    SessionStartHour      = {{SESSION_START}};       // Session Start (UTC)
input int    SessionEndHour        = {{SESSION_END}};         // Session End (UTC)

// ── TradeMetrics Integration ────────────────────────────────────
input string AccountID        = "{{ACCOUNT_ID}}";
input string API_Key          = "{{API_KEY}}";
input string API_Secret       = "";                           // API Secret (enter manually)
input string API_Endpoint     = "https://edgerelay-signal-ingestion.ghwmelite.workers.dev";
input string JournalEndpoint  = "https://edgerelay-journal-sync.ghwmelite.workers.dev";
input bool   EnableJournal    = true;                         // Enable Journal Sync

// ── Shared Integration Block ────────────────────────────────────
{{TRADEMETRICS_BLOCK}}

// ── Strategy Variables ──────────────────────────────────────────
int      g_trendEMAHandle  = INVALID_HANDLE;
int      g_stochHandle     = INVALID_HANDLE;
int      g_adxHandle       = INVALID_HANDLE;
int      g_atrHandle       = INVALID_HANDLE;
CTrade   g_trade;
datetime g_lastLowerBarTime = 0;

//+------------------------------------------------------------------+
//| Calculate lot size based on risk percentage                       |
//+------------------------------------------------------------------+
double CalculateLotSize(double slPips)
  {
   if(RiskPercent <= 0 || slPips <= 0) return LotSize;
   double pip = _Point * ((_Digits == 3 || _Digits == 5) ? 10 : 1);
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskAmount = balance * RiskPercent / 100.0;
   double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   if(tickValue <= 0 || tickSize <= 0) return LotSize;
   double lotSize = riskAmount / (slPips * pip / tickSize * tickValue);
   double minLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   lotSize = MathMax(minLot, MathMin(maxLot, MathFloor(lotSize / lotStep) * lotStep));
   return lotSize;
  }

//+------------------------------------------------------------------+
//| Expert initialization function                                    |
//+------------------------------------------------------------------+
int OnInit()
  {
   //--- Create indicator handles
   g_trendEMAHandle = iMA(_Symbol, HigherTF, TrendEMAPeriod, 0, MODE_EMA, PRICE_CLOSE);
   g_stochHandle    = iStochastic(_Symbol, LowerTF, StochK, StochD, StochSlowing, MODE_SMA, STO_LOWHIGH);

   if(g_trendEMAHandle == INVALID_HANDLE || g_stochHandle == INVALID_HANDLE)
     {
      PrintFormat("[MultiTFTrend] Failed to create indicator handles. Error: %d", GetLastError());
      return INIT_FAILED;
     }

   //--- ADX on Higher TF for trend strength
   if(ADXPeriod > 0)
     {
      g_adxHandle = iADX(_Symbol, HigherTF, ADXPeriod);
      if(g_adxHandle == INVALID_HANDLE)
        {
         PrintFormat("[MultiTFTrend] Failed to create ADX handle. Error: %d", GetLastError());
         return INIT_FAILED;
        }
     }

   //--- ATR handle for dynamic stops (on lower TF for entry precision)
   if(UseATRStops)
     {
      g_atrHandle = iATR(_Symbol, LowerTF, ATRStopPeriod);
      if(g_atrHandle == INVALID_HANDLE)
        {
         PrintFormat("[MultiTFTrend] Failed to create ATR handle. Error: %d", GetLastError());
         return INIT_FAILED;
        }
     }

   //--- Configure trade object
   g_trade.SetExpertMagicNumber(MagicNumber);
   g_trade.SetDeviationInPoints(10);
   g_trade.SetTypeFilling(ORDER_FILLING_IOC);

   //--- Initialize TradeMetrics integration
   return TM_OnInit();
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                  |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   //--- Release indicator handles
   if(g_trendEMAHandle != INVALID_HANDLE)
      IndicatorRelease(g_trendEMAHandle);
   if(g_stochHandle != INVALID_HANDLE)
      IndicatorRelease(g_stochHandle);
   if(g_adxHandle != INVALID_HANDLE)
      IndicatorRelease(g_adxHandle);
   if(g_atrHandle != INVALID_HANDLE)
      IndicatorRelease(g_atrHandle);

   TM_OnDeinit(reason);
  }

//+------------------------------------------------------------------+
//| Timer event handler                                               |
//+------------------------------------------------------------------+
void OnTimer()
  {
   TM_OnTimer();
  }

//+------------------------------------------------------------------+
//| Expert tick function                                              |
//+------------------------------------------------------------------+
void OnTick()
  {
   //--- Detect new bar on the LOWER timeframe (entry timeframe)
   datetime currentLowerBar = iTime(_Symbol, LowerTF, 0);
   if(currentLowerBar == g_lastLowerBarTime) return;
   g_lastLowerBarTime = currentLowerBar;

   if(!TM_CanTrade()) return;

   //--- Read EMA on Higher TF: need enough bars for slope check
   int emaBarsNeeded = EMASlopeBars + 2;
   if(emaBarsNeeded < 5) emaBarsNeeded = 5;

   double ema[];
   ArraySetAsSeries(ema, true);
   if(CopyBuffer(g_trendEMAHandle, 0, 0, emaBarsNeeded, ema) < emaBarsNeeded) return;

   //--- Determine trend direction: compare bar 1 (last closed) vs bar (1 + EMASlopeBars)
   int slopeRef = 1 + EMASlopeBars;
   if(slopeRef >= emaBarsNeeded) slopeRef = emaBarsNeeded - 1;

   double emaSlope = ema[1] - ema[slopeRef];
   bool uptrend   = (emaSlope > 0);
   bool downtrend = (emaSlope < 0);

   //--- EMA slope strength threshold: require minimum slope magnitude
   if(EMASlopeThreshold > 0)
     {
      if(MathAbs(emaSlope) < EMASlopeThreshold)
        {
         uptrend   = false;
         downtrend = false;
        }
     }

   //--- ADX trend strength on Higher TF
   if((uptrend || downtrend) && ADXPeriod > 0 && g_adxHandle != INVALID_HANDLE)
     {
      double adxVal[];
      ArraySetAsSeries(adxVal, true);
      if(CopyBuffer(g_adxHandle, 0, 0, 2, adxVal) >= 2)
        {
         if(adxVal[1] < ADXMinStrength)
           {
            uptrend   = false;
            downtrend = false;
           }
        }
      else
        {
         uptrend   = false;
         downtrend = false;
        }
     }

   //--- No trend detected, skip
   if(!uptrend && !downtrend) return;

   //--- Read Stochastic on Lower TF: buffer 0 = %K, buffer 1 = %D
   double stochK[];
   double stochD[];
   ArraySetAsSeries(stochK, true);
   ArraySetAsSeries(stochD, true);

   if(CopyBuffer(g_stochHandle, 0, 0, 3, stochK) < 3) return;
   if(CopyBuffer(g_stochHandle, 1, 0, 3, stochD) < 3) return;

   //--- Use bars 1 (last closed) and 2 (previous) for crossover detection
   double kCurr = stochK[1];
   double kPrev = stochK[2];
   double dCurr = stochD[1];
   double dPrev = stochD[2];

   //--- BUY: uptrend + Stochastic %K crosses above %D from below 20
   bool buySignal  = uptrend && (kPrev <= dPrev && kCurr > dCurr) && (kPrev < 20.0);

   //--- SELL: downtrend + Stochastic %K crosses below %D from above 80
   bool sellSignal = downtrend && (kPrev >= dPrev && kCurr < dCurr) && (kPrev > 80.0);

   //--- Calculate pip value for SL/TP
   double pip = _Point * ((_Digits == 3 || _Digits == 5) ? 10 : 1);
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

   //--- Read ATR for dynamic stops
   double atrValue = 0.0;
   if(UseATRStops && g_atrHandle != INVALID_HANDLE)
     {
      double atrArr[];
      ArraySetAsSeries(atrArr, true);
      if(CopyBuffer(g_atrHandle, 0, 0, 2, atrArr) >= 2)
         atrValue = atrArr[1];
     }

   //--- BUY signal: uptrend with oversold pullback entry
   if(buySignal)
     {
      //--- Close any existing SELL positions with our magic number
      ClosePositionsByDirection(POSITION_TYPE_SELL);

      //--- Only open if no existing BUY position
      if(!HasPositionByDirection(POSITION_TYPE_BUY))
        {
         double slDist = 0.0;
         double tpDist = 0.0;

         if(UseATRStops && atrValue > 0)
           {
            slDist = atrValue * ATRSLMultiplier;
            tpDist = atrValue * ATRTPMultiplier;
           }
         else
           {
            slDist = StopLossPips * pip;
            tpDist = TakeProfitPips * pip;
           }

         double sl = (slDist > 0) ? NormalizeDouble(ask - slDist, _Digits) : 0.0;
         double tp = (tpDist > 0) ? NormalizeDouble(ask + tpDist, _Digits) : 0.0;

         double slPips = (slDist > 0) ? slDist / pip : 0.0;
         double lot = CalculateLotSize(slPips);

         string comment = StringFormat("TM:%s|SIG:%s", "MultiTF", "BUY_PULLBACK");

         if(g_trade.Buy(lot, _Symbol, ask, sl, tp, comment))
           {
            ulong ticket = g_trade.ResultOrder();
            if(ticket > 0)
               TM_OnTradeOpened(ticket, _Symbol, "buy", lot, ask, sl, tp);
           }
        }
     }

   //--- SELL signal: downtrend with overbought pullback entry
   if(sellSignal)
     {
      //--- Close any existing BUY positions with our magic number
      ClosePositionsByDirection(POSITION_TYPE_BUY);

      //--- Only open if no existing SELL position
      if(!HasPositionByDirection(POSITION_TYPE_SELL))
        {
         double slDist = 0.0;
         double tpDist = 0.0;

         if(UseATRStops && atrValue > 0)
           {
            slDist = atrValue * ATRSLMultiplier;
            tpDist = atrValue * ATRTPMultiplier;
           }
         else
           {
            slDist = StopLossPips * pip;
            tpDist = TakeProfitPips * pip;
           }

         double sl = (slDist > 0) ? NormalizeDouble(bid + slDist, _Digits) : 0.0;
         double tp = (tpDist > 0) ? NormalizeDouble(bid - tpDist, _Digits) : 0.0;

         double slPips = (slDist > 0) ? slDist / pip : 0.0;
         double lot = CalculateLotSize(slPips);

         string comment = StringFormat("TM:%s|SIG:%s", "MultiTF", "SELL_PULLBACK");

         if(g_trade.Sell(lot, _Symbol, bid, sl, tp, comment))
           {
            ulong ticket = g_trade.ResultOrder();
            if(ticket > 0)
               TM_OnTradeOpened(ticket, _Symbol, "sell", lot, bid, sl, tp);
           }
        }
     }

   TM_ManageOpenTrades();
  }

//+------------------------------------------------------------------+
//| Check if a position exists in the given direction                 |
//+------------------------------------------------------------------+
bool HasPositionByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) == direction)
         return true;
     }
   return false;
  }

//+------------------------------------------------------------------+
//| Close all positions in the given direction                        |
//+------------------------------------------------------------------+
void ClosePositionsByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) != direction) continue;

      double profit = PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);

      if(g_trade.PositionClose(ticket))
         TM_OnTradeClosed(ticket, profit);
     }
  }
//+------------------------------------------------------------------+
