//+------------------------------------------------------------------+
//| {{STRATEGY_NAME}} EA                                              |
//| Generated by TradeMetrics Pro Strategy Hub                        |
//+------------------------------------------------------------------+
#property copyright "TradeMetrics Pro"
#property version   "1.00"
#property strict

// ── Includes ────────────────────────────────────────────────────
#include <EdgeRelay_Common.mqh>
#include <EdgeRelay_Crypto.mqh>
#include <EdgeRelay_Http.mqh>
#include <EdgeRelay_Queue.mqh>
#include <EdgeRelay_JournalSync.mqh>
#include <EdgeRelay_JournalQueue.mqh>
#include <Trade\Trade.mqh>

// ── Strategy Parameters ─────────────────────────────────────────
input ENUM_TIMEFRAMES  HigherTF        = {{HIGHER_TF}};        // Higher Timeframe (trend)
input ENUM_TIMEFRAMES  LowerTF         = {{LOWER_TF}};         // Lower Timeframe (entry)
input int              TrendEMAPeriod  = {{TREND_EMA_PERIOD}};  // Trend EMA Period
input int              StochK          = {{STOCH_K}};           // Stochastic %K
input int              StochD          = {{STOCH_D}};           // Stochastic %D
input int              StochSlowing    = {{STOCH_SLOWING}};     // Stochastic Slowing

// ── EMA Slope Strength ────────────────────────────────────────
input double           EMASlopeThreshold = {{EMA_SLOPE_THRESHOLD}}; // Min EMA Slope (price units, e.g. 0.0005)
input int              EMASlopeBars      = {{EMA_SLOPE_BARS}};      // EMA Slope Lookback Bars (e.g. 3)

// ── Strategy Filters ──────────────────────────────────────────
input int    ADXPeriod        = {{ADX_PERIOD}};              // ADX Period on Higher TF (0=disabled)
input double ADXMinStrength   = {{ADX_MIN_STRENGTH}};        // Min ADX for Entry

// ── ATR Dynamic Stops ─────────────────────────────────────────
input bool   UseATRStops      = {{USE_ATR_STOPS}};           // Use ATR for SL/TP
input int    ATRStopPeriod    = {{ATR_STOP_PERIOD}};         // ATR Period for Stops
input double ATRSLMultiplier  = {{ATR_SL_MULT}};             // ATR SL Multiplier
input double ATRTPMultiplier  = {{ATR_TP_MULT}};             // ATR TP Multiplier

// ── Risk-Based Sizing ─────────────────────────────────────────
input double RiskPercent      = {{RISK_PERCENT}};            // Risk % of Balance (0=use fixed lot)

// ── Trade Management ────────────────────────────────────────────
input double LotSize            = {{LOT_SIZE}};              // Lot Size
input int    StopLossPips        = {{SL_PIPS}};               // Stop Loss (pips)
input int    TakeProfitPips      = {{TP_PIPS}};               // Take Profit (pips)
input int    MaxSpreadPoints     = {{MAX_SPREAD}};            // Max Spread (points)
input int    MagicNumber         = {{MAGIC_NUMBER}};          // Magic Number
input string MultiSymbols        = "{{MULTI_SYMBOLS}}";       // Multi-Asset Symbols (comma-separated, empty=chart symbol only)

// ── Risk Management ─────────────────────────────────────────────
input double MaxDailyLossPercent   = {{MAX_DAILY_LOSS}};      // Max Daily Loss %
input int    ConsecutiveLossLimit  = {{CONSEC_LOSS_LIMIT}};   // Consecutive Loss Limit
input double BreakevenTriggerRR    = {{BE_TRIGGER_RR}};       // Breakeven at R:R
input double TrailingStopPips      = {{TRAILING_STOP}};       // Trailing Stop (pips)
input bool   UseSessionFilter      = {{USE_SESSION_FILTER}};  // Session Filter
input int    SessionStartHour      = {{SESSION_START}};       // Session Start (UTC)
input int    SessionEndHour        = {{SESSION_END}};         // Session End (UTC)

// ── TradeMetrics Integration ────────────────────────────────────
input string AccountID        = "{{ACCOUNT_ID}}";
input string API_Key          = "{{API_KEY}}";
input string API_Secret       = "";                           // API Secret (enter manually)
input string API_Endpoint     = "https://edgerelay-signal-ingestion.ghwmelite.workers.dev";
input string JournalEndpoint  = "https://edgerelay-journal-sync.ghwmelite.workers.dev";
input bool   EnableJournal    = true;                         // Enable Journal Sync

// ── Shared Integration Block ────────────────────────────────────
{{TRADEMETRICS_BLOCK}}

// ── Multi-Asset Support ─────────────────────────────────────────
string g_symbols[];
int    g_symbolCount;
datetime g_lastBarTime[];

void InitSymbols()
{
   if(StringLen(MultiSymbols) == 0)
   {
      g_symbolCount = 1;
      ArrayResize(g_symbols, 1);
      g_symbols[0] = _Symbol;
   }
   else
   {
      string parts[];
      g_symbolCount = StringSplit(MultiSymbols, ',', parts);
      ArrayResize(g_symbols, g_symbolCount);
      for(int i = 0; i < g_symbolCount; i++)
      {
         StringTrimLeft(parts[i]);
         StringTrimRight(parts[i]);
         g_symbols[i] = parts[i];
         SymbolSelect(g_symbols[i], true);
      }
   }
   ArrayResize(g_lastBarTime, g_symbolCount);
   for(int i = 0; i < g_symbolCount; i++)
      g_lastBarTime[i] = 0;
}

int GetSymbolMagic(string symbol)
{
   int hash = MagicNumber;
   for(int i = 0; i < StringLen(symbol); i++)
      hash = ((hash << 5) - hash + StringGetCharacter(symbol, i)) & 0x7FFFFFFF;
   return hash;
}

double GetSymbolPip(string symbol)
{
   int digits = (int)SymbolInfoInteger(symbol, SYMBOL_DIGITS);
   double point = SymbolInfoDouble(symbol, SYMBOL_POINT);
   return point * ((digits == 3 || digits == 5) ? 10 : 1);
}

bool HasPositionFor(string symbol, ENUM_POSITION_TYPE direction, int magic)
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != magic) continue;
      if(PositionGetString(POSITION_SYMBOL) != symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) == direction)
         return true;
   }
   return false;
}

void ClosePositionsFor(string symbol, ENUM_POSITION_TYPE direction, int magic)
{
   CTrade closeTrade;
   closeTrade.SetExpertMagicNumber(magic);
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != magic) continue;
      if(PositionGetString(POSITION_SYMBOL) != symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) != direction) continue;
      double profit = PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);
      if(closeTrade.PositionClose(ticket))
         TM_OnTradeClosed(ticket, profit);
   }
}

bool IsNewBarForSymbol(int symIdx, string symbol)
{
   datetime currentBar = iTime(symbol, LowerTF, 0);
   if(currentBar == g_lastBarTime[symIdx]) return false;
   g_lastBarTime[symIdx] = currentBar;
   return true;
}

// ── Strategy Variables ──────────────────────────────────────────
int      g_trendEMAHandles[];
int      g_stochHandles[];
int      g_adxHandles[];
int      g_atrHandles[];
CTrade   g_trade;

//+------------------------------------------------------------------+
//| Calculate lot size based on risk percentage                       |
//+------------------------------------------------------------------+
double CalculateLotSize(double slPips, string symbol, double symPip)
  {
   if(RiskPercent <= 0 || slPips <= 0) return LotSize;
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskAmount = balance * RiskPercent / 100.0;
   double tickValue = SymbolInfoDouble(symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize = SymbolInfoDouble(symbol, SYMBOL_TRADE_TICK_SIZE);
   if(tickValue <= 0 || tickSize <= 0) return LotSize;
   double lotSize = riskAmount / (slPips * symPip / tickSize * tickValue);
   double minLot = SymbolInfoDouble(symbol, SYMBOL_VOLUME_MIN);
   double maxLot = SymbolInfoDouble(symbol, SYMBOL_VOLUME_MAX);
   double lotStep = SymbolInfoDouble(symbol, SYMBOL_VOLUME_STEP);
   lotSize = MathMax(minLot, MathMin(maxLot, MathFloor(lotSize / lotStep) * lotStep));
   return lotSize;
  }

//+------------------------------------------------------------------+
//| Expert initialization function                                    |
//+------------------------------------------------------------------+
int OnInit()
  {
   InitSymbols();

   ArrayResize(g_trendEMAHandles, g_symbolCount);
   ArrayResize(g_stochHandles, g_symbolCount);
   ArrayResize(g_adxHandles, g_symbolCount);
   ArrayResize(g_atrHandles, g_symbolCount);

   for(int i = 0; i < g_symbolCount; i++)
     {
      g_adxHandles[i] = INVALID_HANDLE;
      g_atrHandles[i] = INVALID_HANDLE;

      g_trendEMAHandles[i] = iMA(g_symbols[i], HigherTF, TrendEMAPeriod, 0, MODE_EMA, PRICE_CLOSE);
      g_stochHandles[i]    = iStochastic(g_symbols[i], LowerTF, StochK, StochD, StochSlowing, MODE_SMA, STO_LOWHIGH);

      if(g_trendEMAHandles[i] == INVALID_HANDLE || g_stochHandles[i] == INVALID_HANDLE)
        {
         PrintFormat("[MultiTFTrend] Failed to create indicator handles for %s. Error: %d", g_symbols[i], GetLastError());
         return INIT_FAILED;
        }

      if(ADXPeriod > 0)
        {
         g_adxHandles[i] = iADX(g_symbols[i], HigherTF, ADXPeriod);
         if(g_adxHandles[i] == INVALID_HANDLE)
           {
            PrintFormat("[MultiTFTrend] Failed to create ADX handle for %s. Error: %d", g_symbols[i], GetLastError());
            return INIT_FAILED;
           }
        }

      if(UseATRStops)
        {
         g_atrHandles[i] = iATR(g_symbols[i], LowerTF, ATRStopPeriod);
         if(g_atrHandles[i] == INVALID_HANDLE)
           {
            PrintFormat("[MultiTFTrend] Failed to create ATR handle for %s. Error: %d", g_symbols[i], GetLastError());
            return INIT_FAILED;
           }
        }
     }

   g_trade.SetExpertMagicNumber(MagicNumber);
   g_trade.SetDeviationInPoints(10);
   g_trade.SetTypeFilling(ORDER_FILLING_IOC);

   return TM_OnInit();
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                  |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   for(int i = 0; i < g_symbolCount; i++)
     {
      if(g_trendEMAHandles[i] != INVALID_HANDLE) IndicatorRelease(g_trendEMAHandles[i]);
      if(g_stochHandles[i] != INVALID_HANDLE) IndicatorRelease(g_stochHandles[i]);
      if(g_adxHandles[i] != INVALID_HANDLE) IndicatorRelease(g_adxHandles[i]);
      if(g_atrHandles[i] != INVALID_HANDLE) IndicatorRelease(g_atrHandles[i]);
     }

   TM_OnDeinit(reason);
  }

//+------------------------------------------------------------------+
//| Timer event handler                                               |
//+------------------------------------------------------------------+
void OnTimer()
  {
   TM_OnTimer();
  }

//+------------------------------------------------------------------+
//| Expert tick function                                              |
//+------------------------------------------------------------------+
void OnTick()
  {
   if(!TM_CanTrade()) return;

   for(int si = 0; si < g_symbolCount; si++)
     {
      string sym = g_symbols[si];
      if(!IsNewBarForSymbol(si, sym)) continue;

      int magic = GetSymbolMagic(sym);
      double symPip = GetSymbolPip(sym);
      double symAsk = SymbolInfoDouble(sym, SYMBOL_ASK);
      double symBid = SymbolInfoDouble(sym, SYMBOL_BID);
      int symDigits = (int)SymbolInfoInteger(sym, SYMBOL_DIGITS);

      //--- Read EMA on Higher TF
      int emaBarsNeeded = EMASlopeBars + 2;
      if(emaBarsNeeded < 5) emaBarsNeeded = 5;

      double ema[];
      ArraySetAsSeries(ema, true);
      if(CopyBuffer(g_trendEMAHandles[si], 0, 0, emaBarsNeeded, ema) < emaBarsNeeded) continue;

      int slopeRef = 1 + EMASlopeBars;
      if(slopeRef >= emaBarsNeeded) slopeRef = emaBarsNeeded - 1;

      double emaSlope = ema[1] - ema[slopeRef];
      bool uptrend   = (emaSlope > 0);
      bool downtrend = (emaSlope < 0);

      if(EMASlopeThreshold > 0 && MathAbs(emaSlope) < EMASlopeThreshold)
        { uptrend = false; downtrend = false; }

      //--- ADX trend strength on Higher TF
      if((uptrend || downtrend) && ADXPeriod > 0 && g_adxHandles[si] != INVALID_HANDLE)
        {
         double adxVal[];
         ArraySetAsSeries(adxVal, true);
         if(CopyBuffer(g_adxHandles[si], 0, 0, 2, adxVal) >= 2)
           { if(adxVal[1] < ADXMinStrength) { uptrend = false; downtrend = false; } }
         else
           { uptrend = false; downtrend = false; }
        }

      if(!uptrend && !downtrend) continue;

      //--- Read Stochastic on Lower TF
      double stochK[];
      double stochD[];
      ArraySetAsSeries(stochK, true);
      ArraySetAsSeries(stochD, true);

      if(CopyBuffer(g_stochHandles[si], 0, 0, 3, stochK) < 3) continue;
      if(CopyBuffer(g_stochHandles[si], 1, 0, 3, stochD) < 3) continue;

      double kCurr = stochK[1];
      double kPrev = stochK[2];
      double dCurr = stochD[1];
      double dPrev = stochD[2];

      bool buySignal  = uptrend && (kPrev <= dPrev && kCurr > dCurr) && (kPrev < 20.0);
      bool sellSignal = downtrend && (kPrev >= dPrev && kCurr < dCurr) && (kPrev > 80.0);

      //--- Read ATR for dynamic stops
      double atrValue = 0.0;
      if(UseATRStops && g_atrHandles[si] != INVALID_HANDLE)
        {
         double atrArr[];
         ArraySetAsSeries(atrArr, true);
         if(CopyBuffer(g_atrHandles[si], 0, 0, 2, atrArr) >= 2)
            atrValue = atrArr[1];
        }

      if(buySignal)
        {
         ClosePositionsFor(sym, POSITION_TYPE_SELL, magic);

         if(!HasPositionFor(sym, POSITION_TYPE_BUY, magic))
           {
            double slDist = 0.0, tpDist = 0.0;
            if(UseATRStops && atrValue > 0)
              { slDist = atrValue * ATRSLMultiplier; tpDist = atrValue * ATRTPMultiplier; }
            else
              { slDist = StopLossPips * symPip; tpDist = TakeProfitPips * symPip; }

            double sl = (slDist > 0) ? NormalizeDouble(symAsk - slDist, symDigits) : 0.0;
            double tp = (tpDist > 0) ? NormalizeDouble(symAsk + tpDist, symDigits) : 0.0;
            double slPips = (slDist > 0) ? slDist / symPip : 0.0;
            double lot = CalculateLotSize(slPips, sym, symPip);

            g_trade.SetExpertMagicNumber(magic);
            if(g_trade.Buy(lot, sym, symAsk, sl, tp, StringFormat("TM:%s|SIG:%s", "MultiTF", "BUY_PULLBACK")))
              {
               ulong ticket = g_trade.ResultOrder();
               if(ticket > 0) TM_OnTradeOpened(ticket, sym, "buy", lot, symAsk, sl, tp);
              }
           }
        }

      if(sellSignal)
        {
         ClosePositionsFor(sym, POSITION_TYPE_BUY, magic);

         if(!HasPositionFor(sym, POSITION_TYPE_SELL, magic))
           {
            double slDist = 0.0, tpDist = 0.0;
            if(UseATRStops && atrValue > 0)
              { slDist = atrValue * ATRSLMultiplier; tpDist = atrValue * ATRTPMultiplier; }
            else
              { slDist = StopLossPips * symPip; tpDist = TakeProfitPips * symPip; }

            double sl = (slDist > 0) ? NormalizeDouble(symBid + slDist, symDigits) : 0.0;
            double tp = (tpDist > 0) ? NormalizeDouble(symBid - tpDist, symDigits) : 0.0;
            double slPips = (slDist > 0) ? slDist / symPip : 0.0;
            double lot = CalculateLotSize(slPips, sym, symPip);

            g_trade.SetExpertMagicNumber(magic);
            if(g_trade.Sell(lot, sym, symBid, sl, tp, StringFormat("TM:%s|SIG:%s", "MultiTF", "SELL_PULLBACK")))
              {
               ulong ticket = g_trade.ResultOrder();
               if(ticket > 0) TM_OnTradeOpened(ticket, sym, "sell", lot, symBid, sl, tp);
              }
           }
        }
     }

   TM_ManageOpenTrades();
  }

//+------------------------------------------------------------------+
//| Check if a position exists in the given direction                 |
//+------------------------------------------------------------------+
bool HasPositionByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) == direction)
         return true;
     }
   return false;
  }

//+------------------------------------------------------------------+
//| Close all positions in the given direction                        |
//+------------------------------------------------------------------+
void ClosePositionsByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) != direction) continue;

      double profit = PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);

      if(g_trade.PositionClose(ticket))
         TM_OnTradeClosed(ticket, profit);
     }
  }
//+------------------------------------------------------------------+
