//+------------------------------------------------------------------+
//| {{STRATEGY_NAME}} EA                                              |
//| Generated by TradeMetrics Pro Strategy Hub                        |
//+------------------------------------------------------------------+
#property copyright "TradeMetrics Pro"
#property version   "1.00"
#property strict

// -- Includes ────────────────────────────────────────────────────
#include <EdgeRelay_Common.mqh>
#include <EdgeRelay_Crypto.mqh>
#include <EdgeRelay_Http.mqh>
#include <EdgeRelay_Queue.mqh>
#include <EdgeRelay_JournalSync.mqh>
#include <EdgeRelay_JournalQueue.mqh>
#include <Trade\Trade.mqh>

// -- Strategy Parameters ─────────────────────────────────────────
input int              ATRPeriod       = {{ATR_PERIOD}};        // ATR Period
input double           ATRMultiplier   = {{ATR_MULTIPLIER}};    // Spike Threshold (x ATR)
input int              SpikeTrailPips  = {{SPIKE_TRAIL}};       // Trailing Stop (pips)
input ENUM_TIMEFRAMES  Timeframe       = {{TIMEFRAME}};         // Timeframe

// -- Trade Management ────────────────────────────────────────────
input double LotSize            = {{LOT_SIZE}};              // Lot Size
input int    StopLossPips        = {{SL_PIPS}};               // Stop Loss (pips)
input int    TakeProfitPips      = {{TP_PIPS}};               // Take Profit (pips)
input int    MaxSpreadPoints     = {{MAX_SPREAD}};            // Max Spread (points)
input int    MagicNumber         = {{MAGIC_NUMBER}};          // Magic Number

// -- Risk Management ─────────────────────────────────────────────
input double MaxDailyLossPercent   = {{MAX_DAILY_LOSS}};      // Max Daily Loss %
input int    ConsecutiveLossLimit  = {{CONSEC_LOSS_LIMIT}};   // Consecutive Loss Limit
input double BreakevenTriggerRR    = {{BE_TRIGGER_RR}};       // Breakeven at R:R
input double TrailingStopPips      = {{TRAILING_STOP}};       // Trailing Stop (pips)
input bool   UseSessionFilter      = {{USE_SESSION_FILTER}};  // Session Filter
input int    SessionStartHour      = {{SESSION_START}};       // Session Start (UTC)
input int    SessionEndHour        = {{SESSION_END}};         // Session End (UTC)

// -- TradeMetrics Integration ────────────────────────────────────
input string AccountID        = "{{ACCOUNT_ID}}";
input string API_Key          = "{{API_KEY}}";
input string API_Secret       = "";                           // API Secret (enter manually)
input string API_Endpoint     = "https://edgerelay-signal-ingestion.ghwmelite.workers.dev";
input string JournalEndpoint  = "https://edgerelay-journal-sync.ghwmelite.workers.dev";
input bool   EnableJournal    = true;                         // Enable Journal Sync

// -- Shared Integration Block ────────────────────────────────────
{{TRADEMETRICS_BLOCK}}

// -- Strategy Variables ──────────────────────────────────────────
int      g_atrHandle    = INVALID_HANDLE;
int      g_cooldownBars = 0;
CTrade   g_trade;

//+------------------------------------------------------------------+
//| Expert initialization function                                    |
//+------------------------------------------------------------------+
int OnInit()
  {
   //--- Create ATR handle
   g_atrHandle = iATR(_Symbol, Timeframe, ATRPeriod);

   if(g_atrHandle == INVALID_HANDLE)
     {
      PrintFormat("[NewsSpike] Failed to create ATR handle. Error: %d", GetLastError());
      return INIT_FAILED;
     }

   //--- Configure trade object
   g_trade.SetExpertMagicNumber(MagicNumber);
   g_trade.SetDeviationInPoints(10);
   g_trade.SetTypeFilling(ORDER_FILLING_IOC);

   //--- Initialize TradeMetrics integration
   return TM_OnInit();
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                  |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   //--- Release indicator handles
   if(g_atrHandle != INVALID_HANDLE)
      IndicatorRelease(g_atrHandle);

   TM_OnDeinit(reason);
  }

//+------------------------------------------------------------------+
//| Timer event handler                                               |
//+------------------------------------------------------------------+
void OnTimer()
  {
   TM_OnTimer();
  }

//+------------------------------------------------------------------+
//| Expert tick function                                              |
//+------------------------------------------------------------------+
void OnTick()
  {
   if(!TM_IsNewBar()) return;
   if(!TM_CanTrade()) return;

   //--- Decrement cooldown
   if(g_cooldownBars > 0)
     {
      g_cooldownBars--;
      TM_ManageOpenTrades();
      return;
     }

   //--- Read ATR values
   double atr[];
   ArraySetAsSeries(atr, true);
   if(CopyBuffer(g_atrHandle, 0, 0, 3, atr) < 3) return;

   //--- Calculate bar 1 range
   double high1  = iHigh(_Symbol, Timeframe, 1);
   double low1   = iLow(_Symbol, Timeframe, 1);
   double open1  = iOpen(_Symbol, Timeframe, 1);
   double close1 = iClose(_Symbol, Timeframe, 1);
   double range1 = high1 - low1;

   //--- Use ATR from bar 2 (before the spike) for comparison
   double atrVal = atr[2];
   if(atrVal <= 0.0) { TM_ManageOpenTrades(); return; }

   //--- Check for spike: bar range exceeds ATR threshold
   bool spikeDetected = (range1 > ATRMultiplier * atrVal);
   if(!spikeDetected) { TM_ManageOpenTrades(); return; }

   //--- Determine spike direction
   bool bullishSpike = (close1 > open1);
   bool bearishSpike = (close1 < open1);

   double pip = _Point * ((_Digits == 3 || _Digits == 5) ? 10 : 1);
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

   //--- SL = half the spike candle range
   double spikeSLDist = range1 / 2.0;

   //--- BUY on bullish spike
   if(bullishSpike)
     {
      ClosePositionsByDirection(POSITION_TYPE_SELL);

      if(!HasPositionByDirection(POSITION_TYPE_BUY))
        {
         double sl = NormalizeDouble(ask - spikeSLDist, _Digits);
         double tp = (TakeProfitPips > 0) ? NormalizeDouble(ask + TakeProfitPips * pip, _Digits) : 0.0;

         //--- Override SL if user-defined is tighter
         if(StopLossPips > 0)
           {
            double userSl = NormalizeDouble(ask - StopLossPips * pip, _Digits);
            if(userSl > sl) sl = userSl;
           }

         if(g_trade.Buy(LotSize, _Symbol, ask, sl, tp, "NewsSpike"))
           {
            ulong ticket = g_trade.ResultOrder();
            if(ticket > 0)
              {
               TM_OnTradeOpened(ticket, _Symbol, "buy", LotSize, ask, sl, tp);
               g_cooldownBars = 3;
              }
           }
        }
     }

   //--- SELL on bearish spike
   if(bearishSpike)
     {
      ClosePositionsByDirection(POSITION_TYPE_BUY);

      if(!HasPositionByDirection(POSITION_TYPE_SELL))
        {
         double sl = NormalizeDouble(bid + spikeSLDist, _Digits);
         double tp = (TakeProfitPips > 0) ? NormalizeDouble(bid - TakeProfitPips * pip, _Digits) : 0.0;

         //--- Override SL if user-defined is tighter
         if(StopLossPips > 0)
           {
            double userSl = NormalizeDouble(bid + StopLossPips * pip, _Digits);
            if(userSl < sl) sl = userSl;
           }

         if(g_trade.Sell(LotSize, _Symbol, bid, sl, tp, "NewsSpike"))
           {
            ulong ticket = g_trade.ResultOrder();
            if(ticket > 0)
              {
               TM_OnTradeOpened(ticket, _Symbol, "sell", LotSize, bid, sl, tp);
               g_cooldownBars = 3;
              }
           }
        }
     }

   TM_ManageOpenTrades();
  }

//+------------------------------------------------------------------+
//| Check if a position exists in the given direction                 |
//+------------------------------------------------------------------+
bool HasPositionByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) == direction)
         return true;
     }
   return false;
  }

//+------------------------------------------------------------------+
//| Close all positions in the given direction                        |
//+------------------------------------------------------------------+
void ClosePositionsByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) != direction) continue;

      double profit = PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);

      if(g_trade.PositionClose(ticket))
         TM_OnTradeClosed(ticket, profit);
     }
  }
//+------------------------------------------------------------------+
