//+------------------------------------------------------------------+
//| {{STRATEGY_NAME}} EA                                              |
//| Generated by TradeMetrics Pro Strategy Hub                        |
//+------------------------------------------------------------------+
#property copyright "TradeMetrics Pro"
#property version   "1.00"
#property strict

// ── Includes ────────────────────────────────────────────────────
#include <EdgeRelay_Common.mqh>
#include <EdgeRelay_Crypto.mqh>
#include <EdgeRelay_Http.mqh>
#include <EdgeRelay_Queue.mqh>
#include <EdgeRelay_JournalSync.mqh>
#include <EdgeRelay_JournalQueue.mqh>
#include <Trade\Trade.mqh>

// ── Strategy Parameters ─────────────────────────────────────────
input int              ATRPeriod       = {{ATR_PERIOD}};        // ATR Period
input double           ATRMultiplier   = {{ATR_MULTIPLIER}};    // Spike Threshold (x ATR)
input int              SpikeTrailPips  = {{SPIKE_TRAIL}};       // Trailing Stop (pips)
input int              CooldownBars    = {{COOLDOWN_BARS}};     // Cooldown Bars After Entry
input double           MomentumPct     = {{MOMENTUM_PCT}};      // Min Close Near H/L % (e.g. 70)
input ENUM_TIMEFRAMES  Timeframe       = {{TIMEFRAME}};         // Timeframe

// ── Strategy Filters ──────────────────────────────────────────
input int    ADXPeriod        = {{ADX_PERIOD}};                 // ADX Period (0=disabled)
input double ADXMinStrength   = {{ADX_MIN_STRENGTH}};           // Min ADX for Entry (confirms trend)

// ── ATR Dynamic Stops ─────────────────────────────────────────
input bool   UseATRStops      = {{USE_ATR_STOPS}};              // Use ATR for SL/TP
input int    ATRStopPeriod    = {{ATR_STOP_PERIOD}};            // ATR Period for Stops
input double ATRSLMultiplier  = {{ATR_SL_MULT}};                // ATR SL Multiplier
input double ATRTPMultiplier  = {{ATR_TP_MULT}};                // ATR TP Multiplier

// ── Risk-Based Sizing ─────────────────────────────────────────
input double RiskPercent      = {{RISK_PERCENT}};               // Risk % of Balance (0=use fixed lot)

// ── Trade Management ────────────────────────────────────────────
input double LotSize            = {{LOT_SIZE}};              // Lot Size
input int    StopLossPips        = {{SL_PIPS}};               // Stop Loss (pips)
input int    TakeProfitPips      = {{TP_PIPS}};               // Take Profit (pips)
input int    MaxSpreadPoints     = {{MAX_SPREAD}};            // Max Spread (points)
input int    MagicNumber         = {{MAGIC_NUMBER}};          // Magic Number
input string MultiSymbols        = "{{MULTI_SYMBOLS}}";       // Multi-Asset Symbols (comma-separated, empty=chart symbol only)

// ── Risk Management ─────────────────────────────────────────────
input double MaxDailyLossPercent   = {{MAX_DAILY_LOSS}};      // Max Daily Loss %
input int    ConsecutiveLossLimit  = {{CONSEC_LOSS_LIMIT}};   // Consecutive Loss Limit
input double BreakevenTriggerRR    = {{BE_TRIGGER_RR}};       // Breakeven at R:R
input double TrailingStopPips      = {{TRAILING_STOP}};       // Trailing Stop (pips)
input bool   UseSessionFilter      = {{USE_SESSION_FILTER}};  // Session Filter
input int    SessionStartHour      = {{SESSION_START}};       // Session Start (UTC)
input int    SessionEndHour        = {{SESSION_END}};         // Session End (UTC)

// ── TradeMetrics Integration ────────────────────────────────────
input string AccountID        = "{{ACCOUNT_ID}}";
input string API_Key          = "{{API_KEY}}";
input string API_Secret       = "";                           // API Secret (enter manually)
input string API_Endpoint     = "https://edgerelay-signal-ingestion.ghwmelite.workers.dev";
input string JournalEndpoint  = "https://edgerelay-journal-sync.ghwmelite.workers.dev";
input bool   EnableJournal    = true;                         // Enable Journal Sync

// ── Shared Integration Block ────────────────────────────────────
{{TRADEMETRICS_BLOCK}}

// ── Multi-Asset Support ─────────────────────────────────────────
string g_symbols[];
int    g_symbolCount;
datetime g_lastBarTime[];

void InitSymbols()
{
   if(StringLen(MultiSymbols) == 0)
   { g_symbolCount = 1; ArrayResize(g_symbols, 1); g_symbols[0] = _Symbol; }
   else
   {
      string parts[];
      g_symbolCount = StringSplit(MultiSymbols, ',', parts);
      ArrayResize(g_symbols, g_symbolCount);
      for(int i = 0; i < g_symbolCount; i++)
      { StringTrimLeft(parts[i]); StringTrimRight(parts[i]); g_symbols[i] = parts[i]; SymbolSelect(g_symbols[i], true); }
   }
   ArrayResize(g_lastBarTime, g_symbolCount);
   for(int i = 0; i < g_symbolCount; i++) g_lastBarTime[i] = 0;
}

int GetSymbolMagic(string symbol)
{ int hash = MagicNumber; for(int i = 0; i < StringLen(symbol); i++) hash = ((hash << 5) - hash + StringGetCharacter(symbol, i)) & 0x7FFFFFFF; return hash; }

double GetSymbolPip(string symbol)
{ int digits = (int)SymbolInfoInteger(symbol, SYMBOL_DIGITS); double point = SymbolInfoDouble(symbol, SYMBOL_POINT); return point * ((digits == 3 || digits == 5) ? 10 : 1); }

bool HasPositionFor(string symbol, ENUM_POSITION_TYPE direction, int magic)
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   { ulong ticket = PositionGetTicket(i); if(ticket == 0) continue; if(PositionGetInteger(POSITION_MAGIC) != magic) continue;
     if(PositionGetString(POSITION_SYMBOL) != symbol) continue; if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) == direction) return true; }
   return false;
}

void ClosePositionsFor(string symbol, ENUM_POSITION_TYPE direction, int magic)
{
   CTrade closeTrade; closeTrade.SetExpertMagicNumber(magic);
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   { ulong ticket = PositionGetTicket(i); if(ticket == 0) continue; if(PositionGetInteger(POSITION_MAGIC) != magic) continue;
     if(PositionGetString(POSITION_SYMBOL) != symbol) continue; if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) != direction) continue;
     double profit = PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);
     if(closeTrade.PositionClose(ticket)) TM_OnTradeClosed(ticket, profit); }
}

bool IsNewBarForSymbol(int symIdx, string symbol)
{ datetime currentBar = iTime(symbol, Timeframe, 0); if(currentBar == g_lastBarTime[symIdx]) return false; g_lastBarTime[symIdx] = currentBar; return true; }

// ── Strategy Variables ──────────────────────────────────────────
int      g_atrHandles[];
int      g_atrStopHandles[];
int      g_adxHandles[];
int      g_cooldownBars[];
CTrade   g_trade;

//+------------------------------------------------------------------+
//| Calculate lot size based on risk percentage                       |
//+------------------------------------------------------------------+
double CalculateLotSize(double slPips, string symbol, double symPip)
  {
   if(RiskPercent <= 0 || slPips <= 0) return LotSize;
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskAmount = balance * RiskPercent / 100.0;
   double tickValue = SymbolInfoDouble(symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize = SymbolInfoDouble(symbol, SYMBOL_TRADE_TICK_SIZE);
   if(tickValue <= 0 || tickSize <= 0) return LotSize;
   double lotSize = riskAmount / (slPips * symPip / tickSize * tickValue);
   double minLot = SymbolInfoDouble(symbol, SYMBOL_VOLUME_MIN);
   double maxLot = SymbolInfoDouble(symbol, SYMBOL_VOLUME_MAX);
   double lotStep = SymbolInfoDouble(symbol, SYMBOL_VOLUME_STEP);
   lotSize = MathMax(minLot, MathMin(maxLot, MathFloor(lotSize / lotStep) * lotStep));
   return lotSize;
  }

int OnInit()
  {
   InitSymbols();
   ArrayResize(g_atrHandles, g_symbolCount); ArrayResize(g_atrStopHandles, g_symbolCount);
   ArrayResize(g_adxHandles, g_symbolCount); ArrayResize(g_cooldownBars, g_symbolCount);

   for(int i = 0; i < g_symbolCount; i++)
     {
      g_adxHandles[i] = INVALID_HANDLE; g_atrStopHandles[i] = INVALID_HANDLE;
      g_cooldownBars[i] = 0;

      g_atrHandles[i] = iATR(g_symbols[i], Timeframe, ATRPeriod);
      if(g_atrHandles[i] == INVALID_HANDLE)
        { PrintFormat("[NewsSpike] Failed ATR for %s. Error: %d", g_symbols[i], GetLastError()); return INIT_FAILED; }

      if(ADXPeriod > 0)
        { g_adxHandles[i] = iADX(g_symbols[i], Timeframe, ADXPeriod); if(g_adxHandles[i] == INVALID_HANDLE) { PrintFormat("[NewsSpike] Failed ADX for %s", g_symbols[i]); return INIT_FAILED; } }

      if(UseATRStops)
        {
         if(ATRStopPeriod == ATRPeriod) g_atrStopHandles[i] = g_atrHandles[i];
         else { g_atrStopHandles[i] = iATR(g_symbols[i], Timeframe, ATRStopPeriod); if(g_atrStopHandles[i] == INVALID_HANDLE) { PrintFormat("[NewsSpike] Failed ATR stop for %s", g_symbols[i]); return INIT_FAILED; } }
        }
     }

   g_trade.SetExpertMagicNumber(MagicNumber); g_trade.SetDeviationInPoints(10); g_trade.SetTypeFilling(ORDER_FILLING_IOC);
   return TM_OnInit();
  }

void OnDeinit(const int reason)
  {
   for(int i = 0; i < g_symbolCount; i++)
     {
      if(g_atrHandles[i] != INVALID_HANDLE) IndicatorRelease(g_atrHandles[i]);
      if(g_atrStopHandles[i] != INVALID_HANDLE && g_atrStopHandles[i] != g_atrHandles[i]) IndicatorRelease(g_atrStopHandles[i]);
      if(g_adxHandles[i] != INVALID_HANDLE) IndicatorRelease(g_adxHandles[i]);
     }
   TM_OnDeinit(reason);
  }

//+------------------------------------------------------------------+
//| Timer event handler                                               |
//+------------------------------------------------------------------+
void OnTimer()
  {
   TM_OnTimer();
  }

//+------------------------------------------------------------------+
//| Expert tick function                                              |
//+------------------------------------------------------------------+
void OnTick()
  {
   if(!TM_CanTrade()) return;

   for(int si = 0; si < g_symbolCount; si++)
     {
      string sym = g_symbols[si];
      if(!IsNewBarForSymbol(si, sym)) continue;

      int magic = GetSymbolMagic(sym);
      double symPip = GetSymbolPip(sym);
      double symAsk = SymbolInfoDouble(sym, SYMBOL_ASK);
      double symBid = SymbolInfoDouble(sym, SYMBOL_BID);
      int symDigits = (int)SymbolInfoInteger(sym, SYMBOL_DIGITS);

      if(g_cooldownBars[si] > 0) { g_cooldownBars[si]--; continue; }

      double atr[]; ArraySetAsSeries(atr, true);
      if(CopyBuffer(g_atrHandles[si], 0, 0, 3, atr) < 3) continue;

      double high1  = iHigh(sym, Timeframe, 1);
      double low1   = iLow(sym, Timeframe, 1);
      double open1  = iOpen(sym, Timeframe, 1);
      double close1 = iClose(sym, Timeframe, 1);
      double range1 = high1 - low1;

      double atrVal = atr[2];
      if(atrVal <= 0.0) continue;
      if(range1 <= ATRMultiplier * atrVal) continue;

      bool bullishSpike = (close1 > open1);
      bool bearishSpike = (close1 < open1);

      if(bullishSpike && range1 > 0)
        { double closeNearHigh = (close1 - low1) / range1 * 100.0; if(closeNearHigh < MomentumPct) bullishSpike = false; }
      if(bearishSpike && range1 > 0)
        { double closeNearLow = (high1 - close1) / range1 * 100.0; if(closeNearLow < MomentumPct) bearishSpike = false; }

      if(!bullishSpike && !bearishSpike) continue;

      if(ADXPeriod > 0 && g_adxHandles[si] != INVALID_HANDLE)
        {
         double adxVal[]; ArraySetAsSeries(adxVal, true);
         if(CopyBuffer(g_adxHandles[si], 0, 0, 2, adxVal) >= 2)
           { if(adxVal[1] < ADXMinStrength) { bullishSpike = false; bearishSpike = false; } }
         else { bullishSpike = false; bearishSpike = false; }
        }

      if(!bullishSpike && !bearishSpike) continue;

      double atrStopValue = 0.0;
      if(UseATRStops && g_atrStopHandles[si] != INVALID_HANDLE)
        { double atrArr[]; ArraySetAsSeries(atrArr, true); if(CopyBuffer(g_atrStopHandles[si], 0, 0, 2, atrArr) >= 2) atrStopValue = atrArr[1]; }

      double spikeSLDist = range1 / 2.0;

      g_trade.SetExpertMagicNumber(magic);

      if(bullishSpike)
        {
         ClosePositionsFor(sym, POSITION_TYPE_SELL, magic);
         if(!HasPositionFor(sym, POSITION_TYPE_BUY, magic))
           {
            double slDist = 0.0, tpDist = 0.0;
            if(UseATRStops && atrStopValue > 0) { slDist = atrStopValue * ATRSLMultiplier; tpDist = atrStopValue * ATRTPMultiplier; }
            else { slDist = spikeSLDist; tpDist = (TakeProfitPips > 0) ? TakeProfitPips * symPip : spikeSLDist * 2.0;
                   if(StopLossPips > 0) { double userSlDist = StopLossPips * symPip; if(userSlDist < slDist) slDist = userSlDist; } }

            double sl = (slDist > 0) ? NormalizeDouble(symAsk - slDist, symDigits) : 0.0;
            double tp = (tpDist > 0) ? NormalizeDouble(symAsk + tpDist, symDigits) : 0.0;
            double slPips = (slDist > 0) ? slDist / symPip : 0.0;
            double lot = CalculateLotSize(slPips, sym, symPip);

            if(g_trade.Buy(lot, sym, symAsk, sl, tp, StringFormat("TM:%s|SIG:%s", "NewsSpike", "BUY_SPIKE")))
              { ulong ticket = g_trade.ResultOrder(); if(ticket > 0) { TM_OnTradeOpened(ticket, sym, "buy", lot, symAsk, sl, tp); g_cooldownBars[si] = CooldownBars; } }
           }
        }

      if(bearishSpike)
        {
         ClosePositionsFor(sym, POSITION_TYPE_BUY, magic);
         if(!HasPositionFor(sym, POSITION_TYPE_SELL, magic))
           {
            double slDist = 0.0, tpDist = 0.0;
            if(UseATRStops && atrStopValue > 0) { slDist = atrStopValue * ATRSLMultiplier; tpDist = atrStopValue * ATRTPMultiplier; }
            else { slDist = spikeSLDist; tpDist = (TakeProfitPips > 0) ? TakeProfitPips * symPip : spikeSLDist * 2.0;
                   if(StopLossPips > 0) { double userSlDist = StopLossPips * symPip; if(userSlDist < slDist) slDist = userSlDist; } }

            double sl = (slDist > 0) ? NormalizeDouble(symBid + slDist, symDigits) : 0.0;
            double tp = (tpDist > 0) ? NormalizeDouble(symBid - tpDist, symDigits) : 0.0;
            double slPips = (slDist > 0) ? slDist / symPip : 0.0;
            double lot = CalculateLotSize(slPips, sym, symPip);

            if(g_trade.Sell(lot, sym, symBid, sl, tp, StringFormat("TM:%s|SIG:%s", "NewsSpike", "SELL_SPIKE")))
              { ulong ticket = g_trade.ResultOrder(); if(ticket > 0) { TM_OnTradeOpened(ticket, sym, "sell", lot, symBid, sl, tp); g_cooldownBars[si] = CooldownBars; } }
           }
        }
     }

   TM_ManageOpenTrades();
  }

//+------------------------------------------------------------------+
//| Check if a position exists in the given direction                 |
//+------------------------------------------------------------------+
bool HasPositionByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) == direction)
         return true;
     }
   return false;
  }

//+------------------------------------------------------------------+
//| Close all positions in the given direction                        |
//+------------------------------------------------------------------+
void ClosePositionsByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) != direction) continue;

      double profit = PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);

      if(g_trade.PositionClose(ticket))
         TM_OnTradeClosed(ticket, profit);
     }
  }
//+------------------------------------------------------------------+
