//+------------------------------------------------------------------+
//| {{STRATEGY_NAME}} EA                                              |
//| Generated by TradeMetrics Pro Strategy Hub                        |
//+------------------------------------------------------------------+
#property copyright "TradeMetrics Pro"
#property version   "1.00"
#property strict

// ── Includes ────────────────────────────────────────────────────
#include <EdgeRelay_Common.mqh>
#include <EdgeRelay_Crypto.mqh>
#include <EdgeRelay_Http.mqh>
#include <EdgeRelay_Queue.mqh>
#include <EdgeRelay_JournalSync.mqh>
#include <EdgeRelay_JournalQueue.mqh>
#include <Trade\Trade.mqh>

// ── Strategy Parameters ─────────────────────────────────────────
input int              RSIPeriod      = {{RSI_PERIOD}};        // RSI Period
input int              RSIOverbought  = {{RSI_OVERBOUGHT}};    // Overbought Level
input int              RSIOversold    = {{RSI_OVERSOLD}};      // Oversold Level
input ENUM_TIMEFRAMES  Timeframe      = {{TIMEFRAME}};         // Timeframe

// ── Bollinger Band Confluence ─────────────────────────────────
input int              BBPeriod       = {{BB_PERIOD}};         // Bollinger Band Period
input double           BBDeviation    = {{BB_DEVIATION}};      // Bollinger Band Deviation
input bool             RequireBBConfluence = {{REQUIRE_BB_CONFLUENCE}}; // Require BB Confluence

// ── Trend Filter ──────────────────────────────────────────────
input int              TrendMAPeriod  = {{TREND_MA_PERIOD}};   // Trend MA Period (0=disabled, e.g. 200)
input double           TrendMABuffer  = {{TREND_MA_BUFFER}};   // Trend MA Buffer in ATR units (e.g. 1.0)

// ── Strategy Filters ──────────────────────────────────────────
input int    ADXPeriod        = {{ADX_PERIOD}};              // ADX Period (0=disabled)
input double ADXMinStrength   = {{ADX_MIN_STRENGTH}};        // Min ADX for Entry

// ── ATR Dynamic Stops ─────────────────────────────────────────
input bool   UseATRStops      = {{USE_ATR_STOPS}};           // Use ATR for SL/TP
input int    ATRStopPeriod    = {{ATR_STOP_PERIOD}};         // ATR Period for Stops
input double ATRSLMultiplier  = {{ATR_SL_MULT}};             // ATR SL Multiplier
input double ATRTPMultiplier  = {{ATR_TP_MULT}};             // ATR TP Multiplier

// ── Risk-Based Sizing ─────────────────────────────────────────
input double RiskPercent      = {{RISK_PERCENT}};            // Risk % of Balance (0=use fixed lot)

// ── Trade Management ────────────────────────────────────────────
input double LotSize            = {{LOT_SIZE}};              // Lot Size
input int    StopLossPips        = {{SL_PIPS}};               // Stop Loss (pips)
input int    TakeProfitPips      = {{TP_PIPS}};               // Take Profit (pips)
input int    MaxSpreadPoints     = {{MAX_SPREAD}};            // Max Spread (points)
input int    MagicNumber         = {{MAGIC_NUMBER}};          // Magic Number

// ── Risk Management ─────────────────────────────────────────────
input double MaxDailyLossPercent   = {{MAX_DAILY_LOSS}};      // Max Daily Loss %
input int    ConsecutiveLossLimit  = {{CONSEC_LOSS_LIMIT}};   // Consecutive Loss Limit
input double BreakevenTriggerRR    = {{BE_TRIGGER_RR}};       // Breakeven at R:R
input double TrailingStopPips      = {{TRAILING_STOP}};       // Trailing Stop (pips)
input bool   UseSessionFilter      = {{USE_SESSION_FILTER}};  // Session Filter
input int    SessionStartHour      = {{SESSION_START}};       // Session Start (UTC)
input int    SessionEndHour        = {{SESSION_END}};         // Session End (UTC)

// ── TradeMetrics Integration ────────────────────────────────────
input string AccountID        = "{{ACCOUNT_ID}}";
input string API_Key          = "{{API_KEY}}";
input string API_Secret       = "";                           // API Secret (enter manually)
input string API_Endpoint     = "https://edgerelay-signal-ingestion.ghwmelite.workers.dev";
input string JournalEndpoint  = "https://edgerelay-journal-sync.ghwmelite.workers.dev";
input bool   EnableJournal    = true;                         // Enable Journal Sync

// ── Shared Integration Block ────────────────────────────────────
{{TRADEMETRICS_BLOCK}}

// ── Strategy Variables ──────────────────────────────────────────
int      g_rsiHandle    = INVALID_HANDLE;
int      g_bbHandle     = INVALID_HANDLE;
int      g_trendMAHandle = INVALID_HANDLE;
int      g_adxHandle    = INVALID_HANDLE;
int      g_atrHandle    = INVALID_HANDLE;
double   g_rsiPrev      = 0.0;
CTrade   g_trade;

//+------------------------------------------------------------------+
//| Calculate lot size based on risk percentage                       |
//+------------------------------------------------------------------+
double CalculateLotSize(double slPips)
  {
   if(RiskPercent <= 0 || slPips <= 0) return LotSize;
   double pip = _Point * ((_Digits == 3 || _Digits == 5) ? 10 : 1);
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskAmount = balance * RiskPercent / 100.0;
   double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   if(tickValue <= 0 || tickSize <= 0) return LotSize;
   double lotSize = riskAmount / (slPips * pip / tickSize * tickValue);
   double minLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   lotSize = MathMax(minLot, MathMin(maxLot, MathFloor(lotSize / lotStep) * lotStep));
   return lotSize;
  }

//+------------------------------------------------------------------+
//| Expert initialization function                                    |
//+------------------------------------------------------------------+
int OnInit()
  {
   //--- Create RSI handle
   g_rsiHandle = iRSI(_Symbol, Timeframe, RSIPeriod, PRICE_CLOSE);

   if(g_rsiHandle == INVALID_HANDLE)
     {
      PrintFormat("[RSIMeanReversion] Failed to create RSI handle. Error: %d", GetLastError());
      return INIT_FAILED;
     }

   //--- Bollinger Bands handle
   if(RequireBBConfluence)
     {
      g_bbHandle = iBands(_Symbol, Timeframe, BBPeriod, 0, BBDeviation, PRICE_CLOSE);
      if(g_bbHandle == INVALID_HANDLE)
        {
         PrintFormat("[RSIMeanReversion] Failed to create BB handle. Error: %d", GetLastError());
         return INIT_FAILED;
        }
     }

   //--- Trend MA filter handle
   if(TrendMAPeriod > 0)
     {
      g_trendMAHandle = iMA(_Symbol, Timeframe, TrendMAPeriod, 0, MODE_EMA, PRICE_CLOSE);
      if(g_trendMAHandle == INVALID_HANDLE)
        {
         PrintFormat("[RSIMeanReversion] Failed to create Trend MA handle. Error: %d", GetLastError());
         return INIT_FAILED;
        }
     }

   //--- ADX filter handle
   if(ADXPeriod > 0)
     {
      g_adxHandle = iADX(_Symbol, Timeframe, ADXPeriod);
      if(g_adxHandle == INVALID_HANDLE)
        {
         PrintFormat("[RSIMeanReversion] Failed to create ADX handle. Error: %d", GetLastError());
         return INIT_FAILED;
        }
     }

   //--- ATR handle for dynamic stops
   if(UseATRStops)
     {
      g_atrHandle = iATR(_Symbol, Timeframe, ATRStopPeriod);
      if(g_atrHandle == INVALID_HANDLE)
        {
         PrintFormat("[RSIMeanReversion] Failed to create ATR handle. Error: %d", GetLastError());
         return INIT_FAILED;
        }
     }

   //--- Configure trade object
   g_trade.SetExpertMagicNumber(MagicNumber);
   g_trade.SetDeviationInPoints(10);
   g_trade.SetTypeFilling(ORDER_FILLING_IOC);

   //--- Reset previous RSI
   g_rsiPrev = 0.0;

   //--- Initialize TradeMetrics integration
   return TM_OnInit();
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                  |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   //--- Release indicator handles
   if(g_rsiHandle != INVALID_HANDLE)
      IndicatorRelease(g_rsiHandle);
   if(g_bbHandle != INVALID_HANDLE)
      IndicatorRelease(g_bbHandle);
   if(g_trendMAHandle != INVALID_HANDLE)
      IndicatorRelease(g_trendMAHandle);
   if(g_adxHandle != INVALID_HANDLE)
      IndicatorRelease(g_adxHandle);
   if(g_atrHandle != INVALID_HANDLE)
      IndicatorRelease(g_atrHandle);

   TM_OnDeinit(reason);
  }

//+------------------------------------------------------------------+
//| Timer event handler                                               |
//+------------------------------------------------------------------+
void OnTimer()
  {
   TM_OnTimer();
  }

//+------------------------------------------------------------------+
//| Expert tick function                                              |
//+------------------------------------------------------------------+
void OnTick()
  {
   if(!TM_IsNewBar()) return;
   if(!TM_CanTrade()) return;

   //--- Read RSI value for last closed bar
   double rsi[];
   ArraySetAsSeries(rsi, true);

   if(CopyBuffer(g_rsiHandle, 0, 0, 2, rsi) < 2) return;

   double rsiCurr = rsi[1];   // Last closed bar
   double rsiPrev = g_rsiPrev;
   g_rsiPrev = rsiCurr;

   //--- Skip first bar (no previous value yet)
   if(rsiPrev == 0.0) return;

   //--- Calculate pip value for SL/TP
   double pip = _Point * ((_Digits == 3 || _Digits == 5) ? 10 : 1);
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

   //--- Read ATR for dynamic stops and trend filter buffer
   double atrValue = 0.0;
   if((UseATRStops || TrendMAPeriod > 0) && g_atrHandle != INVALID_HANDLE)
     {
      double atrArr[];
      ArraySetAsSeries(atrArr, true);
      if(CopyBuffer(g_atrHandle, 0, 0, 2, atrArr) >= 2)
         atrValue = atrArr[1];
     }
   //--- If ATR handle not created for trend filter but we need it, create a temp read
   if(TrendMAPeriod > 0 && atrValue == 0.0 && g_atrHandle == INVALID_HANDLE)
     {
      //--- Use a simple fallback: no buffer applied
      atrValue = 0.0;
     }

   //--- Exit logic: close BUY positions when RSI crosses above 50 (mean reversion complete)
   if(rsiPrev <= 50.0 && rsiCurr > 50.0)
      ClosePositionsByDirection(POSITION_TYPE_BUY);

   //--- Exit logic: close SELL positions when RSI crosses below 50 (mean reversion complete)
   if(rsiPrev >= 50.0 && rsiCurr < 50.0)
      ClosePositionsByDirection(POSITION_TYPE_SELL);

   //--- Read Bollinger Band values if confluence required
   double bbUpper = 0.0;
   double bbLower = 0.0;
   if(RequireBBConfluence && g_bbHandle != INVALID_HANDLE)
     {
      double bbUpperArr[];
      double bbLowerArr[];
      ArraySetAsSeries(bbUpperArr, true);
      ArraySetAsSeries(bbLowerArr, true);
      if(CopyBuffer(g_bbHandle, 1, 0, 2, bbUpperArr) < 2) return;  // Buffer 1 = upper
      if(CopyBuffer(g_bbHandle, 2, 0, 2, bbLowerArr) < 2) return;  // Buffer 2 = lower
      bbUpper = bbUpperArr[1];
      bbLower = bbLowerArr[1];
     }

   //--- Read close price for BB and trend filter checks
   double closeArr[];
   ArraySetAsSeries(closeArr, true);
   if(CopyClose(_Symbol, Timeframe, 1, 1, closeArr) < 1) return;
   double lastClose = closeArr[0];

   //--- Read trend MA if enabled
   double trendMAValue = 0.0;
   if(TrendMAPeriod > 0 && g_trendMAHandle != INVALID_HANDLE)
     {
      double trendMA[];
      ArraySetAsSeries(trendMA, true);
      if(CopyBuffer(g_trendMAHandle, 0, 0, 2, trendMA) >= 2)
         trendMAValue = trendMA[1];
     }

   //--- ADX filter: if enabled, read ADX to skip when trend is too strong for mean reversion
   bool adxBlocked = false;
   if(ADXPeriod > 0 && g_adxHandle != INVALID_HANDLE)
     {
      double adxVal[];
      ArraySetAsSeries(adxVal, true);
      if(CopyBuffer(g_adxHandle, 0, 0, 2, adxVal) >= 2)
        {
         //--- For mean reversion: skip if ADX is ABOVE threshold (too trendy)
         if(adxVal[1] > ADXMinStrength)
            adxBlocked = true;
        }
     }

   //--- Entry: BUY when RSI is oversold (and no existing BUY position)
   if(rsiCurr < RSIOversold && !HasPositionByDirection(POSITION_TYPE_BUY))
     {
      //--- ADX filter: skip if market is trending too hard
      if(!adxBlocked)
        {
         //--- BB confluence: price must be at or below lower band
         bool bbOk = true;
         if(RequireBBConfluence && bbLower > 0)
           {
            if(lastClose > bbLower)
               bbOk = false;
           }

         //--- Trend filter: don't buy if price is far below 200 EMA (strong downtrend)
         bool trendOk = true;
         if(TrendMAPeriod > 0 && trendMAValue > 0)
           {
            double trendBuffer = TrendMABuffer * atrValue;
            if(lastClose < trendMAValue - trendBuffer)
               trendOk = false;  // Price too far below EMA — strong downtrend, don't fade
           }

         if(bbOk && trendOk)
           {
            double slDist = 0.0;
            double tpDist = 0.0;

            if(UseATRStops && atrValue > 0)
              {
               slDist = atrValue * ATRSLMultiplier;
               tpDist = atrValue * ATRTPMultiplier;
              }
            else
              {
               slDist = StopLossPips * pip;
               tpDist = TakeProfitPips * pip;
              }

            double sl = (slDist > 0) ? NormalizeDouble(ask - slDist, _Digits) : 0.0;
            double tp = (tpDist > 0) ? NormalizeDouble(ask + tpDist, _Digits) : 0.0;

            double slPips = (slDist > 0) ? slDist / pip : 0.0;
            double lot = CalculateLotSize(slPips);

            string comment = StringFormat("TM:%s|SIG:%s", "RSI_MR", "BUY_OVERSOLD");

            if(g_trade.Buy(lot, _Symbol, ask, sl, tp, comment))
              {
               ulong ticket = g_trade.ResultOrder();
               if(ticket > 0)
                  TM_OnTradeOpened(ticket, _Symbol, "buy", lot, ask, sl, tp);
              }
           }
        }
     }

   //--- Entry: SELL when RSI is overbought (and no existing SELL position)
   if(rsiCurr > RSIOverbought && !HasPositionByDirection(POSITION_TYPE_SELL))
     {
      //--- ADX filter: skip if market is trending too hard
      if(!adxBlocked)
        {
         //--- BB confluence: price must be at or above upper band
         bool bbOk = true;
         if(RequireBBConfluence && bbUpper > 0)
           {
            if(lastClose < bbUpper)
               bbOk = false;
           }

         //--- Trend filter: don't sell if price is far above 200 EMA (strong uptrend)
         bool trendOk = true;
         if(TrendMAPeriod > 0 && trendMAValue > 0)
           {
            double trendBuffer = TrendMABuffer * atrValue;
            if(lastClose > trendMAValue + trendBuffer)
               trendOk = false;  // Price too far above EMA — strong uptrend, don't fade
           }

         if(bbOk && trendOk)
           {
            double slDist = 0.0;
            double tpDist = 0.0;

            if(UseATRStops && atrValue > 0)
              {
               slDist = atrValue * ATRSLMultiplier;
               tpDist = atrValue * ATRTPMultiplier;
              }
            else
              {
               slDist = StopLossPips * pip;
               tpDist = TakeProfitPips * pip;
              }

            double sl = (slDist > 0) ? NormalizeDouble(bid + slDist, _Digits) : 0.0;
            double tp = (tpDist > 0) ? NormalizeDouble(bid - tpDist, _Digits) : 0.0;

            double slPips = (slDist > 0) ? slDist / pip : 0.0;
            double lot = CalculateLotSize(slPips);

            string comment = StringFormat("TM:%s|SIG:%s", "RSI_MR", "SELL_OVERBOUGHT");

            if(g_trade.Sell(lot, _Symbol, bid, sl, tp, comment))
              {
               ulong ticket = g_trade.ResultOrder();
               if(ticket > 0)
                  TM_OnTradeOpened(ticket, _Symbol, "sell", lot, bid, sl, tp);
              }
           }
        }
     }

   TM_ManageOpenTrades();
  }

//+------------------------------------------------------------------+
//| Check if a position exists in the given direction                 |
//+------------------------------------------------------------------+
bool HasPositionByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) == direction)
         return true;
     }
   return false;
  }

//+------------------------------------------------------------------+
//| Close all positions in the given direction                        |
//+------------------------------------------------------------------+
void ClosePositionsByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) != direction) continue;

      double profit = PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);

      if(g_trade.PositionClose(ticket))
         TM_OnTradeClosed(ticket, profit);
     }
  }
//+------------------------------------------------------------------+
