//+------------------------------------------------------------------+
//| {{STRATEGY_NAME}} EA                                              |
//| Generated by TradeMetrics Pro Strategy Hub                        |
//+------------------------------------------------------------------+
#property copyright "TradeMetrics Pro"
#property version   "1.00"
#property strict

// ── Includes ────────────────────────────────────────────────────
#include <EdgeRelay_Common.mqh>
#include <EdgeRelay_Crypto.mqh>
#include <EdgeRelay_Http.mqh>
#include <EdgeRelay_Queue.mqh>
#include <EdgeRelay_JournalSync.mqh>
#include <EdgeRelay_JournalQueue.mqh>
#include <Trade\Trade.mqh>

// ── Strategy Parameters ─────────────────────────────────────────
input int              RSIPeriod      = {{RSI_PERIOD}};        // RSI Period
input int              RSIOverbought  = {{RSI_OVERBOUGHT}};    // Overbought Level
input int              RSIOversold    = {{RSI_OVERSOLD}};      // Oversold Level
input ENUM_TIMEFRAMES  Timeframe      = {{TIMEFRAME}};         // Timeframe

// ── Trade Management ────────────────────────────────────────────
input double LotSize            = {{LOT_SIZE}};              // Lot Size
input int    StopLossPips        = {{SL_PIPS}};               // Stop Loss (pips)
input int    TakeProfitPips      = {{TP_PIPS}};               // Take Profit (pips)
input int    MaxSpreadPoints     = {{MAX_SPREAD}};            // Max Spread (points)
input int    MagicNumber         = {{MAGIC_NUMBER}};          // Magic Number

// ── Risk Management ─────────────────────────────────────────────
input double MaxDailyLossPercent   = {{MAX_DAILY_LOSS}};      // Max Daily Loss %
input int    ConsecutiveLossLimit  = {{CONSEC_LOSS_LIMIT}};   // Consecutive Loss Limit
input double BreakevenTriggerRR    = {{BE_TRIGGER_RR}};       // Breakeven at R:R
input double TrailingStopPips      = {{TRAILING_STOP}};       // Trailing Stop (pips)
input bool   UseSessionFilter      = {{USE_SESSION_FILTER}};  // Session Filter
input int    SessionStartHour      = {{SESSION_START}};       // Session Start (UTC)
input int    SessionEndHour        = {{SESSION_END}};         // Session End (UTC)

// ── TradeMetrics Integration ────────────────────────────────────
input string AccountID        = "{{ACCOUNT_ID}}";
input string API_Key          = "{{API_KEY}}";
input string API_Secret       = "";                           // API Secret (enter manually)
input string API_Endpoint     = "https://edgerelay-signal-ingestion.ghwmelite.workers.dev";
input string JournalEndpoint  = "https://edgerelay-journal-sync.ghwmelite.workers.dev";
input bool   EnableJournal    = true;                         // Enable Journal Sync

// ── Shared Integration Block ────────────────────────────────────
{{TRADEMETRICS_BLOCK}}

// ── Strategy Variables ──────────────────────────────────────────
int      g_rsiHandle  = INVALID_HANDLE;
double   g_rsiPrev    = 0.0;
CTrade   g_trade;

//+------------------------------------------------------------------+
//| Expert initialization function                                    |
//+------------------------------------------------------------------+
int OnInit()
  {
   //--- Create RSI handle
   g_rsiHandle = iRSI(_Symbol, Timeframe, RSIPeriod, PRICE_CLOSE);

   if(g_rsiHandle == INVALID_HANDLE)
     {
      PrintFormat("[RSIMeanReversion] Failed to create RSI handle. Error: %d", GetLastError());
      return INIT_FAILED;
     }

   //--- Configure trade object
   g_trade.SetExpertMagicNumber(MagicNumber);
   g_trade.SetDeviationInPoints(10);
   g_trade.SetTypeFilling(ORDER_FILLING_IOC);

   //--- Reset previous RSI
   g_rsiPrev = 0.0;

   //--- Initialize TradeMetrics integration
   return TM_OnInit();
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                  |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   //--- Release indicator handle
   if(g_rsiHandle != INVALID_HANDLE)
      IndicatorRelease(g_rsiHandle);

   TM_OnDeinit(reason);
  }

//+------------------------------------------------------------------+
//| Timer event handler                                               |
//+------------------------------------------------------------------+
void OnTimer()
  {
   TM_OnTimer();
  }

//+------------------------------------------------------------------+
//| Expert tick function                                              |
//+------------------------------------------------------------------+
void OnTick()
  {
   if(!TM_IsNewBar()) return;
   if(!TM_CanTrade()) return;

   //--- Read RSI value for last closed bar
   double rsi[];
   ArraySetAsSeries(rsi, true);

   if(CopyBuffer(g_rsiHandle, 0, 0, 2, rsi) < 2) return;

   double rsiCurr = rsi[1];   // Last closed bar
   double rsiPrev = g_rsiPrev;
   g_rsiPrev = rsiCurr;

   //--- Skip first bar (no previous value yet)
   if(rsiPrev == 0.0) return;

   //--- Calculate pip value for SL/TP
   double pip = _Point * ((_Digits == 3 || _Digits == 5) ? 10 : 1);
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);

   //--- Exit logic: close BUY positions when RSI crosses above 50 (mean reversion complete)
   if(rsiPrev <= 50.0 && rsiCurr > 50.0)
      ClosePositionsByDirection(POSITION_TYPE_BUY);

   //--- Exit logic: close SELL positions when RSI crosses below 50 (mean reversion complete)
   if(rsiPrev >= 50.0 && rsiCurr < 50.0)
      ClosePositionsByDirection(POSITION_TYPE_SELL);

   //--- Entry: BUY when RSI is oversold (and no existing BUY position)
   if(rsiCurr < RSIOversold && !HasPositionByDirection(POSITION_TYPE_BUY))
     {
      double sl = (StopLossPips > 0)   ? NormalizeDouble(ask - StopLossPips * pip, _Digits)   : 0.0;
      double tp = (TakeProfitPips > 0)  ? NormalizeDouble(ask + TakeProfitPips * pip, _Digits) : 0.0;

      if(g_trade.Buy(LotSize, _Symbol, ask, sl, tp, "RSIMeanReversion"))
        {
         ulong ticket = g_trade.ResultOrder();
         if(ticket > 0)
            TM_OnTradeOpened(ticket, _Symbol, "buy", LotSize, ask, sl, tp);
        }
     }

   //--- Entry: SELL when RSI is overbought (and no existing SELL position)
   if(rsiCurr > RSIOverbought && !HasPositionByDirection(POSITION_TYPE_SELL))
     {
      double sl = (StopLossPips > 0)   ? NormalizeDouble(bid + StopLossPips * pip, _Digits)   : 0.0;
      double tp = (TakeProfitPips > 0)  ? NormalizeDouble(bid - TakeProfitPips * pip, _Digits) : 0.0;

      if(g_trade.Sell(LotSize, _Symbol, bid, sl, tp, "RSIMeanReversion"))
        {
         ulong ticket = g_trade.ResultOrder();
         if(ticket > 0)
            TM_OnTradeOpened(ticket, _Symbol, "sell", LotSize, bid, sl, tp);
        }
     }

   TM_ManageOpenTrades();
  }

//+------------------------------------------------------------------+
//| Check if a position exists in the given direction                 |
//+------------------------------------------------------------------+
bool HasPositionByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) == direction)
         return true;
     }
   return false;
  }

//+------------------------------------------------------------------+
//| Close all positions in the given direction                        |
//+------------------------------------------------------------------+
void ClosePositionsByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) != direction) continue;

      double profit = PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);

      if(g_trade.PositionClose(ticket))
         TM_OnTradeClosed(ticket, profit);
     }
  }
//+------------------------------------------------------------------+
