//+------------------------------------------------------------------+
//| {{STRATEGY_NAME}} EA                                              |
//| Generated by TradeMetrics Pro Strategy Hub                        |
//+------------------------------------------------------------------+
#property copyright "TradeMetrics Pro"
#property version   "1.00"
#property strict

// -- Includes ────────────────────────────────────────────────────
#include <EdgeRelay_Common.mqh>
#include <EdgeRelay_Crypto.mqh>
#include <EdgeRelay_Http.mqh>
#include <EdgeRelay_Queue.mqh>
#include <EdgeRelay_JournalSync.mqh>
#include <EdgeRelay_JournalQueue.mqh>
#include <Trade\Trade.mqh>

// -- Strategy Parameters ─────────────────────────────────────────
input int              ZoneLookback     = {{ZONE_LOOKBACK}};      // Zone Detection Lookback
input double           MinZoneStrength  = {{MIN_ZONE_STRENGTH}};  // Min Body-to-Wick Ratio
input int              RetestTolerance  = {{RETEST_TOLERANCE}};   // Retest Tolerance (pips)
input ENUM_TIMEFRAMES  Timeframe        = {{TIMEFRAME}};          // Timeframe

// -- Trade Management ────────────────────────────────────────────
input double LotSize            = {{LOT_SIZE}};              // Lot Size
input int    StopLossPips        = {{SL_PIPS}};               // Stop Loss (pips)
input int    TakeProfitPips      = {{TP_PIPS}};               // Take Profit (pips)
input int    MaxSpreadPoints     = {{MAX_SPREAD}};            // Max Spread (points)
input int    MagicNumber         = {{MAGIC_NUMBER}};          // Magic Number

// -- Risk Management ─────────────────────────────────────────────
input double MaxDailyLossPercent   = {{MAX_DAILY_LOSS}};      // Max Daily Loss %
input int    ConsecutiveLossLimit  = {{CONSEC_LOSS_LIMIT}};   // Consecutive Loss Limit
input double BreakevenTriggerRR    = {{BE_TRIGGER_RR}};       // Breakeven at R:R
input double TrailingStopPips      = {{TRAILING_STOP}};       // Trailing Stop (pips)
input bool   UseSessionFilter      = {{USE_SESSION_FILTER}};  // Session Filter
input int    SessionStartHour      = {{SESSION_START}};       // Session Start (UTC)
input int    SessionEndHour        = {{SESSION_END}};         // Session End (UTC)

// -- TradeMetrics Integration ────────────────────────────────────
input string AccountID        = "{{ACCOUNT_ID}}";
input string API_Key          = "{{API_KEY}}";
input string API_Secret       = "";                           // API Secret (enter manually)
input string API_Endpoint     = "https://edgerelay-signal-ingestion.ghwmelite.workers.dev";
input string JournalEndpoint  = "https://edgerelay-journal-sync.ghwmelite.workers.dev";
input bool   EnableJournal    = true;                         // Enable Journal Sync

// -- Shared Integration Block ────────────────────────────────────
{{TRADEMETRICS_BLOCK}}

// -- Strategy Variables ──────────────────────────────────────────
#define MAX_ZONES 3

struct SZone
  {
   double price;
   bool   active;
  };

SZone    g_demandZones[MAX_ZONES];
SZone    g_supplyZones[MAX_ZONES];
int      g_demandCount = 0;
int      g_supplyCount = 0;
CTrade   g_trade;

//+------------------------------------------------------------------+
//| Expert initialization function                                    |
//+------------------------------------------------------------------+
int OnInit()
  {
   //--- Reset zones
   for(int i = 0; i < MAX_ZONES; i++)
     {
      g_demandZones[i].price  = 0.0;
      g_demandZones[i].active = false;
      g_supplyZones[i].price  = 0.0;
      g_supplyZones[i].active = false;
     }
   g_demandCount = 0;
   g_supplyCount = 0;

   //--- Configure trade object
   g_trade.SetExpertMagicNumber(MagicNumber);
   g_trade.SetDeviationInPoints(10);
   g_trade.SetTypeFilling(ORDER_FILLING_IOC);

   //--- Initialize TradeMetrics integration
   return TM_OnInit();
  }

//+------------------------------------------------------------------+
//| Expert deinitialization function                                  |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
  {
   TM_OnDeinit(reason);
  }

//+------------------------------------------------------------------+
//| Timer event handler                                               |
//+------------------------------------------------------------------+
void OnTimer()
  {
   TM_OnTimer();
  }

//+------------------------------------------------------------------+
//| Expert tick function                                              |
//+------------------------------------------------------------------+
void OnTick()
  {
   if(!TM_IsNewBar()) return;
   if(!TM_CanTrade()) return;

   double pip = _Point * ((_Digits == 3 || _Digits == 5) ? 10 : 1);
   double ask = SymbolInfoDouble(_Symbol, SYMBOL_ASK);
   double bid = SymbolInfoDouble(_Symbol, SYMBOL_BID);
   double tolerance = RetestTolerance * pip;

   //--- Scan for new impulse candles and build zones
   ScanForZones(pip);

   //--- Invalidate broken zones
   double close1 = iClose(_Symbol, Timeframe, 1);

   for(int i = 0; i < g_demandCount; i++)
     {
      if(g_demandZones[i].active && close1 < g_demandZones[i].price - tolerance)
         g_demandZones[i].active = false;
     }
   for(int i = 0; i < g_supplyCount; i++)
     {
      if(g_supplyZones[i].active && close1 > g_supplyZones[i].price + tolerance)
         g_supplyZones[i].active = false;
     }

   //--- BUY: price retests a demand zone
   for(int i = 0; i < g_demandCount; i++)
     {
      if(!g_demandZones[i].active) continue;

      double low1 = iLow(_Symbol, Timeframe, 1);
      if(low1 <= g_demandZones[i].price + tolerance && close1 > g_demandZones[i].price)
        {
         if(!HasPositionByDirection(POSITION_TYPE_BUY))
           {
            double riskDist = ask - g_demandZones[i].price;
            double sl = (StopLossPips > 0) ? NormalizeDouble(ask - StopLossPips * pip, _Digits)
                                           : NormalizeDouble(g_demandZones[i].price - tolerance, _Digits);
            double tp = (TakeProfitPips > 0) ? NormalizeDouble(ask + TakeProfitPips * pip, _Digits)
                                             : NormalizeDouble(ask + riskDist * 2.0, _Digits);

            if(g_trade.Buy(LotSize, _Symbol, ask, sl, tp, "SDZone"))
              {
               ulong ticket = g_trade.ResultOrder();
               if(ticket > 0)
                  TM_OnTradeOpened(ticket, _Symbol, "buy", LotSize, ask, sl, tp);
              }
           }
         break;
        }
     }

   //--- SELL: price retests a supply zone
   for(int i = 0; i < g_supplyCount; i++)
     {
      if(!g_supplyZones[i].active) continue;

      double high1 = iHigh(_Symbol, Timeframe, 1);
      if(high1 >= g_supplyZones[i].price - tolerance && close1 < g_supplyZones[i].price)
        {
         if(!HasPositionByDirection(POSITION_TYPE_SELL))
           {
            double riskDist = g_supplyZones[i].price - bid;
            double sl = (StopLossPips > 0) ? NormalizeDouble(bid + StopLossPips * pip, _Digits)
                                           : NormalizeDouble(g_supplyZones[i].price + tolerance, _Digits);
            double tp = (TakeProfitPips > 0) ? NormalizeDouble(bid - TakeProfitPips * pip, _Digits)
                                             : NormalizeDouble(bid - riskDist * 2.0, _Digits);

            if(g_trade.Sell(LotSize, _Symbol, bid, sl, tp, "SDZone"))
              {
               ulong ticket = g_trade.ResultOrder();
               if(ticket > 0)
                  TM_OnTradeOpened(ticket, _Symbol, "sell", LotSize, bid, sl, tp);
              }
           }
         break;
        }
     }

   TM_ManageOpenTrades();
  }

//+------------------------------------------------------------------+
//| Scan for impulse candles and register zones                       |
//+------------------------------------------------------------------+
void ScanForZones(double pip)
  {
   //--- Reset zones each scan
   g_demandCount = 0;
   g_supplyCount = 0;

   for(int bar = 1; bar <= ZoneLookback && bar < iBars(_Symbol, Timeframe); bar++)
     {
      double open  = iOpen(_Symbol, Timeframe, bar);
      double close = iClose(_Symbol, Timeframe, bar);
      double high  = iHigh(_Symbol, Timeframe, bar);
      double low   = iLow(_Symbol, Timeframe, bar);

      double body    = MathAbs(close - open);
      double upperWk = high - MathMax(open, close);
      double lowerWk = MathMin(open, close) - low;
      double totalWk = upperWk + lowerWk;

      //--- Avoid division by zero
      if(totalWk < pip * 0.1) totalWk = pip * 0.1;

      double ratio = body / totalWk;
      if(ratio < MinZoneStrength) continue;

      //--- Bullish impulse → demand zone at candle low
      if(close > open && g_demandCount < MAX_ZONES)
        {
         g_demandZones[g_demandCount].price  = low;
         g_demandZones[g_demandCount].active = true;
         g_demandCount++;
        }

      //--- Bearish impulse → supply zone at candle high
      if(close < open && g_supplyCount < MAX_ZONES)
        {
         g_supplyZones[g_supplyCount].price  = high;
         g_supplyZones[g_supplyCount].active = true;
         g_supplyCount++;
        }
     }
  }

//+------------------------------------------------------------------+
//| Check if a position exists in the given direction                 |
//+------------------------------------------------------------------+
bool HasPositionByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) == direction)
         return true;
     }
   return false;
  }

//+------------------------------------------------------------------+
//| Close all positions in the given direction                        |
//+------------------------------------------------------------------+
void ClosePositionsByDirection(ENUM_POSITION_TYPE direction)
  {
   for(int i = PositionsTotal() - 1; i >= 0; i--)
     {
      ulong ticket = PositionGetTicket(i);
      if(ticket == 0) continue;
      if(PositionGetInteger(POSITION_MAGIC) != MagicNumber) continue;
      if(PositionGetString(POSITION_SYMBOL) != _Symbol) continue;
      if((ENUM_POSITION_TYPE)PositionGetInteger(POSITION_TYPE) != direction) continue;

      double profit = PositionGetDouble(POSITION_PROFIT) + PositionGetDouble(POSITION_SWAP);

      if(g_trade.PositionClose(ticket))
         TM_OnTradeClosed(ticket, profit);
     }
  }
//+------------------------------------------------------------------+
